// react-app-source/src/components/shared/Header.js
import React, { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { useAudio } from '../../contexts/AudioContext';

function Header() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const { isPlaying, toggle } = useAudio();

  const toggleMobileMenu = () => {
    setMobileMenuOpen(!mobileMenuOpen);
  };

  const closeMobileMenu = () => {
    setMobileMenuOpen(false);
  };

  const handleTogglePlayback = () => {
    // toggle() may return a promise, handle it gracefully
    const result = toggle();
    if (result && typeof result.catch === 'function') {
      result.catch(err => {
        console.log('Audio toggle prevented:', err);
      });
    }
  };

  return (
    <nav className="main-nav">
      <div className="nav-container">
        <div className="logo">
          <Link to="/home">
            <img
              src="/assets/img/logo.png"
              alt="PASC Region J"
              className={`logo-img ${isPlaying ? 'rotating' : ''}`}
              id="navLogo"
            />
            <span className="logo-text">PASC REGION J</span>
          </Link>
        </div>

        <ul className={`nav-menu ${mobileMenuOpen ? 'active' : ''}`}>
          <li>
            <NavLink to="/home" className={({ isActive }) => isActive ? 'active' : ''} onClick={closeMobileMenu}>
              Home
            </NavLink>
          </li>
          <li>
            <NavLink to="/about" className={({ isActive }) => isActive ? 'active' : ''} onClick={closeMobileMenu}>
              About
            </NavLink>
          </li>
          <li>
            <NavLink to="/register" className={({ isActive }) => isActive ? 'active' : ''} onClick={closeMobileMenu}>
              Registration
            </NavLink>
          </li>
          <li>
            <NavLink to="/workshops" className={({ isActive }) => isActive ? 'active' : ''} onClick={closeMobileMenu}>
              Workshops
            </NavLink>
          </li>
          <li>
            <NavLink to="/schedule" className={({ isActive }) => isActive ? 'active' : ''} onClick={closeMobileMenu}>
              Schedule
            </NavLink>
          </li>
          <li>
            <NavLink to="/gallery" className={({ isActive }) => isActive ? 'active' : ''} onClick={closeMobileMenu}>
              Gallery
            </NavLink>
          </li>
          <li>
            <NavLink to="/resources" className={({ isActive }) => isActive ? 'active' : ''} onClick={closeMobileMenu}>
              Resources
            </NavLink>
          </li>
          <li>
            <NavLink to="/contact" className={({ isActive }) => isActive ? 'active' : ''} onClick={closeMobileMenu}>
              Contact
            </NavLink>
          </li>
        </ul>

        {/* Mute Toggle Button */}
        <button
          className={`mute-toggle-btn ${isPlaying ? 'playing' : 'muted'}`}
          id="muteToggleBtn"
          onClick={handleTogglePlayback}
          title="Mute/Unmute"
        >
          <span className="mute-icon" id="muteIcon" dangerouslySetInnerHTML={{ __html: isPlaying ? '&#128266;' : '&#128263;' }} />
          <span className="mute-label" id="muteLabel">
            {isPlaying ? 'MUTE' : 'UNMUTE'}
          </span>
        </button>

        {/* Mobile menu toggle button */}
        <button
          className={`mobile-menu-toggle ${mobileMenuOpen ? 'active' : ''}`}
          aria-label="Toggle menu"
          onClick={toggleMobileMenu}
        >
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </nav>
  );
}

export default Header;

// angular-app-source/src/app/components/shared/header.component.ts
import { Component, signal, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AudioService } from '../../services/audio.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <nav class="main-nav">
      <div class="nav-container">
        <div class="logo">
          <a routerLink="/home">
            <img
              src="/assets/img/logo.png"
              alt="PASC Region J"
              class="logo-img"
              id="navLogo"
              [class.rotating]="isPlaying()">
            <span class="logo-text">PASC REGION J</span>
          </a>
        </div>

        <ul class="nav-menu" [class.active]="mobileMenuOpen()">
          <li><a routerLink="/home" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" (click)="closeMobileMenu()">Home</a></li>
          <li><a routerLink="/about" routerLinkActive="active" (click)="closeMobileMenu()">About</a></li>
          <li><a routerLink="/register" routerLinkActive="active" (click)="closeMobileMenu()">Registration</a></li>
          <li><a routerLink="/workshops" routerLinkActive="active" (click)="closeMobileMenu()">Workshops</a></li>
          <li><a routerLink="/schedule" routerLinkActive="active" (click)="closeMobileMenu()">Schedule</a></li>
          <li><a routerLink="/gallery" routerLinkActive="active" (click)="closeMobileMenu()">Gallery</a></li>
          <li><a routerLink="/resources" routerLinkActive="active" (click)="closeMobileMenu()">Resources</a></li>
          <li><a routerLink="/contact" routerLinkActive="active" (click)="closeMobileMenu()">Contact</a></li>
        </ul>

        <!-- Mute Toggle Button -->
        <button
          class="mute-toggle-btn"
          id="muteToggleBtn"
          (click)="togglePlayback()"
          title="Mute/Unmute"
          [class.playing]="isPlaying()"
          [class.muted]="!isPlaying()">
          <span class="mute-icon" id="muteIcon">{{ isPlaying() ? '&#128266;' : '&#128263;' }}</span>
          <span class="mute-label" id="muteLabel">{{ isPlaying() ? 'MUTE' : 'UNMUTE' }}</span>
        </button>

        <!-- Mobile menu toggle button -->
        <button class="mobile-menu-toggle" aria-label="Toggle menu" (click)="toggleMobileMenu()">
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </nav>
  `,
  styles: [`
    /* All styles are in global CSS files: style.css, anthem-player.css */
  `]
})
export class HeaderComponent implements OnInit, OnDestroy {
  mobileMenuOpen = signal(false);
  isPlaying = signal(false);
  isMuted = signal(false);

  private subscriptions: Subscription[] = [];

  constructor(private audioService: AudioService) {}

  ngOnInit(): void {
    // Subscribe to audio playing state
    const playingSub = this.audioService.isPlaying$.subscribe(playing => {
      this.isPlaying.set(playing);
    });

    // Subscribe to audio muted state
    const mutedSub = this.audioService.isMuted$.subscribe(muted => {
      this.isMuted.set(muted);
    });

    this.subscriptions.push(playingSub, mutedSub);
  }

  ngOnDestroy(): void {
    // Unsubscribe from all subscriptions
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  toggleMobileMenu() {
    this.mobileMenuOpen.update(value => !value);
  }

  closeMobileMenu() {
    this.mobileMenuOpen.set(false);
  }

  togglePlayback() {
    this.audioService.toggle();
  }
}
