// react-app-source/src/pages/admin/GalleryUpload.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { galleryService } from '../../services/admin-api';

function GalleryUpload() {
  const navigate = useNavigate();

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [selectedFile, setSelectedFile] = useState(null);
  const [preview, setPreview] = useState(null);

  const [formData, setFormData] = useState({
    title: '',
    page_location: 'gallery',
    is_active: false
  });

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setSelectedFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.title.trim()) {
      setError('Image Title is required');
      return;
    }
    if (!selectedFile) {
      setError('Please select an image to upload');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const uploadData = new FormData();
      uploadData.append('image_file', selectedFile);
      uploadData.append('title', formData.title);
      uploadData.append('page_location', formData.page_location);
      uploadData.append('is_active', formData.is_active ? '1' : '0');

      await galleryService.upload(uploadData);
      navigate('/admin/gallery');
    } catch (err) {
      setError(err.message || 'Failed to upload image');
      setLoading(false);
      console.error('Error uploading image:', err);
    }
  };

  const cancel = () => {
    navigate('/admin/gallery');
  };

  return (
    <>
      <div className="content-header">
        <h1>Upload New Image</h1>
        <p className="section-subtitle">Add a new image to {formData.page_location === 'about_page' ? 'About Page' : 'Gallery'}</p>
      </div>

      <div className="action-bar">
        <button className="btn btn-secondary" onClick={cancel}>
          ← Back to Gallery
        </button>
      </div>

      {error && <div className="alert alert-error">{error}</div>}

      <form className="admin-form" onSubmit={handleSubmit}>
        {/* Image Title */}
        <div className="form-group">
          <label htmlFor="title">Image Title <span className="required">*</span></label>
          <input
            type="text"
            id="title"
            name="title"
            className="form-control"
            value={formData.title}
            onChange={handleInputChange}
            placeholder="Enter image title"
            maxLength="255"
            required
          />
          <small className="form-help">This title will be displayed with the image</small>
        </div>

        {/* Page Location */}
        <div className="form-group">
          <label htmlFor="page_location">Page Location <span className="required">*</span></label>
          <select
            id="page_location"
            name="page_location"
            className="form-control"
            value={formData.page_location}
            onChange={handleInputChange}
          >
            <option value="about_page">About Page</option>
            <option value="gallery">Gallery</option>
          </select>
          <small className="form-help">Where should this image appear on the website?</small>
        </div>

        {/* Image File Upload */}
        <div className="form-group">
          <label htmlFor="file">Image File <span className="required">*</span></label>
          <input
            type="file"
            id="file"
            className="form-control"
            accept="image/jpeg,image/jpg,image/png,image/gif,image/webp"
            onChange={handleFileChange}
            required
          />
          <small className="form-help">Supported formats: JPG, PNG, GIF, WebP (Max 5MB)</small>
        </div>

        {/* Image Preview */}
        {preview && (
          <div className="form-group">
            <label>Preview</label>
            <div className="image-preview">
              <img src={preview} alt="Preview" style={{ maxWidth: '300px', maxHeight: '200px' }} />
            </div>
          </div>
        )}

        {/* Is Active Checkbox */}
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              name="is_active"
              checked={formData.is_active}
              onChange={handleInputChange}
            />
            <span>Active (visible on website)</span>
          </label>
        </div>

        <div className="form-actions">
          <button type="submit" className="btn btn-primary" disabled={loading}>
            {loading ? 'Uploading...' : 'Upload Image'}
          </button>
          <button type="button" className="btn btn-secondary" onClick={cancel} disabled={loading}>
            Cancel
          </button>
        </div>
      </form>
    </>
  );
}

export default GalleryUpload;

// angular-app-source/src/app/admin/gallery/gallery-upload/gallery-upload.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { GalleryService } from '../../services/gallery.service';

@Component({
  selector: 'app-gallery-upload',
  standalone: false,
  templateUrl: './gallery-upload.component.html',
  styleUrls: ['./gallery-upload.component.css']
})
export class GalleryUploadComponent implements OnInit {
  loading = false;
  error: string | null = null;
  currentLocation: 'about_page' | 'gallery' = 'gallery';
  selectedFile: File | null = null;
  previewUrl: string | null = null;

  // Form data
  formData = {
    title: '',
    page_location: 'gallery' as 'about_page' | 'gallery',
    is_active: false
  };

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private galleryService: GalleryService
  ) {}

  ngOnInit(): void {
    // Get location from query params
    this.route.queryParams.subscribe(params => {
      this.currentLocation = (params['location'] as 'about_page' | 'gallery') || 'gallery';
      this.formData.page_location = this.currentLocation;
    });
  }

  /**
   * Handle file selection
   */
  onFileSelected(event: any): void {
    const file = event.target.files[0];
    if (file) {
      // Validate file type
      const validTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];
      if (!validTypes.includes(file.type)) {
        this.error = 'Invalid file type. Only JPG, PNG, GIF, and WebP images are allowed.';
        this.selectedFile = null;
        this.previewUrl = null;
        return;
      }

      // Validate file size (5MB max)
      if (file.size > 5242880) {
        this.error = 'File size exceeds 5MB maximum. Please choose a smaller image.';
        this.selectedFile = null;
        this.previewUrl = null;
        return;
      }

      this.selectedFile = file;
      this.error = null;

      // Generate preview
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.previewUrl = e.target.result;
      };
      reader.readAsDataURL(file);
    }
  }

  /**
   * Submit upload form
   */
  onSubmit(): void {
    // Validate
    if (!this.formData.title.trim()) {
      this.error = 'Image Title is required';
      return;
    }
    if (!this.selectedFile) {
      this.error = 'Image File is required';
      return;
    }

    this.loading = true;
    this.error = null;

    // Create FormData for file upload
    const uploadData = new FormData();
    uploadData.append('image_file', this.selectedFile);
    uploadData.append('title', this.formData.title);
    uploadData.append('page_location', this.formData.page_location);
    uploadData.append('is_active', this.formData.is_active ? '1' : '0');

    this.galleryService.upload(uploadData).subscribe({
      next: () => {
        // Redirect immediately to list page
        this.router.navigate(['/admin/gallery'], {
          queryParams: { location: this.formData.page_location }
        });
      },
      error: (err) => {
        this.error = err.message || 'Failed to upload image';
        this.loading = false;
        console.error('Error uploading image:', err);
      }
    });
  }

  /**
   * Cancel and return to list
   */
  cancel(): void {
    this.router.navigate(['/admin/gallery'], {
      queryParams: { location: this.currentLocation }
    });
  }
}

<!-- Content Header -->
<div class="content-header">
  <h1>Upload New Image</h1>
  <p class="section-subtitle">Add a new image to {{ currentLocation === 'about_page' ? 'About Page' : 'Gallery' }}</p>
</div>

<!-- Back Button -->
<div class="action-bar">
  <button class="btn btn-secondary" (click)="cancel()">
    ← Back to Gallery
  </button>
</div>

<!-- Error Message -->
<div class="alert alert-error" *ngIf="error">
  {{ error }}
</div>

<!-- Upload Form -->
<form class="admin-form" (ngSubmit)="onSubmit()">
  <!-- Image Title -->
  <div class="form-group">
    <label for="title">Image Title <span class="required">*</span></label>
    <input
      type="text"
      id="title"
      name="title"
      class="form-control"
      [(ngModel)]="formData.title"
      placeholder="Enter image title"
      maxlength="255"
      required
    />
    <small class="form-help">This title will be displayed with the image</small>
  </div>

  <!-- Page Location -->
  <div class="form-group">
    <label for="page_location">Page Location <span class="required">*</span></label>
    <select
      id="page_location"
      name="page_location"
      class="form-control"
      [(ngModel)]="formData.page_location"
      required
    >
      <option value="about_page">About Page</option>
      <option value="gallery">Gallery</option>
    </select>
    <small class="form-help">Where should this image appear on the website?</small>
  </div>

  <!-- Image File Upload -->
  <div class="form-group">
    <label for="image_file">Image File <span class="required">*</span></label>
    <input
      type="file"
      id="image_file"
      name="image_file"
      class="form-control"
      accept="image/jpeg,image/jpg,image/png,image/gif,image/webp"
      (change)="onFileSelected($event)"
      required
    />
    <small class="form-help">Supported formats: JPG, PNG, GIF, WebP (Max 5MB)</small>
  </div>

  <!-- Image Preview -->
  <div class="form-group" *ngIf="previewUrl">
    <label>Preview</label>
    <div class="image-preview">
      <img [src]="previewUrl" alt="Preview">
    </div>
  </div>

  <!-- Is Active Checkbox -->
  <div class="form-group">
    <label class="checkbox-label">
      <input
        type="checkbox"
        name="is_active"
        [(ngModel)]="formData.is_active"
      />
      <span>Active (visible on website)</span>
    </label>
  </div>

  <!-- Form Actions -->
  <div class="form-actions">
    <button
      type="submit"
      class="btn btn-primary"
      [disabled]="loading"
    >
      {{ loading ? 'Uploading...' : 'Upload Image' }}
    </button>

    <button
      type="button"
      class="btn btn-secondary"
      (click)="cancel()"
      [disabled]="loading"
    >
      Cancel
    </button>
  </div>
</form>
