// react-app-source/src/pages/admin/ForgotPassword.js
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';

function ForgotPassword() {
  const { requestPasswordReset } = useAuth();

  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');
  const [emailSent, setEmailSent] = useState(false);

  const validateEmail = (email) => {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!email || !validateEmail(email)) {
      setErrorMessage('Please enter a valid email address.');
      return;
    }

    setLoading(true);
    setErrorMessage('');
    setSuccessMessage('');

    try {
      const response = await requestPasswordReset(email.trim());
      console.log('Password reset API response:', response);
      setLoading(false);

      if (response.success) {
        setEmailSent(true);
      } else {
        console.warn('Password reset returned unsuccessful:', response.message);
        // Always show success to prevent email enumeration
        setEmailSent(true);
      }
    } catch (error) {
      console.error('Password reset API error:', error);
      setLoading(false);
      // Always show success to prevent email enumeration
      setEmailSent(true);
    }
  };

  return (
    <div className="admin-login-page">
      <div className="login-container">
        <div className="login-box">
        <div className="login-header">
          <div className="logo">
            <img src="/assets/img/logo.png" alt="PASC Region J" className="logo-img" />
          </div>
          <h1>Reset Password</h1>
          <p>PASC Region J Conference 2026</p>
        </div>

        {/* Success Message */}
        {successMessage && (
          <div className="alert alert-success">
            {successMessage}
          </div>
        )}

        {/* Error Message */}
        {errorMessage && (
          <div className="alert alert-error">
            {errorMessage}
          </div>
        )}

        {/* Reset Form */}
        {!emailSent && (
          <form onSubmit={handleSubmit} className="login-form">
            <p className="form-instructions">
              Enter your email address and we'll send you a link to reset your password.
            </p>

            <div className="form-group">
              <label htmlFor="email">Email Address</label>
              <input
                type="email"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="form-control"
                placeholder="Enter your email"
                autoComplete="email"
                autoFocus
              />
            </div>

            <button
              type="submit"
              className="btn btn-login"
              disabled={loading || !email}
            >
              {loading ? 'Sending...' : 'Send Reset Link'}
            </button>
          </form>
        )}

        {/* Success state - show after email sent */}
        {emailSent && (
          <div className="login-form">
            <div className="success-box">
              <div className="success-icon">✓</div>
              <h3>Check Your Email</h3>
              <p>If an account exists with that email address, you will receive a password reset link shortly.</p>
              <p>Please check your email and follow the instructions to reset your password.</p>
              <p className="note">The link will expire in 1 hour.</p>
            </div>
          </div>
        )}

        <div className="login-footer">
          <Link to="/admin" className="btn btn-back">← Back to Login</Link>
        </div>
        </div>
      </div>
    </div>
  );
}

export default ForgotPassword;

// Front_End/angular-app-source/src/app/admin/auth/forgot-password/forgot-password.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-forgot-password',
  standalone: false,
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.css']
})
export class ForgotPasswordComponent {
  resetForm: FormGroup;
  loading = false;
  errorMessage = '';
  successMessage = '';
  emailSent = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService
  ) {
    this.resetForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]]
    });
  }

  onSubmit(): void {
    if (this.resetForm.invalid) {
      this.errorMessage = 'Please enter a valid email address.';
      return;
    }

    this.loading = true;
    this.errorMessage = '';
    this.successMessage = '';

    const email = this.resetForm.value.email.trim();

    this.authService.requestPasswordReset(email).subscribe({
      next: (response) => {
        console.log('Password reset API response:', response);
        this.loading = false;
        if (response.success) {
          this.emailSent = true;
          //this.successMessage = 'Password reset link sent successfully!';
        } else {
          console.warn('Password reset returned unsuccessful:', response.message);
          // Always show success to prevent email enumeration
          this.emailSent = true;
        }
      },
      error: (error) => {
        console.error('Password reset API error:', error);
        this.loading = false;
        // Always show success to prevent email enumeration
        this.emailSent = true;
      }
    });
  }

  get emailControl() {
    return this.resetForm.get('email');
  }
}

<div class="login-container">
  <div class="login-box">
    <div class="login-header">
      <div class="logo">
        <img src="/assets/img/logo.png" alt="PASC Region J" class="logo-img">
      </div>
      <h1>Reset Password</h1>
      <p>PASC Region J Conference 2026</p>
    </div>

    <!-- Success Message -->
    <div *ngIf="successMessage" class="alert alert-success">
      {{ successMessage }}
    </div>

    <!-- Error Message -->
    <div *ngIf="errorMessage" class="alert alert-error">
      {{ errorMessage }}
    </div>

    <!-- Reset Form -->
    <form *ngIf="!emailSent" [formGroup]="resetForm" (ngSubmit)="onSubmit()" class="login-form">
      <p class="form-instructions">
        Enter your email address and we'll send you a link to reset your password.
      </p>

      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          id="email"
          formControlName="email"
          class="form-control"
          placeholder="Enter your email"
          autocomplete="email"
          autofocus
          [class.error]="emailControl?.invalid && emailControl?.touched">
      </div>

      <button
        type="submit"
        class="btn btn-login"
        [disabled]="loading || resetForm.invalid">
        <span *ngIf="!loading">Send Reset Link</span>
        <span *ngIf="loading">Sending...</span>
      </button>
    </form>

    <!-- Success state - show after email sent -->
    <div *ngIf="emailSent" class="login-form">
      <div class="success-box">
        <div class="success-icon">✓</div>
        <h3>Check Your Email</h3>
        <p>If an account exists with that email address, you will receive a password reset link shortly.</p>
        <p>Please check your email and follow the instructions to reset your password.</p>
        <p class="note">The link will expire in 1 hour.</p>
      </div>
    </div>

    <div class="login-footer">
      <a routerLink="/admin" class="btn btn-back">← Back to Login</a>
    </div>
  </div>
</div>
