// react-app-source/src/pages/admin/AnnouncementDelete.js
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { announcementsService } from '../../services/admin-api';

function AnnouncementDelete() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [announcement, setAnnouncement] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (id) {
      loadAnnouncement();
    } else {
      setError('No announcement ID provided');
    }
  }, [id]);

  const loadAnnouncement = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await announcementsService.getById(id);
      setAnnouncement(response.data);
      setLoading(false);
    } catch (err) {
      setError('Failed to load announcement');
      setLoading(false);
      console.error('Error loading announcement:', err);
    }
  };

  const confirmDelete = async () => {
    setLoading(true);
    setError(null);

    try {
      await announcementsService.delete(id);
      navigate('/admin/announcements');
    } catch (err) {
      setError('Failed to delete announcement');
      setLoading(false);
      console.error('Error deleting announcement:', err);
    }
  };

  const cancel = () => {
    navigate('/admin/announcements');
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'No end date';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  };

  return (
    <>
      {/* Content Header */}
      <div className="content-header">
        <h1>Delete Announcement</h1>
        <p className="section-subtitle">Confirm deletion of this announcement</p>
      </div>

      {/* Back Button */}
      <div className="action-bar">
        <button className="btn btn-secondary" onClick={cancel}>
          ← Back to Announcements
        </button>
      </div>

      {/* Error Message */}
      {error && (
        <div className="alert alert-error">
          {error}
        </div>
      )}

      {/* Loading State */}
      {loading && !announcement && (
        <div className="loading-container">
          <div className="spinner"></div>
          <p>Loading announcement...</p>
        </div>
      )}

      {/* Delete Confirmation */}
      {announcement && (
        <div className="delete-confirmation">
          <div className="warning-box">
            <div className="warning-icon">⚠️</div>
            <h2>Are you sure you want to delete this announcement?</h2>
            <p>This action cannot be undone.</p>
          </div>

          <div className="item-preview">
            <h3>Announcement Details:</h3>
            <div className="preview-field">
              <strong>Title:</strong>
              <span>{announcement.title}</span>
            </div>
            <div className="preview-field">
              <strong>Content:</strong>
              <span>{announcement.content}</span>
            </div>
            <div className="preview-field">
              <strong>Publish Start:</strong>
              <span>{formatDate(announcement.publish_start)}</span>
            </div>
            <div className="preview-field">
              <strong>Publish End:</strong>
              <span>{formatDate(announcement.publish_end)}</span>
            </div>
            <div className="preview-field">
              <strong>Status:</strong>
              <span>{announcement.is_active ? 'Active' : 'Inactive'}</span>
            </div>
          </div>

          <div className="form-actions">
            <button
              className="btn btn-danger"
              onClick={confirmDelete}
              disabled={loading}
            >
              {loading ? 'Deleting...' : 'Yes, Delete Announcement'}
            </button>

            <button
              className="btn btn-secondary"
              onClick={cancel}
              disabled={loading}
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </>
  );
}

export default AnnouncementDelete;

// Front_End/angular-app/src/app/admin/announcements/announcement-delete/announcement-delete.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AnnouncementsService } from '../../services/announcements.service';
import { Announcement } from '../../models/announcement.model';

@Component({
  selector: 'app-announcement-delete',
  standalone: false,
  templateUrl: './announcement-delete.component.html',
  styleUrls: ['./announcement-delete.component.css']
})
export class AnnouncementDeleteComponent implements OnInit {
  announcement: Announcement | null = null;
  loading = false;
  error: string | null = null;
  announcementId: number | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private announcementsService: AnnouncementsService
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.announcementId = +params['id'];
        this.loadAnnouncement();
      } else {
        this.error = 'No announcement ID provided';
      }
    });
  }

  /**
   * Load announcement details for confirmation display
   */
  loadAnnouncement(): void {
    if (!this.announcementId) return;

    this.loading = true;
    this.error = null;

    this.announcementsService.getById(this.announcementId).subscribe({
      next: (data) => {
        this.announcement = data;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load announcement';
        this.loading = false;
        console.error('Error loading announcement:', err);
      }
    });
  }

  /**
   * Confirm and delete the announcement
   */
  confirmDelete(): void {
    if (!this.announcementId) return;

    this.loading = true;
    this.error = null;

    this.announcementsService.delete(this.announcementId).subscribe({
      next: () => {
        // Redirect back to list
        this.router.navigate(['/admin/announcements']);
      },
      error: (err) => {
        this.error = 'Failed to delete announcement';
        this.loading = false;
        console.error('Error deleting announcement:', err);
      }
    });
  }

  /**
   * Cancel and return to list
   */
  cancel(): void {
    this.router.navigate(['/admin/announcements']);
  }

  /**
   * Format date for display
   */
  formatDate(dateString: string | null): string {
    if (!dateString) return 'No end date';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  }
}

<!-- Content Header -->
<div class="content-header">
  <h1>Delete Announcement</h1>
  <p class="section-subtitle">Confirm deletion</p>
</div>

<!-- Back Button -->
<div class="action-bar">
  <button class="btn btn-secondary" (click)="cancel()">
    ← Back to Announcements
  </button>
</div>

<!-- Error Message -->
<div class="alert alert-error" *ngIf="error">
  {{ error }}
</div>

<!-- Loading State -->
<div class="loading-container" *ngIf="loading && !announcement">
  <div class="spinner"></div>
  <p>Loading announcement...</p>
</div>

<!-- Delete Confirmation -->
<div class="delete-confirmation" *ngIf="!loading && announcement">
  <!-- Warning Icon and Message -->
  <div class="warning-box">
    <div class="warning-icon">⚠️</div>
    <h2>Are you sure you want to delete this announcement?</h2>
    <p class="warning-text">This action cannot be undone. The announcement will be permanently removed.</p>
  </div>

  <!-- Announcement Details -->
  <div class="details-box">
    <h3>Announcement Details</h3>

    <div class="detail-row">
      <span class="detail-label">Title:</span>
      <span class="detail-value">{{ announcement.title }}</span>
    </div>

    <div class="detail-row">
      <span class="detail-label">Content:</span>
      <span class="detail-value">{{ announcement.content }}</span>
    </div>

    <div class="detail-row">
      <span class="detail-label">Status:</span>
      <span class="detail-value">
        <span class="badge" [class.badge-success]="announcement.is_active" [class.badge-inactive]="!announcement.is_active">
          {{ announcement.is_active ? 'Active' : 'Inactive' }}
        </span>
        <span class="badge badge-featured" *ngIf="announcement.is_featured">Featured</span>
      </span>
    </div>

    <div class="detail-row">
      <span class="detail-label">Publish Start:</span>
      <span class="detail-value">{{ formatDate(announcement.publish_start) }}</span>
    </div>

    <div class="detail-row" *ngIf="announcement.publish_end">
      <span class="detail-label">Publish End:</span>
      <span class="detail-value">{{ formatDate(announcement.publish_end) }}</span>
    </div>

    <div class="detail-row">
      <span class="detail-label">Display Order:</span>
      <span class="detail-value">{{ announcement.display_order }}</span>
    </div>
  </div>

  <!-- Confirmation Actions -->
  <div class="form-actions">
    <button
      type="button"
      class="btn btn-danger"
      (click)="confirmDelete()"
      [disabled]="loading"
    >
      {{ loading ? 'Deleting...' : 'Yes, Delete Announcement' }}
    </button>

    <button
      type="button"
      class="btn btn-secondary"
      (click)="cancel()"
      [disabled]="loading"
    >
      Cancel
    </button>
  </div>
</div>
