// react-app-source/src/pages/PreIntro.js
import React, { useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';

function PreIntro() {
  const navigate = useNavigate();
  const videoRef = useRef(null);

  useEffect(() => {
    // Check if user has already seen the intro sequence
    const introSeen = sessionStorage.getItem('introSeen');
    if (introSeen === 'true') {
      navigate('/home');
      return;
    }

    // Force video to play
    const video = videoRef.current;
    if (video) {
      video.muted = true;
      video.autoplay = true;
      video.loop = true;

      video.play().catch(error => {
        console.error('Video autoplay failed:', error);
        // Try again after user interaction
        document.addEventListener('click', () => {
          video.play();
        }, { once: true });
      });
    }
  }, [navigate]);

  const handleLaunchClick = () => {
    navigate('/intro');
  };

  return (
    <div id="pre-intro-splash">
      {/* Background Video */}
      <video
        ref={videoRef}
        className="pre-intro-bg-video"
        autoPlay
        muted
        loop
        playsInline
      >
        <source src="/assets/video/intro-space-background.mp4" type="video/mp4" />
      </video>

      <div className="pre-intro-content">
        <img src="/assets/img/logo.png" alt="PASC Region J" className="pre-intro-logo" />
        <h1 className="pre-intro-title">PASC REGION <span className="special-j">J</span></h1>
        <p className="pre-intro-subtitle">Leadership Conference 2026</p>
        <p className="pre-intro-date">Reach for the Stars, Lead Beyond Limits - February 13, 2026</p>

        <button className="launch-button" onClick={handleLaunchClick}>
          <span className="rocket-icon">&#128640;</span>
          <span>LAUNCH SITE</span>
        </button>
      </div>
    </div>
  );
}

export default PreIntro;

// Front_End/angular-app/src/app/components/pre-intro/pre-intro.component.ts
import { Component, OnInit, AfterViewInit, ElementRef } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-pre-intro',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './pre-intro.component.html',
  styleUrl: './pre-intro.component.css'
})
export class PreIntroComponent implements OnInit, AfterViewInit {

  constructor(
    private router: Router,
    private elementRef: ElementRef
  ) {}

  ngOnInit(): void {
    // Check if user has already seen the intro sequence
    const introSeen = sessionStorage.getItem('introSeen');

    if (introSeen === 'true') {
      // Skip directly to home page
      this.router.navigate(['/home']);
    }
  }

  ngAfterViewInit(): void {
    // Force video to play with multiple attempts
    setTimeout(() => {
      const video = this.elementRef.nativeElement.querySelector('.pre-intro-bg-video') as HTMLVideoElement;
      
      if (video) {
        console.log('Found video element:', video);
        console.log('Video readyState:', video.readyState);
        console.log('Video paused:', video.paused);
        
        // Set all properties explicitly
        video.muted = true;
        video.autoplay = true;
        video.loop = true;
        
        // Try to play
        video.play()
          .then(() => {
            console.log('Video playing successfully!');
          })
          .catch(error => {
            console.error('Video autoplay failed:', error);
            
            // Try again after user interaction
            document.addEventListener('click', () => {
              video.play();
            }, { once: true });
          });
      } else {
        console.error('Video element not found!');
      }
    }, 100);
  }

  /**
   * Handle "Launch Site" button click
   */
  onLaunchClick(): void {
    // Navigate to intro page
    this.router.navigate(['/intro']);
  }
}
<div id="pre-intro-splash">
  <!-- Background Video -->
  <video class="pre-intro-bg-video" autoplay muted loop playsinline>
    <source src="/assets/video/intro-space-background.mp4" type="video/mp4">
  </video>

  <div class="pre-intro-content">
    <img src="/assets/img/logo.png" alt="PASC Region J" class="pre-intro-logo">
    <h1 class="pre-intro-title">PASC REGION <span class="special-j">J</span></h1>
    <p class="pre-intro-subtitle">Leadership Conference 2026</p>
    <p class="pre-intro-date">Reach for the Stars, Lead Beyond Limits · February 13, 2026</p>

    <button class="launch-button" (click)="onLaunchClick()">
      <span class="rocket-icon">🚀</span>
      <span>LAUNCH SITE</span>
    </button>
  </div>
</div>
