// react-app-source/src/pages/Workshops.js
import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { useAudio } from '../contexts/AudioContext';
import { getWorkshopForms, getPageContent } from '../services/api';
import Header from '../components/shared/Header';
import Footer from '../components/shared/Footer';

function Workshops() {
  const { isPlaying } = useAudio();
  const [forms, setForms] = useState([]);
  const [pageContent, setPageContent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [activeFormIndex, setActiveFormIndex] = useState(null);

  const heroVideoDesktopRef = useRef(null);
  const heroVideoMobileRef = useRef(null);

  useEffect(() => {
    loadPageContent();
    loadWorkshopForms();
  }, []);

  useEffect(() => {
    [heroVideoDesktopRef, heroVideoMobileRef].forEach(ref => {
      const video = ref.current;
      if (video) {
        video.muted = true;
        video.volume = 0;
        if (isPlaying) {
          video.play().catch(() => {});
        } else {
          video.pause();
        }
      }
    });
  }, [isPlaying]);

  const loadPageContent = async () => {
    try {
      const response = await getPageContent('workshops');
      if (response.success && response.data) {
        setPageContent(response.data);
      }
    } catch (err) {
      console.error('Error loading page content:', err);
    }
  };

  const loadWorkshopForms = async () => {
    try {
      setLoading(true);
      const response = await getWorkshopForms('Workshops');
      if (response.success && response.data) {
        setForms(response.data);
        // Auto-expand if only 1 form
        if (response.data.length === 1) {
          setActiveFormIndex(0);
        }
      } else {
        setError('Failed to load workshop forms');
      }
    } catch (err) {
      console.error('Error loading workshop forms:', err);
      setError('Failed to load workshop forms');
    } finally {
      setLoading(false);
    }
  };

  const toggleForm = (index) => {
    // Disable toggle if only one form
    if (forms.length === 1) {
      return;
    }
    setActiveFormIndex(activeFormIndex === index ? null : index);
  };

  return (
    <>
      <Header />

      {/* Hero Section */}
      <section className="page-hero">
        <video ref={heroVideoDesktopRef} id="workshopsVideo" className="hero-video hero-video-desktop" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>
        <video ref={heroVideoMobileRef} id="workshopsVideoMobile" className="hero-video hero-video-mobile" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>

        <div className="container">
          <h1 className="hero-title" id="workshopsTitle">Workshop Application</h1>
          <p className="hero-subtitle" id="workshopsSubtitle">Share Your Leadership Expertise</p>
        </div>
      </section>

      {/* Workshop Info & Application Form Section */}
      <section className="workshop-forms-section">
        <div className="container">
          <div className="intro-content">
            <h2>Present at Our Conference</h2>
            <p>We're looking for passionate leaders to share their knowledge and experience at the PASC Region J Conference 2026. Whether you're a student leader, advisor, or expert in student leadership, we want to hear from you!</p>
          </div>

          {loading && (
            <div className="loading-spinner">
              <div className="spinner"></div>
              <p>Loading workshop forms...</p>
            </div>
          )}

          {error && (
            <div className="alert alert-error">
              <p>{error}</p>
            </div>
          )}

          {!loading && !error && forms.length > 1 && (
            <div className="form-intro">
              <h2>Conference Forms</h2>
              <p className="form-description">Select a form below to begin your submission.</p>
            </div>
          )}

          {!loading && !error && forms.length > 0 && (
            <div className="accordion" id="workshopFormsAccordion">
              {forms.map((form, index) => (
                <div key={form.id} className="accordion-item">
                  <h2 className="accordion-header" id={`heading${form.id}`}>
                    <button
                      className={`accordion-button ${activeFormIndex !== index ? 'collapsed' : ''} ${forms.length === 1 ? 'single-form-locked' : ''}`}
                      type="button"
                      aria-expanded={activeFormIndex === index}
                      aria-controls={`collapse${form.id}`}
                      onClick={() => toggleForm(index)}
                    >
                      <div className="accordion-header-content">
                        <div className="form-title">{form.formname}</div>
                        {form.formdescription && form.formdescription.trim() && (
                          <div className="form-description-preview">{form.formdescription}</div>
                        )}
                      </div>
                    </button>
                  </h2>
                  <div
                    id={`collapse${form.id}`}
                    className={`accordion-collapse collapse ${activeFormIndex === index ? 'show' : ''}`}
                    aria-labelledby={`heading${form.id}`}
                  >
                    <div className="accordion-body">
                      <div
                        className="form-container"
                        dangerouslySetInnerHTML={{ __html: form.embedcode }}
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {!loading && !error && forms.length === 0 && (
            <div className="no-form-message">
              <div className="message-icon">&#128203;</div>
              <h2>Applications Opening Soon</h2>
              <p>Workshop presenter applications are not currently open. Please check back soon or contact us for more information.</p>
              <Link to="/home" className="btn btn-primary">Return Home</Link>
            </div>
          )}
        </div>
      </section>

      {/* Workshop Guidelines Section */}
      <section className="guidelines-section">
        <div className="container">
          <h2>Workshop Guidelines</h2>

          <div className="guidelines-grid">
            <div className="guideline-card">
              <h3>&#128218; Workshop Topics</h3>
              <p>Leadership skills, team building, communication, civic engagement, project planning, creativity, and student council best practices.</p>
            </div>

            <div className="guideline-card">
              <h3>&#9201;&#65039; Session Length</h3>
              <p>Workshops are 30 minutes. Plan your content to fit within this time frame for maximum engagement.</p>
            </div>

            <div className="guideline-card">
              <h3>&#128101; Target Audience</h3>
              <p>Workshops are designed for student council members. We encourage interactive and engaging sessions.</p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <div className="container">
          <h2>Questions About Presenting?</h2>
          <p>We're here to help! Reach out if you have any questions about the application process.</p>
          <div className="cta-buttons">
            <Link to="/about" className="btn btn-primary">Learn More About PASC Region J</Link>
            <Link to="/home" className="btn btn-secondary">Return Home</Link>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}

export default Workshops;

// angular-app-source/src/app/components/workshops/workshops.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, AfterViewInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { Subscription } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { AudioService } from '../../services/audio.service';
import { WorkshopForm, PageContent } from '../../models/api-models';

interface WorkshopFormWithSanitized extends WorkshopForm {
  sanitizedEmbedCode?: SafeHtml;
}

@Component({
  selector: 'app-workshops',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './workshops.component.html',
  styleUrl: './workshops.component.css'
})
export class WorkshopsComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('heroVideoDesktop', { static: false }) heroVideoDesktop!: ElementRef<HTMLVideoElement>;
  @ViewChild('heroVideoMobile', { static: false }) heroVideoMobile!: ElementRef<HTMLVideoElement>;

  private apiService = inject(ApiService);
  private audioService = inject(AudioService);
  private sanitizer = inject(DomSanitizer);

  forms = signal<WorkshopFormWithSanitized[]>([]);
  pageContent = signal<PageContent | null>(null);
  loading = signal(true);
  error = signal<string | null>(null);
  activeFormIndex = signal<number | null>(null);

  private subscriptions: Subscription[] = [];

  ngOnInit() {
    this.loadPageContent();
    this.loadWorkshopForms();
    this.setupAudioSubscription();
  }

  ngAfterViewInit(): void {
    // Explicitly ensure hero videos are muted
    if (this.heroVideoDesktop?.nativeElement) {
      this.heroVideoDesktop.nativeElement.muted = true;
      this.heroVideoDesktop.nativeElement.volume = 0;
    }
    if (this.heroVideoMobile?.nativeElement) {
      this.heroVideoMobile.nativeElement.muted = true;
      this.heroVideoMobile.nativeElement.volume = 0;
    }

    this.controlVideoPlayback(this.audioService.isPlaying());
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  private setupAudioSubscription(): void {
    const playingSub = this.audioService.isPlaying$.subscribe(playing => {
      this.controlVideoPlayback(playing);
    });
    this.subscriptions.push(playingSub);
  }

  private controlVideoPlayback(shouldPlay: boolean): void {
    [this.heroVideoDesktop, this.heroVideoMobile].forEach(videoRef => {
      if (videoRef && videoRef.nativeElement) {
        if (shouldPlay) {
          videoRef.nativeElement.play().catch(() => {});
        } else {
          videoRef.nativeElement.pause();
        }
      }
    });
  }

  private loadPageContent() {
    this.apiService.getPageContent('workshops').subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.pageContent.set(response.data);
        }
      },
      error: (err) => {
        console.error('Error loading page content:', err);
      }
    });
  }

  private loadWorkshopForms() {
    this.loading.set(true);
    this.apiService.getWorkshopForms('Workshops').subscribe({
      next: (response) => {
        if (response.success && response.data) {
          // Pre-sanitize all embed codes to prevent iframe reloading
          const formsWithSanitized = response.data.map(form => ({
            ...form,
            sanitizedEmbedCode: this.sanitizer.bypassSecurityTrustHtml(form.embedcode)
          }));

          this.forms.set(formsWithSanitized);

          // Smart accordion behavior: auto-expand if only 1 form
          if (formsWithSanitized.length === 1) {
            this.activeFormIndex.set(0);
          }
        } else {
          this.error.set('Failed to load workshop forms');
        }
        this.loading.set(false);
      },
      error: (err) => {
        console.error('Error loading workshop forms:', err);
        this.error.set('Failed to load workshop forms');
        this.loading.set(false);
      }
    });
  }

  toggleForm(index: number) {
    // Disable toggle if only one form (keep it always open)
    if (this.forms().length === 1) {
      return;
    }

    this.activeFormIndex.set(this.activeFormIndex() === index ? null : index);
  }
}

<!-- Hero Section -->
<section class="page-hero">
    <!-- Video Background - Desktop -->
    <video #heroVideoDesktop id="workshopsVideo" class="hero-video hero-video-desktop" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <!-- Video Background - Mobile -->
    <video #heroVideoMobile id="workshopsVideoMobile" class="hero-video hero-video-mobile" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <div class="container">
        <h1 class="hero-title" id="workshopsTitle">Workshop Application</h1>
        <p class="hero-subtitle" id="workshopsSubtitle">Share Your Leadership Expertise</p>
    </div>
</section>

<!-- Workshop Info & Application Form Section - Merged -->
<section class="workshop-forms-section">
    <div class="container">
        <!-- Workshop Info -->
        <div class="intro-content">
            <h2>Present at Our Conference</h2>
            <p>We're looking for passionate leaders to share their knowledge and experience at the PASC Region J Conference 2026. Whether you're a student leader, advisor, or expert in student leadership, we want to hear from you!</p>
        </div>

        @if (loading()) {
            <div class="loading-spinner">
                <div class="spinner"></div>
                <p>Loading workshop forms...</p>
            </div>
        }

        @if (error()) {
            <div class="alert alert-error">
                <p>{{ error() }}</p>
            </div>
        }

        @if (!loading() && !error() && forms().length > 0) {
            <div class="form-intro">
                <h2>Conference Forms</h2>
                <p class="form-description">Select a form below to begin your submission.</p>
            </div>

            <!-- Bootstrap Accordion for Multiple Forms -->
            <div class="accordion" id="workshopFormsAccordion">
                @for (form of forms(); track form.id; let i = $index) {
                    <div class="accordion-item">
                        <h2 class="accordion-header" [id]="'heading' + form.id">
                            <button
                                class="accordion-button"
                                [class.collapsed]="activeFormIndex() !== i"
                                [class.single-form-locked]="forms().length === 1"
                                type="button"
                                [attr.data-target]="'#collapse' + form.id"
                                [attr.aria-expanded]="activeFormIndex() === i"
                                [attr.aria-controls]="'collapse' + form.id"
                                (click)="toggleForm(i)">
                                <div class="accordion-header-content">
                                    <div class="form-title">{{ form.formname }}</div>
                                    @if (form.formdescription && form.formdescription.trim()) {
                                        <div class="form-description-preview">{{ form.formdescription }}</div>
                                    }
                                </div>
                            </button>
                        </h2>
                        <div
                            [id]="'collapse' + form.id"
                            class="accordion-collapse collapse"
                            [class.show]="activeFormIndex() === i"
                            [attr.aria-labelledby]="'heading' + form.id"
                            data-bs-parent="#workshopFormsAccordion">
                            <div class="accordion-body">
                                <div class="form-container" [innerHTML]="form.sanitizedEmbedCode"></div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }

        @if (!loading() && !error() && forms().length === 0) {
            <!-- Fallback if no form is active -->
            <div class="no-form-message">
                <div class="message-icon">📋</div>
                <h2>Applications Opening Soon</h2>
                <p>Workshop presenter applications are not currently open. Please check back soon or contact us for more information.</p>
                <a routerLink="/home" class="btn btn-primary">Return Home</a>
            </div>
        }
    </div>
</section>

<!-- Workshop Guidelines Section -->
<section class="guidelines-section">
    <div class="container">
        <h2>Workshop Guidelines</h2>

        <div class="guidelines-grid">
            <div class="guideline-card">
                <h3>📚 Workshop Topics</h3>
                <p>Leadership skills, team building, communication, civic engagement, project planning, creativity, and student council best practices.</p>
            </div>

            <div class="guideline-card">
                <h3>⏱️ Session Length</h3>
                <p>Workshops are 30 minutes. Plan your content to fit within this time frame for maximum engagement.</p>
            </div>

            <div class="guideline-card">
                <h3>👥 Target Audience</h3>
                <p>Workshops are designed for student council members. We encourage interactive and engaging sessions.</p>
            </div>
        </div>
    </div>
</section>

<!-- CTA Section -->
<section class="cta-section">
    <div class="container">
        <h2>Questions About Presenting?</h2>
        <p>We're here to help! Reach out if you have any questions about the application process.</p>
        <div class="cta-buttons">
            <a routerLink="/about" class="btn btn-primary">Learn More About PASC Region J</a>
            <a routerLink="/home" class="btn btn-secondary">Return Home</a>
        </div>
    </div>
</section>
