// angular-app-source/src/app/admin/layout/admin-sidebar/admin-sidebar.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService, AdminUser } from '../../services/auth.service';

@Component({
  selector: 'app-admin-sidebar',
  standalone: false,
  templateUrl: './admin-sidebar.component.html',
  styleUrls: ['./admin-sidebar.component.css']
})
export class AdminSidebarComponent implements OnInit {
  @Input() isMobileOpen = false;
  currentUser: AdminUser | null = null;
  imageLoadError = false;
  profilePictureUrl = ''; // Cache the profile picture URL to prevent infinite loading

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    // Subscribe to current user
    this.authService.currentUser$.subscribe(user => {
      this.currentUser = user;
      this.imageLoadError = false; // Reset error flag when user changes
      // Update profile picture URL when user changes (prevents infinite loading)
      this.updateProfilePictureUrl();
    });
  }

  logout(): void {
    this.authService.logout().subscribe();
  }

  /**
   * Update profile picture URL - called only when user changes
   * This prevents infinite loading by not generating new URLs on every change detection cycle
   */
  updateProfilePictureUrl(): void {
    if (this.imageLoadError || !this.currentUser?.profile_picture) {
      this.profilePictureUrl = '';
    } else {
      // Add timestamp only once when user changes, not on every template check
      this.profilePictureUrl = `/assets/img/profiles/${this.currentUser.profile_picture}?v=${Date.now()}`;
    }
  }

  getProfilePictureUrl(): string {
    return this.profilePictureUrl;
  }

  onImageError(): void {
    this.imageLoadError = true;
    this.profilePictureUrl = ''; // Clear URL on error
  }

  /**
   * Check if current user is Admin (role_id = 1)
   * Only Admins should see User Management
   */
  isAdmin(): boolean {
    return this.currentUser?.role_id === 1;
  }
}

<aside class="admin-sidebar" [class.mobile-open]="isMobileOpen">
  <!-- Logo Header -->
  <div class="sidebar-header">
    <img src="/assets/img/logo.png" alt="PASC Region J" class="sidebar-logo">
    <h2>Admin Panel</h2>
  </div>

  <!-- Navigation Menu -->
  <nav class="sidebar-nav">
    <a routerLink="/admin/dashboard" routerLinkActive="active" class="nav-item">
      <span class="nav-icon">📊</span>
      <span class="nav-text">Dashboard</span>
    </a>

    <a routerLink="/admin/announcements" routerLinkActive="active" class="nav-item">
      <span class="nav-icon">📢</span>
      <span class="nav-text">Announcements</span>
    </a>

    <a routerLink="/admin/forms" routerLinkActive="active" class="nav-item">
      <span class="nav-icon">📝</span>
      <span class="nav-text">Forms</span>
    </a>

    <a routerLink="/admin/gallery" routerLinkActive="active" class="nav-item">
      <span class="nav-icon">📷</span>
      <span class="nav-text">Gallery</span>
    </a>

    <a routerLink="/admin/documents" routerLinkActive="active" class="nav-item">
      <span class="nav-icon">📁</span>
      <span class="nav-text">Documents</span>
    </a>

    <a routerLink="/admin/contacts" routerLinkActive="active" class="nav-item">
      <span class="nav-icon">📧</span>
      <span class="nav-text">Contact Submissions</span>
      <!-- TODO: Add badge for new contacts in Phase 2 -->
    </a>

    <!-- User Management (Admin Only - role_id = 1) -->
    <ng-container *ngIf="isAdmin()">
      <!-- Divider -->
      <div class="nav-divider"></div>

      <a routerLink="/admin/users" routerLinkActive="active" class="nav-item">
        <span class="nav-icon">👥</span>
        <span class="nav-text">User Management</span>
      </a>

      <!-- Divider -->
      <div class="nav-divider"></div>
    </ng-container>

    <!-- External Links -->
    <a href="/" target="_blank" class="nav-item">
      <span class="nav-icon">🌐</span>
      <span class="nav-text">View Website</span>
    </a>

    <a href="https://analytics.google.com" target="_blank" class="nav-item">
      <span class="nav-icon">📈</span>
      <span class="nav-text">Analytics</span>
    </a>

    <a (click)="logout()" class="nav-item nav-logout">
      <span class="nav-icon">🚪</span>
      <span class="nav-text">Logout</span>
    </a>
  </nav>

  <!-- Sidebar Footer (User Info) -->
  <div class="sidebar-footer">
    <div class="user-info">
      <!-- Profile Picture or Placeholder (40px for sidebar) -->
      <img *ngIf="getProfilePictureUrl()"
           [src]="getProfilePictureUrl()"
           alt="Profile"
           (error)="onImageError()"
           style="width: 40px; height: 40px; border-radius: 50%; object-fit: cover; margin: 0 auto 10px auto; display: block; border: 2px solid #4fc3f7;">
      <div *ngIf="!getProfilePictureUrl()" class="profile-placeholder" style="width: 40px; height: 40px; font-size: 20px; margin: 0 auto 10px auto;">
        👤
      </div>
      <strong>{{ currentUser?.full_name || 'Admin User' }}</strong><br>
      <small style="color: #b0b8d4;">{{ currentUser?.role_name || 'Administrator' }}</small>
    </div>

    <!-- My Profile Link -->
    <div style="margin-top: 15px;">
      <a routerLink="/admin/profile" class="nav-item" style="padding: 8px 15px;">
        <span class="nav-icon">⚙️</span>
        <span class="nav-text">My Profile</span>
      </a>
    </div>
  </div>
</aside>

// react-app-source/src/components/admin/AdminSidebar.js
import React, { useState, useEffect } from 'react';
import { NavLink } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';

function AdminSidebar({ isMobileOpen }) {
  const { user, logout } = useAuth();
  const [imageLoadError, setImageLoadError] = useState(false);
  const [profilePictureUrl, setProfilePictureUrl] = useState('');

  useEffect(() => {
    setImageLoadError(false);
    updateProfilePictureUrl();
  }, [user]);

  const updateProfilePictureUrl = () => {
    if (imageLoadError || !user?.profile_picture) {
      setProfilePictureUrl('');
    } else {
      setProfilePictureUrl(`/assets/img/profiles/${user.profile_picture}?v=${Date.now()}`);
    }
  };

  const onImageError = () => {
    setImageLoadError(true);
    setProfilePictureUrl('');
  };

  const handleLogout = () => {
    logout();
  };

  const isAdmin = () => {
    return user?.role_id === 1;
  };

  return (
    <aside className={`admin-sidebar ${isMobileOpen ? 'mobile-open' : ''}`}>
      {/* Logo Header */}
      <div className="sidebar-header">
        <img src="/assets/img/logo.png" alt="PASC Region J" className="sidebar-logo" />
        <h2>Admin Panel</h2>
      </div>

      {/* Navigation Menu */}
      <nav className="sidebar-nav">
        <NavLink to="/admin/dashboard" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
          <span className="nav-icon">📊</span>
          <span className="nav-text">Dashboard</span>
        </NavLink>

        <NavLink to="/admin/announcements" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
          <span className="nav-icon">📢</span>
          <span className="nav-text">Announcements</span>
        </NavLink>

        <NavLink to="/admin/forms" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
          <span className="nav-icon">📝</span>
          <span className="nav-text">Forms</span>
        </NavLink>

        <NavLink to="/admin/gallery" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
          <span className="nav-icon">📷</span>
          <span className="nav-text">Gallery</span>
        </NavLink>

        <NavLink to="/admin/documents" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
          <span className="nav-icon">📁</span>
          <span className="nav-text">Documents</span>
        </NavLink>

        <NavLink to="/admin/schedule" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
          <span className="nav-icon">📅</span>
          <span className="nav-text">Schedule</span>
        </NavLink>

        <NavLink to="/admin/contacts" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
          <span className="nav-icon">📧</span>
          <span className="nav-text">Contact Submissions</span>
        </NavLink>

        {/* User Management (Admin Only - role_id = 1) */}
        {isAdmin() && (
          <>
            <div className="nav-divider"></div>

            <NavLink to="/admin/users" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}>
              <span className="nav-icon">👥</span>
              <span className="nav-text">User Management</span>
            </NavLink>

            <div className="nav-divider"></div>
          </>
        )}

        {/* External Links */}
        <a href="/" target="_blank" rel="noopener noreferrer" className="nav-item">
          <span className="nav-icon">🌐</span>
          <span className="nav-text">View Website</span>
        </a>

        <a href="https://analytics.google.com" target="_blank" rel="noopener noreferrer" className="nav-item">
          <span className="nav-icon">📈</span>
          <span className="nav-text">Analytics</span>
        </a>

        <button onClick={handleLogout} className="nav-item nav-logout">
          <span className="nav-icon">🚪</span>
          <span className="nav-text">Logout</span>
        </button>
      </nav>

      {/* Sidebar Footer (User Info) */}
      <div className="sidebar-footer">
        <div className="user-info">
          {/* Profile Picture or Placeholder (40px for sidebar) */}
          {profilePictureUrl ? (
            <img
              src={profilePictureUrl}
              alt="Profile"
              onError={onImageError}
              style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                objectFit: 'cover',
                margin: '0 auto 10px auto',
                display: 'block',
                border: '2px solid #4fc3f7'
              }}
            />
          ) : (
            <div
              className="profile-placeholder"
              style={{
                width: '40px',
                height: '40px',
                fontSize: '20px',
                margin: '0 auto 10px auto'
              }}
            >
              👤
            </div>
          )}
          <strong>{user?.full_name || 'Admin User'}</strong><br />
          <small style={{ color: '#b0b8d4' }}>{user?.role_name || 'Administrator'}</small>
        </div>

        {/* My Profile Link */}
        <div style={{ marginTop: '15px' }}>
          <NavLink to="/admin/profile" className="nav-item" style={{ padding: '8px 15px' }}>
            <span className="nav-icon">⚙️</span>
            <span className="nav-text">My Profile</span>
          </NavLink>
        </div>
      </div>
    </aside>
  );
}

export default AdminSidebar;
