// angular-app-source/src/app/admin/layout/admin-layout/admin-layout.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-admin-layout',
  standalone: false,
  templateUrl: './admin-layout.component.html',
  styleUrls: ['./admin-layout.component.css']
})
export class AdminLayoutComponent {
  isMobileMenuOpen = false;

  toggleMobileMenu(): void {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;

    // Prevent body scroll when menu is open
    if (this.isMobileMenuOpen) {
      document.body.classList.add('mobile-menu-open');
    } else {
      document.body.classList.remove('mobile-menu-open');
    }
  }

  closeMobileMenu(): void {
    this.isMobileMenuOpen = false;
    document.body.classList.remove('mobile-menu-open');
  }
}

<div class="admin-wrapper">
  <!-- Sidebar Navigation -->
  <app-admin-sidebar [isMobileOpen]="isMobileMenuOpen"></app-admin-sidebar>

  <!-- Mobile Overlay (for closing sidebar when clicking outside) -->
  <div class="mobile-overlay" [class.active]="isMobileMenuOpen" (click)="closeMobileMenu()"></div>

  <!-- Main Content Area -->
  <main class="admin-content">
    <!-- Fixed Header Bar -->
    <app-admin-header (toggleMobileMenu)="toggleMobileMenu()"></app-admin-header>

    <!-- Router outlet for admin pages -->
    <router-outlet></router-outlet>
  </main>
</div>

// react-app-source/src/components/admin/AdminLayout.js
import React, { useState } from 'react';
import { Outlet } from 'react-router-dom';
import AdminSidebar from './AdminSidebar';
import AdminHeader from './AdminHeader';

function AdminLayout() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(prev => {
      const newState = !prev;
      // Prevent body scroll when menu is open
      if (newState) {
        document.body.classList.add('mobile-menu-open');
      } else {
        document.body.classList.remove('mobile-menu-open');
      }
      return newState;
    });
  };

  const closeMobileMenu = () => {
    setIsMobileMenuOpen(false);
    document.body.classList.remove('mobile-menu-open');
  };

  return (
    <div className="admin-wrapper">
      {/* Sidebar Navigation */}
      <AdminSidebar isMobileOpen={isMobileMenuOpen} />

      {/* Mobile Overlay (for closing sidebar when clicking outside) */}
      <div
        className={`mobile-overlay ${isMobileMenuOpen ? 'active' : ''}`}
        onClick={closeMobileMenu}
      ></div>

      {/* Main Content Area */}
      <main className="admin-content">
        {/* Fixed Header Bar */}
        <AdminHeader onToggleMobileMenu={toggleMobileMenu} />

        {/* Router outlet for admin pages */}
        <Outlet />
      </main>
    </div>
  );
}

export default AdminLayout;
