// angular-app-source/src/app/admin/auth/activate/activate.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-activate',
  standalone: false,
  templateUrl: './activate.component.html',
  styleUrls: ['./activate.component.css']
})
export class ActivateComponent implements OnInit {
  activateForm: FormGroup;
  loading = false;
  errorMessage = '';
  successMessage = '';
  token: string | null = null;
  showPassword = false;
  showConfirmPassword = false;

  // Password strength indicator
  passwordStrength = 0;
  strengthLabel = '';
  strengthColor = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.activateForm = this.fb.group({
      newPassword: ['', [Validators.required, Validators.minLength(8)]],
      confirmPassword: ['', [Validators.required]]
    });

    // Subscribe to password changes for strength indicator
    this.activateForm.get('newPassword')?.valueChanges.subscribe(value => {
      this.calculatePasswordStrength(value);
    });
  }

  ngOnInit(): void {
    // Get token from query parameters
    this.route.queryParams.subscribe(params => {
      this.token = params['token'] || null;
      if (!this.token) {
        this.errorMessage = 'Invalid activation link. Please contact the administrator.';
      }
    });
  }

  calculatePasswordStrength(password: string): void {
    if (!password) {
      this.passwordStrength = 0;
      this.strengthLabel = '';
      this.strengthColor = '';
      return;
    }

    let strength = 0;

    // Length checks
    if (password.length >= 8) strength += 20;
    if (password.length >= 12) strength += 10;
    if (password.length >= 16) strength += 10;

    // Character type checks
    if (/[a-z]/.test(password)) strength += 10;
    if (/[A-Z]/.test(password)) strength += 15;
    if (/[0-9]/.test(password)) strength += 15;
    if (/[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(password)) strength += 20;

    // Bonus for variety
    const types = [/[a-z]/, /[A-Z]/, /[0-9]/, /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/];
    const typeCount = types.filter(regex => regex.test(password)).length;
    if (typeCount >= 4) strength += 10;

    // Cap at 100
    this.passwordStrength = Math.min(strength, 100);

    // Set label and color based on strength
    if (this.passwordStrength < 20) {
      this.strengthLabel = 'Weak';
      this.strengthColor = '#dc3545'; // Red
    } else if (this.passwordStrength < 40) {
      this.strengthLabel = 'Fair';
      this.strengthColor = '#fd7e14'; // Orange
    } else if (this.passwordStrength < 60) {
      this.strengthLabel = 'Medium';
      this.strengthColor = '#ffc107'; // Yellow
    } else if (this.passwordStrength < 80) {
      this.strengthLabel = 'Good';
      this.strengthColor = '#90EE90'; // Light Green
    } else {
      this.strengthLabel = 'Strong';
      this.strengthColor = '#28a745'; // Dark Green
    }
  }

  onSubmit(): void {
    if (this.activateForm.invalid || !this.token) {
      this.errorMessage = 'Please fill in all required fields.';
      return;
    }

    const { newPassword, confirmPassword } = this.activateForm.value;

    // Check passwords match
    if (newPassword !== confirmPassword) {
      this.errorMessage = 'Passwords do not match.';
      return;
    }

    // Validate password requirements
    if (newPassword.length < 8) {
      this.errorMessage = 'Password must be at least 8 characters.';
      return;
    }

    if (!/[A-Z]/.test(newPassword)) {
      this.errorMessage = 'Password must contain at least one uppercase letter.';
      return;
    }

    if (!/[0-9]/.test(newPassword)) {
      this.errorMessage = 'Password must contain at least one number.';
      return;
    }

    if (!/[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(newPassword)) {
      this.errorMessage = 'Password must contain at least one special character.';
      return;
    }

    this.loading = true;
    this.errorMessage = '';

    this.authService.activateAccount(this.token, newPassword).subscribe({
      next: (response) => {
        if (response.success) {
          // Backend now auto-logs user in after successful activation
          // Update the current user in AuthService so the app knows user is logged in
          if (response.user) {
            // The authService will update currentUserSubject through the API response
            // Just need to trigger a re-check to get the session
            this.authService.checkAuthStatus().subscribe();
          }

          this.successMessage = 'Account activated successfully! You are now logged in. Redirecting to dashboard...';
          setTimeout(() => {
            // Redirect to dashboard since user is now logged in
            this.router.navigate(['/admin/dashboard']);
          }, 2000);
        } else {
          this.errorMessage = response.message || 'Failed to activate account.';
          this.loading = false;
        }
      },
      error: (error) => {
        this.errorMessage = error.message || 'Failed to activate account. Please try again or contact the administrator.';
        this.loading = false;
      }
    });
  }

  togglePasswordVisibility(field: string): void {
    if (field === 'password') {
      this.showPassword = !this.showPassword;
    } else if (field === 'confirmPassword') {
      this.showConfirmPassword = !this.showConfirmPassword;
    }
  }

  get newPasswordControl() {
    return this.activateForm.get('newPassword');
  }

  get confirmPasswordControl() {
    return this.activateForm.get('confirmPassword');
  }
}

<div class="login-container">
  <div class="login-box">
    <div class="login-header">
      <div class="logo">
        <img src="/assets/img/logo.png" alt="PASC Region J" class="logo-img">
      </div>
      <h1>Activate Your Account</h1>
      <p>PASC Region J Conference 2026</p>
    </div>

    <!-- Success Message -->
    <div *ngIf="successMessage" class="alert alert-success">
      {{ successMessage }}
    </div>

    <!-- Error Message -->
    <div *ngIf="errorMessage" class="alert alert-error">
      {{ errorMessage }}
    </div>

    <!-- Activation Form -->
    <form *ngIf="!successMessage && token" [formGroup]="activateForm" (ngSubmit)="onSubmit()" class="login-form">
      <p class="form-instructions">
        Welcome! Please set your password to activate your account.
      </p>

      <div class="form-group">
        <label for="newPassword">New Password</label>
        <div class="password-input-wrapper">
          <input
            [type]="showPassword ? 'text' : 'password'"
            id="newPassword"
            formControlName="newPassword"
            class="form-control"
            placeholder="Enter your password"
            autocomplete="new-password"
            autofocus
            [class.error]="newPasswordControl?.invalid && newPasswordControl?.touched">
          <button
            type="button"
            class="password-toggle"
            (click)="togglePasswordVisibility('password')"
            aria-label="Toggle password visibility">
            <span class="toggle-icon">{{ showPassword ? '🙈' : '👁️' }}</span>
          </button>
        </div>
        <!-- Password Strength Indicator -->
        <div *ngIf="passwordStrength > 0" class="password-strength">
          <div class="strength-bar-container">
            <div class="strength-bar" [style.width.%]="passwordStrength" [style.background]="strengthColor"></div>
          </div>
          <span class="strength-label" [style.color]="strengthColor">{{ strengthLabel }}</span>
        </div>
      </div>

      <div class="form-group">
        <label for="confirmPassword">Confirm Password</label>
        <div class="password-input-wrapper">
          <input
            [type]="showConfirmPassword ? 'text' : 'password'"
            id="confirmPassword"
            formControlName="confirmPassword"
            class="form-control"
            placeholder="Confirm your password"
            autocomplete="new-password"
            [class.error]="confirmPasswordControl?.invalid && confirmPasswordControl?.touched">
          <button
            type="button"
            class="password-toggle"
            (click)="togglePasswordVisibility('confirmPassword')"
            aria-label="Toggle password visibility">
            <span class="toggle-icon">{{ showConfirmPassword ? '🙈' : '👁️' }}</span>
          </button>
        </div>
      </div>

      <!-- Password Requirements Info -->
      <div class="password-requirements">
        <strong class="requirements-title">Password Requirements:</strong>
        <ul class="requirements-list">
          <li>Minimum 8 characters</li>
          <li>At least one uppercase letter (A-Z)</li>
          <li>At least one number (0-9)</li>
          <li>At least one special character (e.g., !@#$%^&*)</li>
        </ul>
      </div>

      <button
        type="submit"
        class="btn btn-login"
        [disabled]="loading || activateForm.invalid">
        <span *ngIf="!loading">Activate Account</span>
        <span *ngIf="loading">Activating...</span>
      </button>
    </form>

    <!-- Back to Login Link -->
    <div class="login-footer">
      <a [routerLink]="['/admin/login']" [queryParams]="{from: 'activate'}" class="back-link">← Back to Login</a>
    </div>
  </div>
</div>

// react-app-source/src/pages/admin/Activate.js
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';

function Activate() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { activateAccount, checkAuthStatus } = useAuth();

  const [formData, setFormData] = useState({
    newPassword: '',
    confirmPassword: ''
  });
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');
  const [token, setToken] = useState(null);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  // Password strength indicator
  const [passwordStrength, setPasswordStrength] = useState(0);
  const [strengthLabel, setStrengthLabel] = useState('');
  const [strengthColor, setStrengthColor] = useState('');

  useEffect(() => {
    const tokenParam = searchParams.get('token');
    setToken(tokenParam);
    if (!tokenParam) {
      setErrorMessage('Invalid activation link. Please contact the administrator.');
    }
  }, [searchParams]);

  useEffect(() => {
    calculatePasswordStrength(formData.newPassword);
  }, [formData.newPassword]);

  const calculatePasswordStrength = (password) => {
    if (!password) {
      setPasswordStrength(0);
      setStrengthLabel('');
      setStrengthColor('');
      return;
    }

    let strength = 0;

    // Length checks
    if (password.length >= 8) strength += 20;
    if (password.length >= 12) strength += 10;
    if (password.length >= 16) strength += 10;

    // Character type checks
    if (/[a-z]/.test(password)) strength += 10;
    if (/[A-Z]/.test(password)) strength += 15;
    if (/[0-9]/.test(password)) strength += 15;
    if (/[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/.test(password)) strength += 20;

    // Bonus for variety
    const types = [/[a-z]/, /[A-Z]/, /[0-9]/, /[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/];
    const typeCount = types.filter(regex => regex.test(password)).length;
    if (typeCount >= 4) strength += 10;

    // Cap at 100
    const finalStrength = Math.min(strength, 100);
    setPasswordStrength(finalStrength);

    // Set label and color based on strength
    if (finalStrength < 20) {
      setStrengthLabel('Weak');
      setStrengthColor('#dc3545');
    } else if (finalStrength < 40) {
      setStrengthLabel('Fair');
      setStrengthColor('#fd7e14');
    } else if (finalStrength < 60) {
      setStrengthLabel('Medium');
      setStrengthColor('#ffc107');
    } else if (finalStrength < 80) {
      setStrengthLabel('Good');
      setStrengthColor('#90EE90');
    } else {
      setStrengthLabel('Strong');
      setStrengthColor('#28a745');
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.newPassword || !formData.confirmPassword || !token) {
      setErrorMessage('Please fill in all required fields.');
      return;
    }

    const { newPassword, confirmPassword } = formData;

    // Check passwords match
    if (newPassword !== confirmPassword) {
      setErrorMessage('Passwords do not match.');
      return;
    }

    // Validate password requirements
    if (newPassword.length < 8) {
      setErrorMessage('Password must be at least 8 characters.');
      return;
    }

    if (!/[A-Z]/.test(newPassword)) {
      setErrorMessage('Password must contain at least one uppercase letter.');
      return;
    }

    if (!/[0-9]/.test(newPassword)) {
      setErrorMessage('Password must contain at least one number.');
      return;
    }

    if (!/[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/.test(newPassword)) {
      setErrorMessage('Password must contain at least one special character.');
      return;
    }

    setLoading(true);
    setErrorMessage('');

    try {
      const response = await activateAccount(token, newPassword);

      if (response.success) {
        // Backend now auto-logs user in after successful activation
        if (response.user) {
          // Trigger a re-check to get the session
          checkAuthStatus();
        }

        setSuccessMessage('Account activated successfully! You are now logged in. Redirecting to dashboard...');
        setTimeout(() => {
          navigate('/admin/dashboard');
        }, 2000);
      } else {
        setErrorMessage(response.message || 'Failed to activate account.');
        setLoading(false);
      }
    } catch (error) {
      setErrorMessage(error.message || 'Failed to activate account. Please try again or contact the administrator.');
      setLoading(false);
    }
  };

  const togglePasswordVisibility = (field) => {
    if (field === 'password') {
      setShowPassword(prev => !prev);
    } else if (field === 'confirmPassword') {
      setShowConfirmPassword(prev => !prev);
    }
  };

  return (
    <div className="admin-login-page">
      <div className="login-container">
        <div className="login-box">
        <div className="login-header">
          <div className="logo">
            <img src="/assets/img/logo.png" alt="PASC Region J" className="logo-img" />
          </div>
          <h1>Activate Your Account</h1>
          <p>PASC Region J Conference 2026</p>
        </div>

        {/* Success Message */}
        {successMessage && (
          <div className="alert alert-success">
            {successMessage}
          </div>
        )}

        {/* Error Message */}
        {errorMessage && (
          <div className="alert alert-error">
            {errorMessage}
          </div>
        )}

        {/* Activation Form */}
        {!successMessage && token && (
          <form onSubmit={handleSubmit} className="login-form">
            <p className="form-instructions">
              Welcome! Please set your password to activate your account.
            </p>

            <div className="form-group">
              <label htmlFor="newPassword">New Password</label>
              <div className="password-input-wrapper">
                <input
                  type={showPassword ? 'text' : 'password'}
                  id="newPassword"
                  name="newPassword"
                  value={formData.newPassword}
                  onChange={handleInputChange}
                  className="form-control"
                  placeholder="Enter your password"
                  autoComplete="new-password"
                  autoFocus
                />
                <button
                  type="button"
                  className="password-toggle"
                  onClick={() => togglePasswordVisibility('password')}
                  aria-label="Toggle password visibility"
                >
                  <span className="toggle-icon">{showPassword ? '🙈' : '👁️'}</span>
                </button>
              </div>
              {/* Password Strength Indicator */}
              {passwordStrength > 0 && (
                <div className="password-strength">
                  <div className="strength-bar-container">
                    <div
                      className="strength-bar"
                      style={{ width: `${passwordStrength}%`, background: strengthColor }}
                    ></div>
                  </div>
                  <span className="strength-label" style={{ color: strengthColor }}>{strengthLabel}</span>
                </div>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="confirmPassword">Confirm Password</label>
              <div className="password-input-wrapper">
                <input
                  type={showConfirmPassword ? 'text' : 'password'}
                  id="confirmPassword"
                  name="confirmPassword"
                  value={formData.confirmPassword}
                  onChange={handleInputChange}
                  className="form-control"
                  placeholder="Confirm your password"
                  autoComplete="new-password"
                />
                <button
                  type="button"
                  className="password-toggle"
                  onClick={() => togglePasswordVisibility('confirmPassword')}
                  aria-label="Toggle password visibility"
                >
                  <span className="toggle-icon">{showConfirmPassword ? '🙈' : '👁️'}</span>
                </button>
              </div>
            </div>

            {/* Password Requirements Info */}
            <div className="password-requirements">
              <strong className="requirements-title">Password Requirements:</strong>
              <ul className="requirements-list">
                <li>Minimum 8 characters</li>
                <li>At least one uppercase letter (A-Z)</li>
                <li>At least one number (0-9)</li>
                <li>At least one special character (e.g., !@#$%^&*)</li>
              </ul>
            </div>

            <button
              type="submit"
              className="btn btn-login"
              disabled={loading || !formData.newPassword || !formData.confirmPassword}
            >
              {loading ? 'Activating...' : 'Activate Account'}
            </button>
          </form>
        )}

        {/* Back to Login Link */}
        <div className="login-footer">
          <Link to="/admin/login?from=activate" className="back-link">← Back to Login</Link>
        </div>
        </div>
      </div>
    </div>
  );
}

export default Activate;
