// Front_End/angular-app-source/src/app/admin/documents/document-edit/document-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DocumentsService } from '../../services/documents.service';
import { Document } from '../../models/document.model';

@Component({
  selector: 'app-document-edit',
  standalone: false,
  templateUrl: './document-edit.component.html',
  styleUrls: ['./document-edit.component.css']
})
export class DocumentEditComponent implements OnInit {
  documentId: number | null = null;
  loading = false;
  error: string | null = null;
  document: Document | null = null;

  formData = {
    title: '',
    description: '',
    document_type: '',
    is_active: false
  };

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private documentsService: DocumentsService
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.documentId = +params['id'];
        this.loadDocument();
      }
    });
  }

  loadDocument(): void {
    if (!this.documentId) return;

    this.loading = true;
    this.error = null;

    this.documentsService.getById(this.documentId).subscribe({
      next: (data) => {
        this.document = data;
        this.formData = {
          title: data.title,
          description: data.description || '',
          document_type: data.document_type || '',
          is_active: data.is_active
        };
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load document';
        this.loading = false;
        console.error('Error loading document:', err);
      }
    });
  }

  onSubmit(): void {
    if (!this.formData.title.trim()) {
      this.error = 'Document Title is required';
      return;
    }

    this.loading = true;
    this.error = null;

    if (this.documentId) {
      this.documentsService.update(this.documentId, this.formData).subscribe({
        next: () => {
          this.router.navigate(['/admin/documents']);
        },
        error: (err) => {
          this.error = err.message || 'Failed to update document';
          this.loading = false;
          console.error('Error updating document:', err);
        }
      });
    }
  }

  cancel(): void {
    this.router.navigate(['/admin/documents']);
  }

  getDocumentIcon(extension: string): string {
    const ext = extension.toLowerCase().replace('.', '');
    switch(ext) {
      case 'pdf': return '📄';
      case 'doc':
      case 'docx': return '📝';
      case 'xls':
      case 'xlsx': return '📊';
      case 'ppt':
      case 'pptx': return '📽️';
      default: return '📁';
    }
  }

  getDocIconClass(extension: string): string {
    const ext = extension.toLowerCase().replace('.', '');
    return `doc-icon ${ext}`;
  }

  formatFileSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' B';
    const kb = bytes / 1024;
    if (kb < 1024) return kb.toFixed(1) + ' KB';
    const mb = kb / 1024;
    return mb.toFixed(2) + ' MB';
  }
}

// react-app-source/src/pages/admin/DocumentEdit.js
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { documentsService } from '../../services/admin-api';

function DocumentEdit() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [document, setDocument] = useState(null);

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    document_type: '',
    is_active: true
  });

  useEffect(() => {
    loadDocument();
  }, [id]);

  const loadDocument = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await documentsService.getById(id);
      const data = response.data;
      setDocument(data);
      setFormData({
        title: data.title || '',
        description: data.description || '',
        document_type: data.document_type || '',
        is_active: data.is_active || false
      });
      setLoading(false);
    } catch (err) {
      setError('Failed to load document');
      setLoading(false);
      console.error('Error loading document:', err);
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.title.trim()) {
      setError('Document Title is required');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      await documentsService.update(id, formData);
      navigate('/admin/documents');
    } catch (err) {
      setError(err.message || 'Failed to update document');
      setLoading(false);
      console.error('Error updating document:', err);
    }
  };

  const cancel = () => {
    navigate('/admin/documents');
  };

  const getDocumentIcon = (extension) => {
    if (!extension) return '📁';
    const ext = extension.toLowerCase().replace('.', '');
    switch (ext) {
      case 'pdf': return '📄';
      case 'doc':
      case 'docx': return '📝';
      case 'xls':
      case 'xlsx': return '📊';
      case 'ppt':
      case 'pptx': return '📽️';
      default: return '📁';
    }
  };

  const getDocIconClass = (extension) => {
    if (!extension) return 'doc-icon';
    const ext = extension.toLowerCase().replace('.', '');
    return `doc-icon ${ext}`;
  };

  const formatFileSize = (bytes) => {
    if (!bytes) return '0 B';
    if (bytes < 1024) return bytes + ' B';
    const kb = bytes / 1024;
    if (kb < 1024) return kb.toFixed(1) + ' KB';
    const mb = kb / 1024;
    return mb.toFixed(2) + ' MB';
  };

  return (
    <>
      {/* Content Header */}
      <div className="content-header">
        <h1>Edit Document</h1>
        <p className="section-subtitle">Update document details</p>
      </div>

      {/* Back Button */}
      <div className="action-bar">
        <button className="btn btn-secondary" onClick={cancel}>
          ← Back to Documents
        </button>
      </div>

      {/* Error Message */}
      {error && <div className="alert alert-error">{error}</div>}

      {/* Loading State */}
      {loading && !formData.title && (
        <div className="loading-container">
          <div className="spinner"></div>
          <p>Loading document...</p>
        </div>
      )}

      {/* Edit Form */}
      {(!loading || formData.title) && document && (
        <form className="admin-form" onSubmit={handleSubmit}>
          {/* Current Document Info */}
          <div className="form-group">
            <label>Current Document</label>
            <div className="document-info">
              <div className={getDocIconClass(document.file_extension)}>
                {getDocumentIcon(document.file_extension)}
              </div>
              <div>
                <div><strong>{document.original_filename}</strong></div>
                <div className="file-info">{formatFileSize(document.file_size)}</div>
              </div>
            </div>
          </div>

          {/* Document Title */}
          <div className="form-group">
            <label htmlFor="title">Document Title <span className="required">*</span></label>
            <input
              type="text"
              id="title"
              name="title"
              className="form-control"
              value={formData.title}
              onChange={handleInputChange}
              placeholder="Enter document title"
              maxLength="255"
              required
            />
            <small className="form-help">This title will be displayed on the website</small>
          </div>

          {/* Description */}
          <div className="form-group">
            <label htmlFor="description">Description</label>
            <textarea
              id="description"
              name="description"
              className="form-control"
              value={formData.description}
              onChange={handleInputChange}
              placeholder="Brief description of this document"
              rows="3"
            ></textarea>
            <small className="form-help">Optional description shown with the document</small>
          </div>

          {/* Document Type */}
          <div className="form-group">
            <label htmlFor="document_type">Document Type</label>
            <input
              type="text"
              id="document_type"
              name="document_type"
              className="form-control"
              value={formData.document_type}
              onChange={handleInputChange}
              placeholder="e.g., Workshop Materials, Registration Form, etc."
              maxLength="100"
            />
            <small className="form-help">Optional category or type for this document</small>
          </div>

          {/* Is Active Checkbox */}
          <div className="form-group">
            <label className="checkbox-label">
              <input
                type="checkbox"
                name="is_active"
                checked={formData.is_active}
                onChange={handleInputChange}
              />
              <span>Active (visible on website)</span>
            </label>
          </div>

          {/* Form Actions */}
          <div className="form-actions">
            <button
              type="submit"
              className="btn btn-primary"
              disabled={loading}
            >
              {loading ? 'Saving...' : 'Update Document'}
            </button>

            <button
              type="button"
              className="btn btn-secondary"
              onClick={cancel}
              disabled={loading}
            >
              Cancel
            </button>
          </div>
        </form>
      )}
    </>
  );
}

export default DocumentEdit;
