// angular-app-source/src/app/admin/documents/document-list/document-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { DocumentsService } from '../../services/documents.service';
import { Document } from '../../models/document.model';

@Component({
  selector: 'app-document-list',
  standalone: false,
  templateUrl: './document-list.component.html',
  styleUrls: ['./document-list.component.css']
})
export class DocumentListComponent implements OnInit {
  documents: Document[] = [];
  filteredDocuments: Document[] = [];
  loading = false;
  error: string | null = null;
  searchQuery = '';
  statusFilter = 'all';

  // Pagination
  currentPage = 1;
  itemsPerPage = 10;

  constructor(
    private documentsService: DocumentsService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loadDocuments();
  }

  /**
   * Load all documents from API
   */
  loadDocuments(): void {
    this.loading = true;
    this.error = null;

    this.documentsService.getAll().subscribe({
      next: (data) => {
        this.documents = data;
        this.applyFilters();
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message || 'Failed to load documents';
        this.loading = false;
        console.error('Error loading documents:', err);
      }
    });
  }

  /**
   * Apply search and status filters
   */
  applyFilters(): void {
    let filtered = [...this.documents];

    // Apply status filter
    if (this.statusFilter === 'active') {
      filtered = filtered.filter(doc => doc.is_active);
    } else if (this.statusFilter === 'inactive') {
      filtered = filtered.filter(doc => !doc.is_active);
    }

    // Apply search filter (case-insensitive)
    if (this.searchQuery.trim()) {
      const query = this.searchQuery.toLowerCase();
      filtered = filtered.filter(doc =>
        doc.title.toLowerCase().includes(query) ||
        (doc.description && doc.description.toLowerCase().includes(query)) ||
        doc.original_filename.toLowerCase().includes(query)
      );
    }

    this.filteredDocuments = filtered;
  }

  /**
   * Handle search input
   */
  onSearch(): void {
    this.currentPage = 1;
    this.applyFilters();
  }

  /**
   * Handle status filter change
   */
  onStatusFilterChange(): void {
    this.currentPage = 1;
    this.applyFilters();
  }

  /**
   * Navigate to upload page
   */
  uploadNew(): void {
    this.router.navigate(['/admin/documents/upload']);
  }

  /**
   * Navigate to edit page
   */
  edit(id: number): void {
    this.router.navigate(['/admin/documents/edit', id]);
  }

  /**
   * Toggle active status
   */
  toggleActive(document: Document): void {
    this.documentsService.toggleActive(document.id).subscribe({
      next: (updated) => {
        const index = this.documents.findIndex(doc => doc.id === document.id);
        if (index !== -1) {
          this.documents[index] = updated;
        }

        const filteredIndex = this.filteredDocuments.findIndex(doc => doc.id === document.id);
        if (filteredIndex !== -1) {
          this.filteredDocuments[filteredIndex] = updated;
        }
      },
      error: (err) => {
        this.error = 'Failed to toggle status';
        console.error('Error toggling status:', err);
      }
    });
  }

  /**
   * Navigate to delete confirmation page
   */
  deleteDocument(document: Document): void {
    this.router.navigate(['/admin/documents/delete', document.id]);
  }

  /**
   * Update display order
   */
  updateDisplayOrder(document: Document, newOrder: number): void {
    this.documentsService.updateOrder(document.id, newOrder).subscribe({
      next: () => {
        this.loadDocuments();
      },
      error: (err) => {
        this.error = 'Failed to update order';
        console.error('Error updating order:', err);
      }
    });
  }

  /**
   * Get document icon based on file extension
   */
  getDocumentIcon(extension: string): string {
    const ext = extension.toLowerCase().replace('.', '');
    switch(ext) {
      case 'pdf': return '📄';
      case 'doc':
      case 'docx': return '📝';
      case 'xls':
      case 'xlsx': return '📊';
      case 'ppt':
      case 'pptx': return '📽️';
      default: return '📁';
    }
  }

  /**
   * Get document icon CSS class
   */
  getDocIconClass(extension: string): string {
    const ext = extension.toLowerCase().replace('.', '');
    return `doc-icon ${ext}`;
  }

  /**
   * Format file size for display
   */
  formatFileSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' B';
    const kb = bytes / 1024;
    if (kb < 1024) return kb.toFixed(1) + ' KB';
    const mb = kb / 1024;
    return mb.toFixed(2) + ' MB';
  }

  /**
   * Get paginated documents for current page
   */
  getPaginatedDocuments(): Document[] {
    const startIndex = (this.currentPage - 1) * this.itemsPerPage;
    const endIndex = startIndex + this.itemsPerPage;
    return this.filteredDocuments.slice(startIndex, endIndex);
  }

  /**
   * Get total number of pages
   */
  getTotalPages(): number {
    return Math.max(1, Math.ceil(this.filteredDocuments.length / this.itemsPerPage));
  }

  /**
   * Get page numbers to display
   */
  getPageNumbers(): number[] {
    const totalPages = this.getTotalPages();
    const maxPagesToShow = 5;
    let startPage = Math.max(1, this.currentPage - Math.floor(maxPagesToShow / 2));
    let endPage = Math.min(totalPages, startPage + maxPagesToShow - 1);

    if (endPage - startPage < maxPagesToShow - 1) {
      startPage = Math.max(1, endPage - maxPagesToShow + 1);
    }

    const pages: number[] = [];
    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }
    return pages;
  }

  getPageStart(): number {
    if (this.filteredDocuments.length === 0) return 0;
    return (this.currentPage - 1) * this.itemsPerPage + 1;
  }

  getPageEnd(): number {
    const end = this.currentPage * this.itemsPerPage;
    return Math.min(end, this.filteredDocuments.length);
  }

  goToPage(page: number): void {
    this.currentPage = page;
  }

  previousPage(): void {
    if (this.currentPage > 1) {
      this.currentPage--;
    }
  }

  nextPage(): void {
    if (this.currentPage < this.getTotalPages()) {
      this.currentPage++;
    }
  }
}

// react-app-source/src/pages/admin/DocumentList.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { documentsService } from '../../services/admin-api';

function DocumentList() {
  const navigate = useNavigate();
  const [documents, setDocuments] = useState([]);
  const [filteredDocuments, setFilteredDocuments] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');

  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;

  useEffect(() => {
    loadDocuments();
  }, []);

  useEffect(() => {
    applyFilters();
  }, [documents, searchQuery]);

  const loadDocuments = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await documentsService.getAll();
      setDocuments(response.data || []);
      setLoading(false);
    } catch (err) {
      setError(err.message || 'Failed to load documents');
      setLoading(false);
      console.error('Error loading documents:', err);
    }
  };

  const applyFilters = () => {
    let filtered = [...documents];

    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(doc =>
        doc.title?.toLowerCase().includes(query) ||
        doc.description?.toLowerCase().includes(query)
      );
    }

    setFilteredDocuments(filtered);
  };

  const onSearch = (e) => {
    setSearchQuery(e.target.value);
    setCurrentPage(1);
  };

  const uploadNew = () => {
    navigate('/admin/documents/upload');
  };

  const edit = (id) => {
    navigate(`/admin/documents/edit/${id}`);
  };

  const toggleActive = async (doc) => {
    try {
      const response = await documentsService.toggleActive(doc.id);
      const updated = response.data;

      // Smooth single-row update instead of reloading entire list
      setDocuments(prev => prev.map(d =>
        d.id === doc.id ? { ...d, ...updated } : d
      ));
    } catch (err) {
      setError('Failed to toggle status');
      console.error('Error toggling status:', err);
    }
  };

  const deleteDocument = (doc) => {
    navigate(`/admin/documents/delete/${doc.id}`);
  };

  const getFileIcon = (extension) => {
    switch (extension?.toLowerCase()) {
      case 'pdf': return '📄';
      case 'doc':
      case 'docx': return '📝';
      case 'xls':
      case 'xlsx': return '📊';
      case 'ppt':
      case 'pptx': return '📑';
      default: return '📁';
    }
  };

  const getPaginatedDocuments = () => {
    const startIndex = (currentPage - 1) * itemsPerPage;
    return filteredDocuments.slice(startIndex, startIndex + itemsPerPage);
  };

  const getTotalPages = () => Math.max(1, Math.ceil(filteredDocuments.length / itemsPerPage));
  const getPageStart = () => filteredDocuments.length === 0 ? 0 : (currentPage - 1) * itemsPerPage + 1;
  const getPageEnd = () => Math.min(currentPage * itemsPerPage, filteredDocuments.length);

  return (
    <>
      <div className="content-header">
        <h1>Manage Documents</h1>
        <p>Upload and manage downloadable documents</p>
      </div>

      <div className="section">
        <div className="section-header">
          <h2>All Documents ({documents.length})</h2>
          <button className="btn btn-primary" onClick={uploadNew}>
            + Upload New Document
          </button>
        </div>

        <div className="search-container">
          <input
            type="text"
            className="search-input"
            placeholder="Search by title or description..."
            value={searchQuery}
            onChange={onSearch}
          />
          <span className="search-results">
            Showing {filteredDocuments.length} of {documents.length} total
          </span>
        </div>

        {error && <div className="alert alert-error">{error}</div>}

        {loading && (
          <div className="loading-container">
            <div className="spinner"></div>
            <p>Loading documents...</p>
          </div>
        )}

        {!loading && filteredDocuments.length > 0 && (
          <div className="pagination-container">
            <div className="pagination-info">
              Showing {getPageStart()}-{getPageEnd()} of {filteredDocuments.length} total
            </div>
          </div>
        )}

        {!loading && (
          <div className="table-container">
            <table className="data-table">
              <thead>
                <tr>
                  <th style={{ width: '5%' }}>Type</th>
                  <th style={{ width: '35%' }}>Title</th>
                  <th style={{ width: '20%' }}>Category</th>
                  <th style={{ width: '10%' }}>Size</th>
                  <th style={{ width: '10%' }}>Status</th>
                  <th style={{ width: '15%' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredDocuments.length === 0 && (
                  <tr>
                    <td colSpan="6" className="text-center">
                      <div className="empty-state">
                        <p>{searchQuery ? 'No documents match your search' : 'No documents yet'}</p>
                        {!searchQuery && (
                          <button className="btn btn-primary btn-sm" onClick={uploadNew}>
                            Upload First Document
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                )}

                {getPaginatedDocuments().map(doc => (
                  <tr key={doc.id}>
                    <td>{getFileIcon(doc.fileextension)}</td>
                    <td data-label="TITLE">
                      <strong>{doc.title}</strong>
                      {doc.description && (
                        <>
                          <br />
                          <small className="text-muted">{doc.description}</small>
                        </>
                      )}
                    </td>
                    <td data-label="CATEGORY">{doc.documenttype || 'General'}</td>
                    <td data-label="SIZE">{doc.filesizeformatted}</td>
                    <td data-label="STATUS">
                      {doc.is_active ? (
                        <span className="badge badge-success">✓ Active</span>
                      ) : (
                        <span className="badge badge-inactive">Inactive</span>
                      )}
                    </td>
                    <td data-label="ACTIONS" className="actions">
                      <button className="btn btn-sm btn-edit" onClick={() => edit(doc.id)} title="Edit">✏️</button>
                      <button className="btn btn-sm btn-toggle" onClick={() => toggleActive(doc)} title="Toggle">
                        {doc.is_active ? '👁️' : '🚫'}
                      </button>
                      <button className="btn btn-sm btn-delete" onClick={() => deleteDocument(doc)} title="Delete">🗑️</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {!loading && filteredDocuments.length > itemsPerPage && (
          <div className="pagination-container">
            <div className="pagination-controls">
              <button
                className="pagination-btn"
                onClick={() => setCurrentPage(p => p - 1)}
                disabled={currentPage === 1}
              >
                « Previous
              </button>
              <span style={{ padding: '0 16px' }}>Page {currentPage} of {getTotalPages()}</span>
              <button
                className="pagination-btn"
                onClick={() => setCurrentPage(p => p + 1)}
                disabled={currentPage === getTotalPages()}
              >
                Next »
              </button>
            </div>
          </div>
        )}
      </div>
    </>
  );
}

export default DocumentList;
