// Front_End/angular-app-source/src/app/admin/documents/document-upload/document-upload.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { DocumentsService } from '../../services/documents.service';

@Component({
  selector: 'app-document-upload',
  standalone: false,
  templateUrl: './document-upload.component.html',
  styleUrls: ['./document-upload.component.css']
})
export class DocumentUploadComponent {
  loading = false;
  error: string | null = null;
  selectedFile: File | null = null;

  formData = {
    title: '',
    description: '',
    document_type: '',
    is_active: false
  };

  constructor(
    private router: Router,
    private documentsService: DocumentsService
  ) {}

  onFileSelected(event: any): void {
    const file = event.target.files[0];
    if (file) {
      // Validate file type
      const validTypes = [
        'application/pdf',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation'
      ];

      if (!validTypes.includes(file.type)) {
        this.error = 'Invalid file type. Only PDF, Word, Excel, and PowerPoint files are allowed.';
        this.selectedFile = null;
        return;
      }

      // Validate file size (10MB max)
      if (file.size > 10485760) {
        this.error = 'File size exceeds 10MB maximum. Please choose a smaller document.';
        this.selectedFile = null;
        return;
      }

      this.selectedFile = file;
      this.error = null;
    }
  }

  onSubmit(): void {
    if (!this.formData.title.trim()) {
      this.error = 'Document Title is required';
      return;
    }
    if (!this.selectedFile) {
      this.error = 'Document File is required';
      return;
    }

    this.loading = true;
    this.error = null;

    const uploadData = new FormData();
    uploadData.append('document_file', this.selectedFile);
    uploadData.append('title', this.formData.title);
    uploadData.append('description', this.formData.description || '');
    uploadData.append('document_type', this.formData.document_type || '');
    uploadData.append('is_active', this.formData.is_active ? '1' : '0');

    this.documentsService.upload(uploadData).subscribe({
      next: () => {
        this.router.navigate(['/admin/documents']);
      },
      error: (err) => {
        this.error = err.message || 'Failed to upload document';
        this.loading = false;
        console.error('Error uploading document:', err);
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/admin/documents']);
  }
}

<!-- Content Header -->
<div class="content-header">
  <h1>Upload New Document</h1>
  <p class="section-subtitle">Add a new document to resources</p>
</div>

<!-- Back Button -->
<div class="action-bar">
  <button class="btn btn-secondary" (click)="cancel()">
    ← Back to Documents
  </button>
</div>

<!-- Error Message -->
<div class="alert alert-error" *ngIf="error">
  {{ error }}
</div>

<!-- Upload Form -->
<form class="admin-form" (ngSubmit)="onSubmit()">
  <!-- Document Title -->
  <div class="form-group">
    <label for="title">Document Title <span class="required">*</span></label>
    <input
      type="text"
      id="title"
      name="title"
      class="form-control"
      [(ngModel)]="formData.title"
      placeholder="Enter document title"
      maxlength="255"
      required
    />
    <small class="form-help">This title will be displayed on the website</small>
  </div>

  <!-- Description -->
  <div class="form-group">
    <label for="description">Description</label>
    <textarea
      id="description"
      name="description"
      class="form-control"
      [(ngModel)]="formData.description"
      placeholder="Brief description of this document"
      rows="3"
    ></textarea>
    <small class="form-help">Optional description shown with the document</small>
  </div>

  <!-- Document File Upload -->
  <div class="form-group">
    <label for="document_file">Document File <span class="required">*</span></label>
    <input
      type="file"
      id="document_file"
      name="document_file"
      class="form-control"
      accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx"
      (change)="onFileSelected($event)"
      required
    />
    <small class="form-help">Supported formats: PDF, Word, Excel, PowerPoint (Max 10MB)</small>
  </div>

  <!-- Document Type -->
  <div class="form-group">
    <label for="document_type">Document Type</label>
    <input
      type="text"
      id="document_type"
      name="document_type"
      class="form-control"
      [(ngModel)]="formData.document_type"
      placeholder="e.g., Workshop Materials, Registration Form, etc."
      maxlength="100"
    />
    <small class="form-help">Optional category or type for this document</small>
  </div>

  <!-- Is Active Checkbox -->
  <div class="form-group">
    <label class="checkbox-label">
      <input
        type="checkbox"
        name="is_active"
        [(ngModel)]="formData.is_active"
      />
      <span>Active (visible on website)</span>
    </label>
  </div>

  <!-- Form Actions -->
  <div class="form-actions">
    <button
      type="submit"
      class="btn btn-primary"
      [disabled]="loading"
    >
      {{ loading ? 'Uploading...' : 'Upload Document' }}
    </button>

    <button
      type="button"
      class="btn btn-secondary"
      (click)="cancel()"
      [disabled]="loading"
    >
      Cancel
    </button>
  </div>
</form>

// react-app-source/src/pages/admin/DocumentUpload.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { documentsService } from '../../services/admin-api';

function DocumentUpload() {
  const navigate = useNavigate();

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [selectedFile, setSelectedFile] = useState(null);

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    document_type: '',
    is_active: false
  });

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      // Validate file type
      const validTypes = [
        'application/pdf',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation'
      ];

      if (!validTypes.includes(file.type)) {
        setError('Invalid file type. Only PDF, Word, Excel, and PowerPoint files are allowed.');
        setSelectedFile(null);
        return;
      }

      // Validate file size (10MB max)
      if (file.size > 10485760) {
        setError('File size exceeds 10MB maximum. Please choose a smaller document.');
        setSelectedFile(null);
        return;
      }

      setSelectedFile(file);
      setError(null);
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.title.trim()) {
      setError('Document Title is required');
      return;
    }
    if (!selectedFile) {
      setError('Document File is required');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const uploadData = new FormData();
      uploadData.append('document_file', selectedFile);
      uploadData.append('title', formData.title);
      uploadData.append('description', formData.description || '');
      uploadData.append('document_type', formData.document_type || '');
      uploadData.append('is_active', formData.is_active ? '1' : '0');

      await documentsService.upload(uploadData);
      navigate('/admin/documents');
    } catch (err) {
      setError(err.message || 'Failed to upload document');
      setLoading(false);
      console.error('Error uploading document:', err);
    }
  };

  const cancel = () => {
    navigate('/admin/documents');
  };

  return (
    <>
      {/* Content Header */}
      <div className="content-header">
        <h1>Upload New Document</h1>
        <p className="section-subtitle">Add a new document to resources</p>
      </div>

      {/* Back Button */}
      <div className="action-bar">
        <button className="btn btn-secondary" onClick={cancel}>
          ← Back to Documents
        </button>
      </div>

      {/* Error Message */}
      {error && <div className="alert alert-error">{error}</div>}

      {/* Upload Form */}
      <form className="admin-form" onSubmit={handleSubmit}>
        {/* Document Title */}
        <div className="form-group">
          <label htmlFor="title">Document Title <span className="required">*</span></label>
          <input
            type="text"
            id="title"
            name="title"
            className="form-control"
            value={formData.title}
            onChange={handleInputChange}
            placeholder="Enter document title"
            maxLength="255"
            required
          />
          <small className="form-help">This title will be displayed on the website</small>
        </div>

        {/* Description */}
        <div className="form-group">
          <label htmlFor="description">Description</label>
          <textarea
            id="description"
            name="description"
            className="form-control"
            value={formData.description}
            onChange={handleInputChange}
            placeholder="Brief description of this document"
            rows="3"
          ></textarea>
          <small className="form-help">Optional description shown with the document</small>
        </div>

        {/* Document File Upload */}
        <div className="form-group">
          <label htmlFor="document_file">Document File <span className="required">*</span></label>
          <input
            type="file"
            id="document_file"
            name="document_file"
            className="form-control"
            accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx"
            onChange={handleFileChange}
            required
          />
          <small className="form-help">Supported formats: PDF, Word, Excel, PowerPoint (Max 10MB)</small>
        </div>

        {/* Document Type */}
        <div className="form-group">
          <label htmlFor="document_type">Document Type</label>
          <input
            type="text"
            id="document_type"
            name="document_type"
            className="form-control"
            value={formData.document_type}
            onChange={handleInputChange}
            placeholder="e.g., Workshop Materials, Registration Form, etc."
            maxLength="100"
          />
          <small className="form-help">Optional category or type for this document</small>
        </div>

        {/* Is Active Checkbox */}
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              name="is_active"
              checked={formData.is_active}
              onChange={handleInputChange}
            />
            <span>Active (visible on website)</span>
          </label>
        </div>

        {/* Form Actions */}
        <div className="form-actions">
          <button
            type="submit"
            className="btn btn-primary"
            disabled={loading}
          >
            {loading ? 'Uploading...' : 'Upload Document'}
          </button>

          <button
            type="button"
            className="btn btn-secondary"
            onClick={cancel}
            disabled={loading}
          >
            Cancel
          </button>
        </div>
      </form>
    </>
  );
}

export default DocumentUpload;
