// Front_End/angular-app/src/app/admin/gallery/gallery-list/gallery-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { GalleryService } from '../../services/gallery.service';
import { GalleryImage } from '../../models/gallery.model';

@Component({
  selector: 'app-gallery-list',
  standalone: false,
  templateUrl: './gallery-list.component.html',
  styleUrls: ['./gallery-list.component.css']
})
export class GalleryListComponent implements OnInit {
  images: GalleryImage[] = [];
  filteredImages: GalleryImage[] = [];
  loading = false;
  error: string | null = null;
  searchQuery = '';
  statusFilter = 'all';
  currentLocation: 'about_page' | 'gallery' = 'gallery';

  // Tab counts
  aboutPageCount = 0;
  galleryCount = 0;

  // Pagination
  currentPage = 1;
  itemsPerPage = 10;

  constructor(
    private galleryService: GalleryService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    // Get location from query params (default to gallery)
    this.route.queryParams.subscribe(params => {
      this.currentLocation = (params['location'] as 'about_page' | 'gallery') || 'gallery';
      this.loadImages();
      this.loadTabCounts();
    });
  }

  /**
   * Load all images for current location from API
   */
  loadImages(): void {
    this.loading = true;
    this.error = null;

    this.galleryService.getAll(this.currentLocation).subscribe({
      next: (data) => {
        this.images = data;
        this.applyFilters();
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message || 'Failed to load images';
        this.loading = false;
        console.error('Error loading images:', err);
      }
    });
  }

  /**
   * Load counts for both tabs
   */
  loadTabCounts(): void {
    // Load About Page count
    this.galleryService.getAll('about_page').subscribe({
      next: (data) => {
        this.aboutPageCount = data.length;
      },
      error: (err) => {
        console.error('Error loading about page count:', err);
      }
    });

    // Load Gallery count
    this.galleryService.getAll('gallery').subscribe({
      next: (data) => {
        this.galleryCount = data.length;
      },
      error: (err) => {
        console.error('Error loading gallery count:', err);
      }
    });
  }

  /**
   * Switch to a different location tab
   */
  switchTab(location: 'about_page' | 'gallery'): void {
    this.currentLocation = location;
    this.currentPage = 1;
    this.searchQuery = '';
    this.statusFilter = 'all';
    this.router.navigate(['/admin/gallery'], { queryParams: { location } });
  }

  /**
   * Apply search and status filters
   */
  applyFilters(): void {
    let filtered = [...this.images];

    // Apply status filter
    if (this.statusFilter === 'active') {
      filtered = filtered.filter(img => img.is_active);
    } else if (this.statusFilter === 'inactive') {
      filtered = filtered.filter(img => !img.is_active);
    }

    // Apply search filter (case-insensitive)
    if (this.searchQuery.trim()) {
      const query = this.searchQuery.toLowerCase();
      filtered = filtered.filter(img =>
        img.title.toLowerCase().includes(query) ||
        img.original_filename.toLowerCase().includes(query)
      );
    }

    this.filteredImages = filtered;
  }

  /**
   * Handle search input
   */
  onSearch(): void {
    this.currentPage = 1; // Reset to page 1 on search
    this.applyFilters();
  }

  /**
   * Handle status filter change
   */
  onStatusFilterChange(): void {
    this.currentPage = 1; // Reset to page 1 on filter change
    this.applyFilters();
  }

  /**
   * Navigate to upload page
   */
  uploadNew(): void {
    this.router.navigate(['/admin/gallery/upload'], {
      queryParams: { location: this.currentLocation }
    });
  }

  /**
   * Navigate to edit page
   */
  edit(id: number): void {
    this.router.navigate(['/admin/gallery/edit', id], {
      queryParams: { location: this.currentLocation }
    });
  }

  /**
   * Toggle active status
   */
  toggleActive(image: GalleryImage): void {
    this.galleryService.toggleActive(image.id).subscribe({
      next: (updated) => {
        // Update local data
        const index = this.images.findIndex(img => img.id === image.id);
        if (index !== -1) {
          this.images[index] = updated;
        }

        // Update filtered list
        const filteredIndex = this.filteredImages.findIndex(img => img.id === image.id);
        if (filteredIndex !== -1) {
          this.filteredImages[filteredIndex] = updated;
        }
      },
      error: (err) => {
        this.error = 'Failed to toggle status';
        console.error('Error toggling status:', err);
      }
    });
  }

  /**
   * Navigate to delete confirmation page
   */
  deleteImage(image: GalleryImage): void {
    this.router.navigate(['/admin/gallery/delete', image.id]);
  }

  /**
   * Update display order
   */
  updateDisplayOrder(image: GalleryImage, newOrder: number): void {
    this.galleryService.updateOrder(image.id, newOrder, this.currentLocation).subscribe({
      next: () => {
        this.loadImages(); // Reload to get updated order
        this.loadTabCounts(); // Update tab counts
      },
      error: (err) => {
        this.error = 'Failed to update order';
        console.error('Error updating order:', err);
      }
    });
  }

  /**
   * Get image URL
   */
  getImageUrl(filename: string): string {
    return `/assets/img/gallery/${filename}`;
  }

  /**
   * Format file size for display
   */
  formatFileSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  }

  /**
   * Get paginated images for current page
   */
  getPaginatedImages(): GalleryImage[] {
    const startIndex = (this.currentPage - 1) * this.itemsPerPage;
    const endIndex = startIndex + this.itemsPerPage;
    return this.filteredImages.slice(startIndex, endIndex);
  }

  /**
   * Get total number of pages
   */
  getTotalPages(): number {
    return Math.max(1, Math.ceil(this.filteredImages.length / this.itemsPerPage));
  }

  /**
   * Get page numbers to display
   */
  getPageNumbers(): number[] {
    const totalPages = this.getTotalPages();
    const maxPagesToShow = 5;
    let startPage = Math.max(1, this.currentPage - Math.floor(maxPagesToShow / 2));
    let endPage = Math.min(totalPages, startPage + maxPagesToShow - 1);

    if (endPage - startPage < maxPagesToShow - 1) {
      startPage = Math.max(1, endPage - maxPagesToShow + 1);
    }

    const pages: number[] = [];
    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }
    return pages;
  }

  /**
   * Get start index for current page (for display)
   */
  getPageStart(): number {
    if (this.filteredImages.length === 0) return 0;
    return (this.currentPage - 1) * this.itemsPerPage + 1;
  }

  /**
   * Get end index for current page (for display)
   */
  getPageEnd(): number {
    const end = this.currentPage * this.itemsPerPage;
    return Math.min(end, this.filteredImages.length);
  }

  /**
   * Go to specific page
   */
  goToPage(page: number): void {
    this.currentPage = page;
  }

  /**
   * Go to previous page
   */
  previousPage(): void {
    if (this.currentPage > 1) {
      this.currentPage--;
    }
  }

  /**
   * Go to next page
   */
  nextPage(): void {
    if (this.currentPage < this.getTotalPages()) {
      this.currentPage++;
    }
  }
}

<div class="page-header">
  <h1>Gallery</h1>
  <button class="btn btn-primary">Upload Images</button>
</div>

<div class="content-card">
  <p>Gallery items will be populated in Phase 2 (API Integration)</p>
</div>

// react-app-source/src/pages/admin/GalleryList.js
import React, { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { galleryService } from '../../services/admin-api';

function GalleryList() {
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();

  const [images, setImages] = useState([]);
  const [filteredImages, setFilteredImages] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [currentLocation, setCurrentLocation] = useState(searchParams.get('location') || 'gallery');

  // Tab counts
  const [galleryCount, setGalleryCount] = useState(0);
  const [aboutPageCount, setAboutPageCount] = useState(0);

  // Pagination
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;

  // Image preview modal
  const [showModal, setShowModal] = useState(false);
  const [modalImageUrl, setModalImageUrl] = useState('');

  useEffect(() => {
    loadImages();
    loadTabCounts();
  }, [currentLocation]);

  useEffect(() => {
    applyFilters();
  }, [images, searchQuery, statusFilter]);

  const loadImages = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await galleryService.getAll(currentLocation);
      setImages(response.data || []);
      setLoading(false);
    } catch (err) {
      setError(err.message || 'Failed to load images');
      setLoading(false);
      console.error('Error loading images:', err);
    }
  };

  const loadTabCounts = async () => {
    try {
      const [aboutRes, galleryRes] = await Promise.all([
        galleryService.getAll('about_page'),
        galleryService.getAll('gallery')
      ]);
      setAboutPageCount((aboutRes.data || []).length);
      setGalleryCount((galleryRes.data || []).length);
    } catch (err) {
      console.error('Error loading tab counts:', err);
    }
  };

  const switchTab = (location) => {
    setCurrentLocation(location);
    setCurrentPage(1);
    setSearchQuery('');
    setStatusFilter('all');
    setSearchParams({ location });
  };

  const applyFilters = () => {
    let filtered = [...images];

    // Apply status filter
    if (statusFilter === 'active') {
      filtered = filtered.filter(img => img.is_active);
    } else if (statusFilter === 'inactive') {
      filtered = filtered.filter(img => !img.is_active);
    }

    // Apply search filter
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(img =>
        img.title?.toLowerCase().includes(query) ||
        img.original_filename?.toLowerCase().includes(query)
      );
    }

    setFilteredImages(filtered);
  };

  const onSearch = (e) => {
    setSearchQuery(e.target.value);
    setCurrentPage(1);
  };

  const onStatusFilterChange = (e) => {
    setStatusFilter(e.target.value);
    setCurrentPage(1);
  };

  const uploadNew = () => {
    navigate('/admin/gallery/upload', { state: { location: currentLocation } });
  };

  const edit = (id) => {
    navigate(`/admin/gallery/edit/${id}`, { state: { location: currentLocation } });
  };

  const toggleActive = async (image) => {
    try {
      const response = await galleryService.toggleActive(image.id);
      const updated = response.data;

      // Smooth single-row update instead of reloading entire list
      setImages(prev => prev.map(img =>
        img.id === image.id ? { ...img, ...updated } : img
      ));
    } catch (err) {
      setError('Failed to toggle status');
      console.error('Error toggling status:', err);
    }
  };

  const deleteImage = (image) => {
    navigate(`/admin/gallery/delete/${image.id}`);
  };

  const updateDisplayOrder = async (image, newOrder) => {
    try {
      await galleryService.updateOrder(image.id, parseInt(newOrder), currentLocation);
      loadImages(); // Reload to get updated order
      loadTabCounts(); // Update tab counts
    } catch (err) {
      setError('Failed to update order');
      console.error('Error updating order:', err);
    }
  };

  const getImageUrl = (filename) => `/assets/img/gallery/${filename}`;

  const formatFileSize = (bytes) => {
    if (!bytes) return '0 B';
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  };

  const openImageModal = (filename) => {
    setModalImageUrl(getImageUrl(filename));
    setShowModal(true);
  };

  const closeModal = () => {
    setShowModal(false);
    setModalImageUrl('');
  };

  // Pagination helpers
  const getPaginatedImages = () => {
    const startIndex = (currentPage - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    return filteredImages.slice(startIndex, endIndex);
  };

  const getTotalPages = () => Math.max(1, Math.ceil(filteredImages.length / itemsPerPage));

  const getPageNumbers = () => {
    const totalPages = getTotalPages();
    const maxPagesToShow = 5;
    let startPage = Math.max(1, currentPage - Math.floor(maxPagesToShow / 2));
    let endPage = Math.min(totalPages, startPage + maxPagesToShow - 1);

    if (endPage - startPage < maxPagesToShow - 1) {
      startPage = Math.max(1, endPage - maxPagesToShow + 1);
    }

    const pages = [];
    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }
    return pages;
  };

  const getPageStart = () => {
    if (filteredImages.length === 0) return 0;
    return (currentPage - 1) * itemsPerPage + 1;
  };

  const getPageEnd = () => {
    const end = currentPage * itemsPerPage;
    return Math.min(end, filteredImages.length);
  };

  const goToPage = (page) => setCurrentPage(page);
  const previousPage = () => { if (currentPage > 1) setCurrentPage(p => p - 1); };
  const nextPage = () => { if (currentPage < getTotalPages()) setCurrentPage(p => p + 1); };

  return (
    <>
      {/* Content Header */}
      <div className="content-header">
        <h1>Gallery Management</h1>
        <p>Manage images for About Page and Gallery</p>
      </div>

      {/* Tabs Navigation */}
      <div className="tabs">
        <button
          className={`tab ${currentLocation === 'gallery' ? 'active' : ''}`}
          onClick={() => switchTab('gallery')}
        >
          Gallery
          <span className="tab-badge">{galleryCount}</span>
        </button>
        <button
          className={`tab ${currentLocation === 'about_page' ? 'active' : ''}`}
          onClick={() => switchTab('about_page')}
        >
          About Page
          <span className="tab-badge">{aboutPageCount}</span>
        </button>
      </div>

      <div className="section">
        {/* Section Header with Upload Button */}
        <div className="section-header">
          <h2>{currentLocation === 'about_page' ? 'About Page' : 'Gallery'} Images ({images.length})</h2>
          <button className="btn btn-primary" onClick={uploadNew}>
            + Upload New Image
          </button>
        </div>

        {/* Search and Filter */}
        <div className="search-container">
          <input
            type="text"
            className="search-input"
            placeholder="Search by title or filename..."
            value={searchQuery}
            onChange={onSearch}
          />

          <select className="status-filter" value={statusFilter} onChange={onStatusFilterChange}>
            <option value="all">All Statuses</option>
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
          </select>

          {(searchQuery || statusFilter !== 'all') && (
            <span className="search-results">
              {filteredImages.length} result{filteredImages.length !== 1 ? 's' : ''} found
            </span>
          )}
        </div>

        {/* Error Message */}
        {error && <div className="alert alert-error">{error}</div>}

        {/* Loading State */}
        {loading && (
          <div className="loading-container">
            <div className="spinner"></div>
            <p>Loading images...</p>
          </div>
        )}

        {/* Pagination Info (Top) */}
        {!loading && filteredImages.length > 0 && (
          <div className="pagination-container">
            <div className="pagination-info">
              Showing {getPageStart()}-{getPageEnd()} of {filteredImages.length} total
            </div>
            <div className="pagination-controls">
              <button className="pagination-btn" onClick={previousPage} disabled={currentPage === 1}>
                « Previous
              </button>

              {getPageNumbers()[0] > 1 && (
                <button className="pagination-btn" onClick={() => goToPage(1)}>1</button>
              )}
              {getPageNumbers()[0] > 2 && (
                <span style={{ padding: '0 8px', color: '#666' }}>...</span>
              )}

              {getPageNumbers().map(page => (
                <button
                  key={page}
                  className={`pagination-btn ${page === currentPage ? 'active' : ''}`}
                  disabled={page === currentPage && getTotalPages() === 1}
                  onClick={() => goToPage(page)}
                >
                  {page}
                </button>
              ))}

              {getPageNumbers()[getPageNumbers().length - 1] < getTotalPages() - 1 && (
                <span style={{ padding: '0 8px', color: '#666' }}>...</span>
              )}
              {getPageNumbers()[getPageNumbers().length - 1] < getTotalPages() && (
                <button className="pagination-btn" onClick={() => goToPage(getTotalPages())}>
                  {getTotalPages()}
                </button>
              )}

              <button className="pagination-btn" onClick={nextPage} disabled={currentPage === getTotalPages()}>
                Next »
              </button>
            </div>
          </div>
        )}

        {/* Images Table */}
        {!loading && (
          <div className="table-container">
            <table className="data-table" id="gallery-table">
              <thead>
                <tr>
                  <th style={{ width: '8%' }}>Order</th>
                  <th style={{ width: '12%' }}>Preview</th>
                  <th style={{ width: '45%' }}>Image Details</th>
                  <th style={{ width: '15%' }}>Status</th>
                  <th style={{ width: '20%' }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {/* Empty State */}
                {filteredImages.length === 0 && (
                  <tr>
                    <td colSpan="5" className="text-center">
                      <div className="empty-state">
                        {searchQuery || statusFilter !== 'all' ? (
                          <p>No images match your filters</p>
                        ) : (
                          <>
                            <p>No {currentLocation === 'about_page' ? 'About Page' : 'Gallery'} images found.</p>
                            <button className="btn btn-primary btn-sm" onClick={uploadNew}>
                              Upload Your First Image
                            </button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                )}

                {/* Data Rows */}
                {getPaginatedImages().map(image => (
                  <tr key={image.id}>
                    {/* Display Order Dropdown */}
                    <td data-label="ORDER" className="text-center">
                      <select
                        className="order-select"
                        value={image.display_order || 1}
                        onChange={(e) => updateDisplayOrder(image, e.target.value)}
                      >
                        {Array.from({ length: images.length }, (_, idx) => (
                          <option key={idx + 1} value={idx + 1}>
                            {idx + 1}
                          </option>
                        ))}
                      </select>
                    </td>

                    {/* Image Preview */}
                    <td data-label="PREVIEW">
                      <img
                        src={getImageUrl(image.filename)}
                        alt={image.title}
                        className="image-thumbnail"
                        onClick={() => openImageModal(image.filename)}
                        style={{ cursor: 'pointer' }}
                        title="Click to preview full size"
                      />
                    </td>

                    {/* Image Details */}
                    <td data-label="IMAGE DETAILS">
                      <strong>{image.title}</strong>
                      <br />
                      <small className="text-muted">
                        {image.original_filename} ({formatFileSize(image.file_size)})
                      </small>
                    </td>

                    {/* Status Badge */}
                    <td data-label="STATUS">
                      {image.is_active ? (
                        <span className="badge badge-success">✓ Active</span>
                      ) : (
                        <span className="badge badge-inactive">Inactive</span>
                      )}
                    </td>

                    {/* Actions */}
                    <td data-label="ACTIONS" className="actions">
                      <button className="btn btn-sm btn-edit" onClick={() => edit(image.id)} title="Edit">
                        ✏️
                      </button>
                      <button className="btn btn-sm btn-toggle" onClick={() => toggleActive(image)} title="Toggle Active/Inactive">
                        {image.is_active ? '👁️' : '🚫'}
                      </button>
                      <button className="btn btn-sm btn-delete" onClick={() => deleteImage(image)} title="Delete">
                        🗑️
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Pagination (Bottom) */}
        {!loading && filteredImages.length > 0 && (
          <div className="pagination-container">
            <div className="pagination-info">
              Showing {getPageStart()}-{getPageEnd()} of {filteredImages.length} total
            </div>
            <div className="pagination-controls">
              <button className="pagination-btn" onClick={previousPage} disabled={currentPage === 1}>
                « Previous
              </button>

              {getPageNumbers()[0] > 1 && (
                <button className="pagination-btn" onClick={() => goToPage(1)}>1</button>
              )}
              {getPageNumbers()[0] > 2 && (
                <span style={{ padding: '0 8px', color: '#666' }}>...</span>
              )}

              {getPageNumbers().map(page => (
                <button
                  key={page}
                  className={`pagination-btn ${page === currentPage ? 'active' : ''}`}
                  disabled={page === currentPage && getTotalPages() === 1}
                  onClick={() => goToPage(page)}
                >
                  {page}
                </button>
              ))}

              {getPageNumbers()[getPageNumbers().length - 1] < getTotalPages() - 1 && (
                <span style={{ padding: '0 8px', color: '#666' }}>...</span>
              )}
              {getPageNumbers()[getPageNumbers().length - 1] < getTotalPages() && (
                <button className="pagination-btn" onClick={() => goToPage(getTotalPages())}>
                  {getTotalPages()}
                </button>
              )}

              <button className="pagination-btn" onClick={nextPage} disabled={currentPage === getTotalPages()}>
                Next »
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Image Preview Modal */}
      {showModal && (
        <div className="image-modal-overlay" onClick={closeModal}>
          <div className="image-modal-content" onClick={(e) => e.stopPropagation()}>
            <button className="modal-close-btn" onClick={closeModal}>&times;</button>
            <img src={modalImageUrl} alt="Full size preview" />
          </div>
        </div>
      )}
    </>
  );
}

export default GalleryList;
