// angular-app-source/src/app/admin/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: false,
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;
  loading = false;
  errorMessage = '';
  showPassword = false;
  returnUrl = '/admin/dashboard';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    // NOTE: Do not auto-redirect here. Allow users to see login page
    // even if they have a lingering session. This prevents security issues
    // where users navigating from error pages (activate/reset) get logged
    // in automatically. The ngOnInit will handle proper redirect logic.

    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  ngOnInit(): void {
    // Get return URL from route parameters or default to dashboard
    this.returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/admin/dashboard';

    // Check if user is already authenticated
    // Only redirect if they're authenticated AND not coming from an auth error page
    const fromActivate = this.route.snapshot.queryParams['from'] === 'activate';
    const fromReset = this.route.snapshot.queryParams['from'] === 'reset';

    if (this.authService.isAuthenticated() && !fromActivate && !fromReset) {
      // User is already logged in and not coming from error page, redirect to dashboard
      this.router.navigate(['/admin/dashboard']);
    }
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      this.errorMessage = 'Please enter both username and password.';
      return;
    }

    this.loading = true;
    this.errorMessage = '';

    const credentials = {
      username: this.loginForm.value.username.trim(),
      password: this.loginForm.value.password
    };

    this.authService.login(credentials).subscribe({
      next: (response) => {
        if (response.success) {
          // Check if user must change password
          if (response.user?.must_change_password) {
            this.router.navigate(['/admin/change-password']);
          } else {
            // Redirect to return URL or dashboard
            this.router.navigate([this.returnUrl]);
          }
        } else {
          this.errorMessage = response.message || 'Login failed. Please try again.';
          this.loading = false;
        }
      },
      error: (error) => {
        this.errorMessage = error.message || 'Login failed. Please check your credentials and try again.';
        this.loading = false;
      }
    });
  }

  togglePassword(): void {
    this.showPassword = !this.showPassword;
  }

  get usernameControl() {
    return this.loginForm.get('username');
  }

  get passwordControl() {
    return this.loginForm.get('password');
  }
}

<div class="login-container">
  <div class="login-box">
    <div class="login-header">
      <div class="logo">
        <img src="/assets/img/logo.png" alt="PASC Region J" class="logo-img">
      </div>
      <h1>Admin Panel</h1>
      <p>PASC Region J Conference 2026</p>
    </div>

    <!-- Error Message -->
    <div *ngIf="errorMessage" class="alert alert-error">
      {{ errorMessage }}
    </div>

    <!-- Login Form -->
    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="login-form">
      <div class="form-group">
        <label for="username">Username</label>
        <input
          type="text"
          id="username"
          formControlName="username"
          class="form-control"
          autocomplete="username"
          autofocus
          [class.error]="usernameControl?.invalid && usernameControl?.touched">
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <div class="password-input-wrapper">
          <input
            [type]="showPassword ? 'text' : 'password'"
            id="password"
            formControlName="password"
            class="form-control"
            autocomplete="current-password"
            [class.error]="passwordControl?.invalid && passwordControl?.touched">
          <button
            type="button"
            class="password-toggle"
            (click)="togglePassword()"
            aria-label="Toggle password visibility">
            <span class="toggle-icon">{{ showPassword ? '🙈' : '👁️' }}</span>
          </button>
        </div>
      </div>

      <button
        type="submit"
        class="btn btn-login"
        [disabled]="loading">
        <span *ngIf="!loading">Sign In</span>
        <span *ngIf="loading">Signing In...</span>
      </button>

      <div class="forgot-password-link">
        <a routerLink="/admin/forgot-password">Forgot Password?</a>
      </div>
    </form>

    <div class="login-footer">
      <!--<p><small>Default credentials: devadmin / Welcome01!</small></p>-->
      <p><small>Please change default password after first login</small></p>
    </div>
  </div>
</div>

// react-app-source/src/pages/admin/Login.js
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';

function Login() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { login, isAuthenticated } = useAuth();

  const [formData, setFormData] = useState({
    username: '',
    password: ''
  });
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  const returnUrl = searchParams.get('returnUrl') || '/admin/dashboard';

  useEffect(() => {
    // Check if user is already authenticated
    // Only redirect if they're authenticated AND not coming from an auth error page
    const fromActivate = searchParams.get('from') === 'activate';
    const fromReset = searchParams.get('from') === 'reset';

    if (isAuthenticated && !fromActivate && !fromReset) {
      navigate('/admin/dashboard');
    }
  }, [isAuthenticated, searchParams, navigate]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.username || !formData.password) {
      setErrorMessage('Please enter both username and password.');
      return;
    }

    setLoading(true);
    setErrorMessage('');

    try {
      const response = await login({
        username: formData.username.trim(),
        password: formData.password
      });

      if (response.success) {
        // Check if user must change password
        if (response.user?.must_change_password) {
          navigate('/admin/change-password');
        } else {
          navigate(returnUrl);
        }
      } else {
        setErrorMessage(response.message || 'Login failed. Please try again.');
        setLoading(false);
      }
    } catch (error) {
      setErrorMessage(error.message || 'Login failed. Please check your credentials and try again.');
      setLoading(false);
    }
  };

  const togglePassword = () => {
    setShowPassword(prev => !prev);
  };

  return (
    <div className="admin-login-page">
      <div className="login-container">
        <div className="login-box">
        <div className="login-header">
          <div className="logo">
            <img src="/assets/img/logo.png" alt="PASC Region J" className="logo-img" />
          </div>
          <h1>Admin Panel</h1>
          <p>PASC Region J Conference 2026</p>
        </div>

        {/* Error Message */}
        {errorMessage && (
          <div className="alert alert-error">
            {errorMessage}
          </div>
        )}

        {/* Login Form */}
        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label htmlFor="username">Username</label>
            <input
              type="text"
              id="username"
              name="username"
              value={formData.username}
              onChange={handleInputChange}
              className="form-control"
              autoComplete="username"
              autoFocus
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Password</label>
            <div className="password-input-wrapper">
              <input
                type={showPassword ? 'text' : 'password'}
                id="password"
                name="password"
                value={formData.password}
                onChange={handleInputChange}
                className="form-control"
                autoComplete="current-password"
              />
              <button
                type="button"
                className="password-toggle"
                onClick={togglePassword}
                aria-label="Toggle password visibility"
              >
                <span className="toggle-icon">{showPassword ? '🙈' : '👁️'}</span>
              </button>
            </div>
          </div>

          <button
            type="submit"
            className="btn btn-login"
            disabled={loading}
          >
            {loading ? 'Signing In...' : 'Sign In'}
          </button>

          <div className="forgot-password-link">
            <Link to="/admin/forgot-password">Forgot Password?</Link>
          </div>
        </form>

        <div className="login-footer">
          <p><small>Please change default password after first login</small></p>
        </div>
        </div>
      </div>
    </div>
  );
}

export default Login;
