// Front_End/angular-app-source/src/app/admin/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ProfileService } from '../services/profile.service';
import { User } from '../models/user.model';

@Component({
  selector: 'app-profile',
  standalone: false,
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  user: User | null = null;
  loading = true;

  // Form groups
  profileForm: FormGroup;
  passwordForm: FormGroup;

  // Success/error messages
  profileSuccess: string | null = null;
  profileError: string | null = null;
  passwordSuccess: string | null = null;
  passwordError: string | null = null;
  pictureSuccess: string | null = null;
  pictureError: string | null = null;

  // Loading states
  profileLoading = false;
  passwordLoading = false;
  pictureLoading = false;

  // Profile picture
  selectedPictureFile: File | null = null;
  picturePreviewUrl: string | null = null;

  // Password visibility toggles
  showCurrentPassword = false;
  showNewPassword = false;
  showConfirmNewPassword = false;

  constructor(
    private fb: FormBuilder,
    private profileService: ProfileService
  ) {
    // Initialize profile form
    this.profileForm = this.fb.group({
      full_name: ['', [Validators.required, Validators.maxLength(100)]],
      email: ['', [Validators.required, Validators.email, Validators.maxLength(100)]]
    });

    // Initialize password form
    this.passwordForm = this.fb.group({
      current_password: ['', Validators.required],
      new_password: ['', [
        Validators.required,
        Validators.minLength(8),
        Validators.pattern(/^(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z0-9]).{8,}$/)
      ]],
      confirm_new_password: ['', Validators.required]
    }, { validators: this.passwordMatchValidator });
  }

  ngOnInit(): void {
    this.loadProfile();
  }

  /**
   * Load user profile
   */
  loadProfile(): void {
    this.loading = true;
    this.profileService.getProfile().subscribe({
      next: (user) => {
        this.user = user;
        this.profileForm.patchValue({
          full_name: user.full_name,
          email: user.email
        });
        this.loading = false;
      },
      error: (err) => {
        this.profileError = err.message || 'Failed to load profile';
        this.loading = false;
      }
    });
  }

  /**
   * Update profile information
   */
  updateProfile(): void {
    if (this.profileForm.invalid) {
      this.profileForm.markAllAsTouched();
      return;
    }

    this.profileLoading = true;
    this.profileSuccess = null;
    this.profileError = null;

    this.profileService.updateProfile(this.profileForm.value).subscribe({
      next: (response) => {
        this.profileSuccess = response.message || 'Profile updated successfully';
        this.profileLoading = false;
        this.loadProfile(); // Reload profile
      },
      error: (err) => {
        this.profileError = err.message || 'Failed to update profile';
        this.profileLoading = false;
      }
    });
  }

  /**
   * Change password
   */
  changePassword(): void {
    if (this.passwordForm.invalid) {
      this.passwordForm.markAllAsTouched();
      return;
    }

    this.passwordLoading = true;
    this.passwordSuccess = null;
    this.passwordError = null;

    this.profileService.changePassword(this.passwordForm.value).subscribe({
      next: (response) => {
        this.passwordSuccess = response.message || 'Password changed successfully';
        this.passwordForm.reset();
        this.passwordLoading = false;
      },
      error: (err) => {
        this.passwordError = err.message || 'Failed to change password';
        this.passwordLoading = false;
      }
    });
  }

  /**
   * Handle file selection
   */
  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      const file = input.files[0];

      // Validate file type
      const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'];
      if (!allowedTypes.includes(file.type)) {
        this.pictureError = 'Invalid file type. Only JPG, PNG, and GIF files are allowed.';
        input.value = '';
        return;
      }

      // Validate file size (5MB)
      if (file.size > 5242880) {
        this.pictureError = 'File too large. Maximum file size is 5MB.';
        input.value = '';
        return;
      }

      this.selectedPictureFile = file;
      this.pictureError = null;

      // Create preview
      const reader = new FileReader();
      reader.onload = () => {
        this.picturePreviewUrl = reader.result as string;
      };
      reader.readAsDataURL(file);
    }
  }

  /**
   * Upload profile picture
   */
  uploadPicture(): void {
    if (!this.selectedPictureFile) {
      this.pictureError = 'Please select a file to upload';
      return;
    }

    this.pictureLoading = true;
    this.pictureSuccess = null;
    this.pictureError = null;

    this.profileService.uploadProfilePicture(this.selectedPictureFile).subscribe({
      next: (response) => {
        this.pictureSuccess = response.message || 'Profile picture uploaded successfully!';
        this.selectedPictureFile = null;
        this.picturePreviewUrl = null;
        this.pictureLoading = false;
        this.loadProfile(); // Reload profile to get new picture

        // Clear file input
        const fileInput = document.getElementById('profile_picture') as HTMLInputElement;
        if (fileInput) fileInput.value = '';
      },
      error: (err) => {
        this.pictureError = err.message || 'Failed to upload profile picture';
        this.pictureLoading = false;
      }
    });
  }

  /**
   * Remove profile picture
   */
  removePicture(): void {
    if (!confirm('Are you sure you want to remove your profile picture?')) {
      return;
    }

    this.pictureLoading = true;
    this.pictureSuccess = null;
    this.pictureError = null;

    this.profileService.removeProfilePicture().subscribe({
      next: (response) => {
        this.pictureSuccess = response.message || 'Profile picture removed successfully';
        this.pictureLoading = false;
        this.loadProfile(); // Reload profile
      },
      error: (err) => {
        this.pictureError = err.message || 'Failed to remove profile picture';
        this.pictureLoading = false;
      }
    });
  }

  /**
   * Get profile picture URL
   */
  getProfilePictureUrl(): string {
    if (this.picturePreviewUrl) {
      return this.picturePreviewUrl;
    }
    if (this.user?.profile_picture) {
      return `/assets/img/profiles/${this.user.profile_picture}?v=${new Date().getTime()}`;
    }
    return '';
  }

  /**
   * Custom validator to check if passwords match
   */
  private passwordMatchValidator(group: FormGroup): { [key: string]: boolean } | null {
    const newPassword = group.get('new_password')?.value;
    const confirmPassword = group.get('confirm_new_password')?.value;

    if (newPassword && confirmPassword && newPassword !== confirmPassword) {
      return { passwordMismatch: true };
    }
    return null;
  }

  /**
   * Get password error message
   */
  getPasswordErrorMessage(): string {
    const control = this.passwordForm.get('new_password');
    if (!control?.errors) return '';

    if (control.errors['required']) return 'Password is required';
    if (control.errors['minlength']) return 'Password must be at least 8 characters';
    if (control.errors['pattern']) {
      return 'Password must contain uppercase letter, number, and special character';
    }
    return '';
  }

  /**
   * Toggle password visibility
   */
  togglePasswordVisibility(field: 'current' | 'new' | 'confirm'): void {
    switch (field) {
      case 'current':
        this.showCurrentPassword = !this.showCurrentPassword;
        break;
      case 'new':
        this.showNewPassword = !this.showNewPassword;
        break;
      case 'confirm':
        this.showConfirmNewPassword = !this.showConfirmNewPassword;
        break;
    }
  }

  /**
   * Format date for display
   */
  formatDate(dateString: string | null): string {
    if (!dateString) return 'Never';
    const date = new Date(dateString);
    return date.toLocaleString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true
    });
  }
}

<div class="content-header">
  <h1>My Profile</h1>
  <p>Manage your personal information and account settings</p>
</div>

<!-- Loading State -->
<div *ngIf="loading" class="loading-container">Loading profile...</div>

<!-- Personal Information Section -->
<div *ngIf="!loading && user" class="section">
  <h2>Personal Information</h2>

  <div *ngIf="profileSuccess" class="alert alert-success">
    {{ profileSuccess }}
  </div>

  <div *ngIf="profileError" class="alert alert-error">
    {{ profileError }}
  </div>

  <form [formGroup]="profileForm" (ngSubmit)="updateProfile()" class="admin-form profile-form">
    <div class="form-group">
      <label for="full_name">Full Name *</label>
      <input type="text"
             id="full_name"
             formControlName="full_name"
             [class.error]="profileForm.get('full_name')?.invalid && profileForm.get('full_name')?.touched"
             maxlength="100">
      <div *ngIf="profileForm.get('full_name')?.invalid && profileForm.get('full_name')?.touched" class="error-message">
        <span *ngIf="profileForm.get('full_name')?.errors?.['required']">Full name is required</span>
      </div>
    </div>

    <div class="form-group">
      <label for="email">Email Address *</label>
      <input type="email"
             id="email"
             formControlName="email"
             [class.error]="profileForm.get('email')?.invalid && profileForm.get('email')?.touched"
             maxlength="100">
      <div *ngIf="profileForm.get('email')?.invalid && profileForm.get('email')?.touched" class="error-message">
        <span *ngIf="profileForm.get('email')?.errors?.['required']">Email is required</span>
        <span *ngIf="profileForm.get('email')?.errors?.['email']">Please enter a valid email address</span>
      </div>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary" [disabled]="profileLoading">
        {{ profileLoading ? 'Updating...' : 'Update Profile' }}
      </button>
    </div>
  </form>
</div>

<!-- Profile Picture Section -->
<div *ngIf="!loading && user" class="section">
  <h2>Profile Picture</h2>

  <div *ngIf="pictureSuccess" class="alert alert-success">
    {{ pictureSuccess }}
  </div>

  <div *ngIf="pictureError" class="alert alert-error">
    {{ pictureError }}
  </div>

  <form class="admin-form profile-form">
    <!-- Display Current Picture -->
    <div style="text-align: center; margin-bottom: 30px;">
      <img *ngIf="getProfilePictureUrl()"
           [src]="getProfilePictureUrl()"
           alt="Profile Picture"
           class="profile-picture-preview">
      <div *ngIf="!getProfilePictureUrl()" class="profile-placeholder">
        👤
      </div>
    </div>

    <div class="form-group">
      <label for="profile_picture">Choose New Picture</label>
      <input type="file"
             id="profile_picture"
             (change)="onFileSelected($event)"
             accept=".jpg,.jpeg,.png,.gif">
      <small>Maximum file size: 5MB. Allowed types: JPG, PNG, GIF</small>
    </div>

    <div class="form-actions" style="justify-content: center;">
      <button type="button"
              (click)="uploadPicture()"
              class="btn btn-primary"
              [disabled]="pictureLoading || !selectedPictureFile">
        {{ pictureLoading ? 'Uploading...' : 'Upload Picture' }}
      </button>
      <button *ngIf="user.profile_picture"
              type="button"
              (click)="removePicture()"
              class="btn btn-secondary"
              style="background: #dc3545; color: white;"
              [disabled]="pictureLoading">
        Remove Picture
      </button>
    </div>
  </form>
</div>

<!-- Change Password Section -->
<div *ngIf="!loading && user" class="section">
  <h2>Change Password</h2>

  <div *ngIf="passwordSuccess" class="alert alert-success">
    {{ passwordSuccess }}
  </div>

  <div *ngIf="passwordError" class="alert alert-error">
    {{ passwordError }}
  </div>

  <form [formGroup]="passwordForm" (ngSubmit)="changePassword()" class="admin-form profile-form">
    <div class="form-group">
      <label for="current_password">Current Password *</label>
      <div class="password-input-wrapper">
        <input [type]="showCurrentPassword ? 'text' : 'password'"
               id="current_password"
               formControlName="current_password"
               [class.error]="passwordForm.get('current_password')?.invalid && passwordForm.get('current_password')?.touched"
               autocomplete="current-password">
        <button type="button" class="password-toggle" (click)="togglePasswordVisibility('current')">
          <span class="toggle-icon">{{ showCurrentPassword ? '🙈' : '👁️' }}</span>
        </button>
      </div>
      <small>Enter your current password for security verification.</small>
    </div>

    <div class="form-group">
      <label for="new_password">New Password *</label>
      <div class="password-input-wrapper">
        <input [type]="showNewPassword ? 'text' : 'password'"
               id="new_password"
               formControlName="new_password"
               [class.error]="passwordForm.get('new_password')?.invalid && passwordForm.get('new_password')?.touched"
               autocomplete="new-password">
        <button type="button" class="password-toggle" (click)="togglePasswordVisibility('new')">
          <span class="toggle-icon">{{ showNewPassword ? '🙈' : '👁️' }}</span>
        </button>
      </div>
      <small>Must be at least 8 characters with one uppercase letter (A-Z), one number (0-9), and one special character (e.g., !@#$%^&*).</small>
      <div *ngIf="passwordForm.get('new_password')?.invalid && passwordForm.get('new_password')?.touched" class="error-message">
        {{ getPasswordErrorMessage() }}
      </div>
    </div>

    <div class="form-group">
      <label for="confirm_new_password">Confirm New Password *</label>
      <div class="password-input-wrapper">
        <input [type]="showConfirmNewPassword ? 'text' : 'password'"
               id="confirm_new_password"
               formControlName="confirm_new_password"
               [class.error]="passwordForm.get('confirm_new_password')?.invalid && passwordForm.get('confirm_new_password')?.touched"
               autocomplete="new-password">
        <button type="button" class="password-toggle" (click)="togglePasswordVisibility('confirm')">
          <span class="toggle-icon">{{ showConfirmNewPassword ? '🙈' : '👁️' }}</span>
        </button>
      </div>
      <div *ngIf="passwordForm.errors?.['passwordMismatch'] && passwordForm.get('confirm_new_password')?.touched" class="error-message">
        Passwords do not match
      </div>
    </div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary" [disabled]="passwordLoading">
        {{ passwordLoading ? 'Changing...' : 'Change Password' }}
      </button>
    </div>
  </form>
</div>

<!-- Account Information Section (Read-Only) -->
<div *ngIf="!loading && user" class="section">
  <h2>Account Information</h2>

  <div class="admin-form profile-form">
    <div class="info-row">
      <span class="info-label">Username:</span>
      <span class="info-value">{{ user.username }}</span>
    </div>

    <div class="info-row">
      <span class="info-label">Role:</span>
      <span class="info-value">
        <strong style="color: #2d3561;">{{ user.role_name }}</strong>
      </span>
    </div>

    <div class="info-row">
      <span class="info-label">Account Status:</span>
      <span class="info-value">
        <span *ngIf="user.is_active" class="badge badge-success">✓ Active</span>
        <span *ngIf="!user.is_active" class="badge badge-inactive">Inactive</span>
      </span>
    </div>

    <div class="info-row">
      <span class="info-label">Last Login:</span>
      <span class="info-value">{{ formatDate(user.last_login) }}</span>
    </div>

    <div class="info-row">
      <span class="info-label">Account Created:</span>
      <span class="info-value">{{ formatDate(user.created_at) }}</span>
    </div>

    <div class="info-row">
      <span class="info-label">Password Last Changed:</span>
      <span class="info-value">{{ formatDate(user.password_changed_at) }}</span>
    </div>
  </div>
</div>

// react-app-source/src/pages/admin/Profile.js
import React, { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { profileService } from '../../services/admin-api';

function Profile() {
  const { user, checkAuthStatus } = useAuth();

  const [loading, setLoading] = useState(true);
  const [profileData, setProfileData] = useState({
    email: '',
    full_name: ''
  });

  const [passwordData, setPasswordData] = useState({
    current_password: '',
    new_password: '',
    confirm_new_password: ''
  });

  // Success/error messages for each section
  const [profileSuccess, setProfileSuccess] = useState(null);
  const [profileError, setProfileError] = useState(null);
  const [passwordSuccess, setPasswordSuccess] = useState(null);
  const [passwordError, setPasswordError] = useState(null);
  const [pictureSuccess, setPictureSuccess] = useState(null);
  const [pictureError, setPictureError] = useState(null);

  // Loading states
  const [profileLoading, setProfileLoading] = useState(false);
  const [passwordLoading, setPasswordLoading] = useState(false);
  const [pictureLoading, setPictureLoading] = useState(false);

  // Profile picture
  const [selectedPictureFile, setSelectedPictureFile] = useState(null);
  const [picturePreviewUrl, setPicturePreviewUrl] = useState(null);
  const [imageLoadError, setImageLoadError] = useState(false);

  // Password visibility toggles
  const [showCurrentPassword, setShowCurrentPassword] = useState(false);
  const [showNewPassword, setShowNewPassword] = useState(false);
  const [showConfirmNewPassword, setShowConfirmNewPassword] = useState(false);

  // Password strength indicator
  const [passwordStrength, setPasswordStrength] = useState(0);
  const [passwordStrengthLabel, setPasswordStrengthLabel] = useState('');
  const [passwordStrengthColor, setPasswordStrengthColor] = useState('');

  useEffect(() => {
    loadProfile();
  }, []);

  useEffect(() => {
    calculatePasswordStrength(passwordData.new_password);
  }, [passwordData.new_password]);

  const loadProfile = async () => {
    setLoading(true);
    setImageLoadError(false);
    try {
      const response = await profileService.getProfile();
      if (response.success && response.data) {
        setProfileData({
          email: response.data.email || '',
          full_name: response.data.full_name || ''
        });
      }
      setLoading(false);
    } catch (err) {
      setProfileError(err.message || 'Failed to load profile');
      setLoading(false);
    }
  };

  const handleProfileChange = (e) => {
    const { name, value } = e.target;
    setProfileData(prev => ({ ...prev, [name]: value }));
  };

  const handlePasswordChange = (e) => {
    const { name, value } = e.target;
    setPasswordData(prev => ({ ...prev, [name]: value }));
  };

  const handleProfileSubmit = async (e) => {
    e.preventDefault();
    setProfileSuccess(null);
    setProfileError(null);

    if (!profileData.full_name.trim()) {
      setProfileError('Full name is required');
      return;
    }
    if (!profileData.email.trim()) {
      setProfileError('Email is required');
      return;
    }

    setProfileLoading(true);

    try {
      const response = await profileService.updateProfile(profileData);
      if (response.success) {
        setProfileSuccess(response.message || 'Profile updated successfully');
        checkAuthStatus();
        loadProfile();
      } else {
        setProfileError(response.message || 'Failed to update profile');
      }
      setProfileLoading(false);
    } catch (err) {
      setProfileError(err.message || 'Failed to update profile');
      setProfileLoading(false);
    }
  };

  const handlePasswordSubmit = async (e) => {
    e.preventDefault();
    setPasswordSuccess(null);
    setPasswordError(null);

    if (!passwordData.current_password) {
      setPasswordError('Current password is required');
      return;
    }
    if (!passwordData.new_password) {
      setPasswordError('New password is required');
      return;
    }
    if (passwordData.new_password.length < 8) {
      setPasswordError('Password must be at least 8 characters');
      return;
    }
    if (!/[A-Z]/.test(passwordData.new_password)) {
      setPasswordError('Password must contain at least one uppercase letter');
      return;
    }
    if (!/[0-9]/.test(passwordData.new_password)) {
      setPasswordError('Password must contain at least one number');
      return;
    }
    if (!/[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/.test(passwordData.new_password)) {
      setPasswordError('Password must contain at least one special character');
      return;
    }
    if (passwordData.new_password !== passwordData.confirm_new_password) {
      setPasswordError('Passwords do not match');
      return;
    }

    setPasswordLoading(true);

    try {
      const response = await profileService.changePassword({
        current_password: passwordData.current_password,
        new_password: passwordData.new_password
      });
      if (response.success) {
        setPasswordSuccess(response.message || 'Password changed successfully');
        setPasswordData({
          current_password: '',
          new_password: '',
          confirm_new_password: ''
        });
      } else {
        setPasswordError(response.message || 'Failed to change password');
      }
      setPasswordLoading(false);
    } catch (err) {
      setPasswordError(err.message || 'Failed to change password');
      setPasswordLoading(false);
    }
  };

  const onFileSelected = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    // Validate file type
    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'];
    if (!allowedTypes.includes(file.type)) {
      setPictureError('Invalid file type. Only JPG, PNG, and GIF files are allowed.');
      e.target.value = '';
      return;
    }

    // Validate file size (5MB)
    if (file.size > 5242880) {
      setPictureError('File too large. Maximum file size is 5MB.');
      e.target.value = '';
      return;
    }

    setSelectedPictureFile(file);
    setPictureError(null);

    // Create preview
    const reader = new FileReader();
    reader.onload = () => {
      setPicturePreviewUrl(reader.result);
    };
    reader.readAsDataURL(file);
  };

  const uploadPicture = async () => {
    if (!selectedPictureFile) {
      setPictureError('Please select a file to upload');
      return;
    }

    setPictureLoading(true);
    setPictureSuccess(null);
    setPictureError(null);

    try {
      const formData = new FormData();
      formData.append('profile_picture', selectedPictureFile);

      const response = await profileService.uploadProfilePicture(formData);
      if (response.success) {
        setPictureSuccess(response.message || 'Profile picture uploaded successfully!');
        setSelectedPictureFile(null);
        setPicturePreviewUrl(null);
        loadProfile();
        checkAuthStatus();

        // Clear file input
        const fileInput = document.getElementById('profile_picture');
        if (fileInput) fileInput.value = '';
      } else {
        setPictureError(response.message || 'Failed to upload profile picture');
      }
      setPictureLoading(false);
    } catch (err) {
      setPictureError(err.message || 'Failed to upload profile picture');
      setPictureLoading(false);
    }
  };

  const removePicture = async () => {
    if (!window.confirm('Are you sure you want to remove your profile picture?')) {
      return;
    }

    setPictureLoading(true);
    setPictureSuccess(null);
    setPictureError(null);

    try {
      const response = await profileService.removeProfilePicture();
      if (response.success) {
        setPictureSuccess(response.message || 'Profile picture removed successfully');
        loadProfile();
        checkAuthStatus();
      } else {
        setPictureError(response.message || 'Failed to remove profile picture');
      }
      setPictureLoading(false);
    } catch (err) {
      setPictureError(err.message || 'Failed to remove profile picture');
      setPictureLoading(false);
    }
  };

  const getProfilePictureUrl = () => {
    if (imageLoadError) return '';
    if (picturePreviewUrl) return picturePreviewUrl;
    if (user?.profile_picture) {
      return `/assets/img/profiles/${user.profile_picture}?v=${Date.now()}`;
    }
    return '';
  };

  const onImageError = () => {
    setImageLoadError(true);
  };

  const togglePasswordVisibility = (field) => {
    switch (field) {
      case 'current':
        setShowCurrentPassword(!showCurrentPassword);
        break;
      case 'new':
        setShowNewPassword(!showNewPassword);
        break;
      case 'confirm':
        setShowConfirmNewPassword(!showConfirmNewPassword);
        break;
      default:
        break;
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'Never';
    const date = new Date(dateString);
    return date.toLocaleString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true
    });
  };

  const calculatePasswordStrength = (password) => {
    if (!password) {
      setPasswordStrength(0);
      setPasswordStrengthLabel('');
      setPasswordStrengthColor('');
      return;
    }

    let strength = 0;

    // Length checks
    if (password.length >= 8) strength += 20;
    if (password.length >= 12) strength += 10;
    if (password.length >= 16) strength += 10;

    // Character type checks
    if (/[a-z]/.test(password)) strength += 10;
    if (/[A-Z]/.test(password)) strength += 15;
    if (/[0-9]/.test(password)) strength += 15;
    if (/[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/.test(password)) strength += 20;

    // Bonus for variety
    const types = [/[a-z]/, /[A-Z]/, /[0-9]/, /[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/];
    const typeCount = types.filter(regex => regex.test(password)).length;
    if (typeCount >= 4) strength += 10;

    // Cap at 100
    const finalStrength = Math.min(strength, 100);
    setPasswordStrength(finalStrength);

    // Set label and color based on strength
    if (finalStrength < 20) {
      setPasswordStrengthLabel('Weak');
      setPasswordStrengthColor('#dc3545');
    } else if (finalStrength < 40) {
      setPasswordStrengthLabel('Fair');
      setPasswordStrengthColor('#fd7e14');
    } else if (finalStrength < 60) {
      setPasswordStrengthLabel('Medium');
      setPasswordStrengthColor('#ffc107');
    } else if (finalStrength < 80) {
      setPasswordStrengthLabel('Good');
      setPasswordStrengthColor('#90EE90');
    } else {
      setPasswordStrengthLabel('Strong');
      setPasswordStrengthColor('#28a745');
    }
  };

  if (loading) {
    return (
      <>
        <div className="content-header">
          <h1>My Profile</h1>
          <p>Manage your personal information and account settings</p>
        </div>
        <div className="loading-container">Loading profile...</div>
      </>
    );
  }

  return (
    <>
      <div className="content-header">
        <h1>My Profile</h1>
        <p>Manage your personal information and account settings</p>
      </div>

      {/* Personal Information Section */}
      <div className="section">
        <h2>Personal Information</h2>

        {profileSuccess && <div className="alert alert-success">{profileSuccess}</div>}
        {profileError && <div className="alert alert-error">{profileError}</div>}

        <form className="admin-form profile-form" onSubmit={handleProfileSubmit}>
          <div className="form-group">
            <label htmlFor="full_name">Full Name *</label>
            <input
              type="text"
              id="full_name"
              name="full_name"
              value={profileData.full_name}
              onChange={handleProfileChange}
              maxLength={100}
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email Address *</label>
            <input
              type="email"
              id="email"
              name="email"
              value={profileData.email}
              onChange={handleProfileChange}
              maxLength={100}
            />
          </div>

          <div className="form-actions">
            <button type="submit" className="btn btn-primary" disabled={profileLoading}>
              {profileLoading ? 'Updating...' : 'Update Profile'}
            </button>
          </div>
        </form>
      </div>

      {/* Profile Picture Section */}
      <div className="section">
        <h2>Profile Picture</h2>

        {pictureSuccess && <div className="alert alert-success">{pictureSuccess}</div>}
        {pictureError && <div className="alert alert-error">{pictureError}</div>}

        <div className="admin-form profile-form">
          {/* Display Current Picture */}
          <div style={{ textAlign: 'center', marginBottom: '30px' }}>
            {getProfilePictureUrl() ? (
              <img
                src={getProfilePictureUrl()}
                alt="Profile Picture"
                className="profile-picture-preview"
                onError={onImageError}
              />
            ) : (
              <div className="profile-placeholder">👤</div>
            )}
          </div>

          <div className="form-group">
            <label htmlFor="profile_picture">Choose New Picture</label>
            <input
              type="file"
              id="profile_picture"
              onChange={onFileSelected}
              accept=".jpg,.jpeg,.png,.gif"
            />
            <small>Maximum file size: 5MB. Allowed types: JPG, PNG, GIF</small>
          </div>

          <div className="form-actions" style={{ justifyContent: 'center' }}>
            <button
              type="button"
              onClick={uploadPicture}
              className="btn btn-primary"
              disabled={pictureLoading || !selectedPictureFile}
            >
              {pictureLoading ? 'Uploading...' : 'Upload Picture'}
            </button>
            {user?.profile_picture && (
              <button
                type="button"
                onClick={removePicture}
                className="btn btn-secondary"
                style={{ background: '#dc3545', color: 'white' }}
                disabled={pictureLoading}
              >
                Remove Picture
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Change Password Section */}
      <div className="section">
        <h2>Change Password</h2>

        {passwordSuccess && <div className="alert alert-success">{passwordSuccess}</div>}
        {passwordError && <div className="alert alert-error">{passwordError}</div>}

        <form className="admin-form profile-form" onSubmit={handlePasswordSubmit}>
          <div className="form-group">
            <label htmlFor="current_password">Current Password *</label>
            <div className="password-input-wrapper">
              <input
                type={showCurrentPassword ? 'text' : 'password'}
                id="current_password"
                name="current_password"
                value={passwordData.current_password}
                onChange={handlePasswordChange}
                autoComplete="current-password"
              />
              <button type="button" className="password-toggle" onClick={() => togglePasswordVisibility('current')}>
                <span className="toggle-icon">{showCurrentPassword ? '🙈' : '👁️'}</span>
              </button>
            </div>
            <small>Enter your current password for security verification.</small>
          </div>

          <div className="form-group">
            <label htmlFor="new_password">New Password *</label>
            <div className="password-input-wrapper">
              <input
                type={showNewPassword ? 'text' : 'password'}
                id="new_password"
                name="new_password"
                value={passwordData.new_password}
                onChange={handlePasswordChange}
                autoComplete="new-password"
              />
              <button type="button" className="password-toggle" onClick={() => togglePasswordVisibility('new')}>
                <span className="toggle-icon">{showNewPassword ? '🙈' : '👁️'}</span>
              </button>
            </div>
            {/* Password Strength Indicator */}
            {passwordStrength > 0 && (
              <div className="password-strength" style={{ marginTop: '8px' }}>
                <div className="strength-bar-container" style={{ width: '100%', height: '6px', background: '#e0e0e0', borderRadius: '3px', overflow: 'hidden' }}>
                  <div className="strength-bar" style={{ width: `${passwordStrength}%`, background: passwordStrengthColor, height: '100%', transition: 'width 0.3s ease, background 0.3s ease' }}></div>
                </div>
                <span className="strength-label" style={{ color: passwordStrengthColor, fontSize: '12px', fontWeight: '600', marginTop: '4px', display: 'inline-block' }}>{passwordStrengthLabel}</span>
              </div>
            )}
            <small>Must be at least 8 characters with one uppercase letter (A-Z), one number (0-9), and one special character (e.g., !@#$%^&*).</small>
          </div>

          <div className="form-group">
            <label htmlFor="confirm_new_password">Confirm New Password *</label>
            <div className="password-input-wrapper">
              <input
                type={showConfirmNewPassword ? 'text' : 'password'}
                id="confirm_new_password"
                name="confirm_new_password"
                value={passwordData.confirm_new_password}
                onChange={handlePasswordChange}
                autoComplete="new-password"
              />
              <button type="button" className="password-toggle" onClick={() => togglePasswordVisibility('confirm')}>
                <span className="toggle-icon">{showConfirmNewPassword ? '🙈' : '👁️'}</span>
              </button>
            </div>
          </div>

          <div className="form-actions">
            <button type="submit" className="btn btn-primary" disabled={passwordLoading}>
              {passwordLoading ? 'Changing...' : 'Change Password'}
            </button>
          </div>
        </form>
      </div>

      {/* Account Information Section (Read-Only) */}
      <div className="section">
        <h2>Account Information</h2>

        <div className="admin-form profile-form">
          <div className="info-row">
            <span className="info-label">Username:</span>
            <span className="info-value">{user?.username}</span>
          </div>

          <div className="info-row">
            <span className="info-label">Role:</span>
            <span className="info-value">
              <strong style={{ color: '#2d3561' }}>{user?.role_name || (user?.role_id === 1 ? 'Admin' : 'Content Manager')}</strong>
            </span>
          </div>

          <div className="info-row">
            <span className="info-label">Account Status:</span>
            <span className="info-value">
              {user?.is_active ? (
                <span className="badge badge-success">✓ Active</span>
              ) : (
                <span className="badge badge-inactive">Inactive</span>
              )}
            </span>
          </div>

          <div className="info-row">
            <span className="info-label">Last Login:</span>
            <span className="info-value">{formatDate(user?.last_login)}</span>
          </div>

          <div className="info-row">
            <span className="info-label">Account Created:</span>
            <span className="info-value">{formatDate(user?.created_at)}</span>
          </div>

          <div className="info-row">
            <span className="info-label">Password Last Changed:</span>
            <span className="info-value">{formatDate(user?.password_changed_at)}</span>
          </div>
        </div>
      </div>
    </>
  );
}

export default Profile;
