// Front_End/angular-app-source/src/app/admin/users/user-form/user-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { UsersService } from '../../services/users.service';
import { User, Role, CreateUserRequest, UpdateUserRequest } from '../../models/user.model';

@Component({
  selector: 'app-user-form',
  standalone: false,
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.css']
})
export class UserFormComponent implements OnInit {
  userId: number | null = null;
  isEditMode = false;
  user: User | null = null;
  roles: Role[] = [];
  loading = false;
  error: string | null = null;
  tempPassword: string | null = null;
  successMessage: string | null = null;

  // Form fields
  username = '';
  password = '';
  confirmPassword = '';
  fullName = '';
  email = '';
  roleId = 0;
  isActive = true;

  // Edit mode only
  changePassword = false;
  newPassword = '';
  confirmNewPassword = '';

  // Password visibility toggles
  showPassword = false;
  showConfirmPassword = false;
  showNewPassword = false;
  showConfirmNewPassword = false;

  // Password strength indicators (for create mode)
  passwordStrength = 0;
  passwordStrengthLabel = '';
  passwordStrengthColor = '';

  // Password strength indicators (for edit mode)
  newPasswordStrength = 0;
  newPasswordStrengthLabel = '';
  newPasswordStrengthColor = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private usersService: UsersService
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.userId = parseInt(id, 10);
      this.isEditMode = true;
      this.loadUser();
    }
    this.loadRoles();
  }

  loadUser(): void {
    if (!this.userId) return;

    this.loading = true;
    this.usersService.getById(this.userId).subscribe({
      next: (user) => {
        this.user = user;
        this.username = user.username;
        this.fullName = user.full_name;
        this.email = user.email;
        this.roleId = user.role_id;
        this.isActive = user.is_active;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load user';
        this.loading = false;
        console.error(err);
      }
    });
  }

  loadRoles(): void {
    this.usersService.getRoles().subscribe({
      next: (roles) => {
        this.roles = roles;
        if (!this.isEditMode && roles.length > 0) {
          this.roleId = roles[0].id;
        }
      },
      error: (err) => {
        console.error('Error loading roles:', err);
      }
    });
  }

  togglePasswordVisibility(field: string): void {
    const passwordField = document.getElementById(field) as HTMLInputElement;
    if (!passwordField) return;

    switch (field) {
      case 'password':
        this.showPassword = !this.showPassword;
        break;
      case 'confirmPassword':
        this.showConfirmPassword = !this.showConfirmPassword;
        break;
      case 'newPassword':
        this.showNewPassword = !this.showNewPassword;
        break;
      case 'confirmNewPassword':
        this.showConfirmNewPassword = !this.showConfirmNewPassword;
        break;
    }

    passwordField.type = passwordField.type === 'password' ? 'text' : 'password';
  }

  onChangePasswordToggle(): void {
    if (!this.changePassword) {
      this.newPassword = '';
      this.confirmNewPassword = '';
    }
  }

  onSubmit(): void {
    this.error = null;

    // Validation
    if (!this.fullName || !this.email || !this.roleId) {
      this.error = 'Please fill in all required fields';
      return;
    }

    if (!this.isEditMode) {
      // Add mode - validate password
      if (!this.username || !this.password) {
        this.error = 'Username and password are required';
        return;
      }

      // Validate username - no spaces allowed
      if (/\s/.test(this.username)) {
        this.error = 'Username cannot contain spaces';
        return;
      }

      if (this.password.length < 8) {
        this.error = 'Password must be at least 8 characters long';
        return;
      }

      if (!/[A-Z]/.test(this.password)) {
        this.error = 'Password must contain at least one uppercase letter (A-Z)';
        return;
      }

      if (!/[0-9]/.test(this.password)) {
        this.error = 'Password must contain at least one number (0-9)';
        return;
      }

      if (!/[^a-zA-Z0-9]/.test(this.password)) {
        this.error = 'Password must contain at least one special character (e.g., !@#$%^&*)';
        return;
      }

      if (this.password !== this.confirmPassword) {
        this.error = 'Passwords do not match';
        return;
      }

      this.createUser();
    } else {
      // Edit mode - validate password if changing
      if (this.changePassword) {
        if (!this.newPassword) {
          this.error = 'New password is required when "Change Password" is checked';
          return;
        }

        if (this.newPassword.length < 8) {
          this.error = 'Password must be at least 8 characters long';
          return;
        }

        if (!/[A-Z]/.test(this.newPassword)) {
          this.error = 'Password must contain at least one uppercase letter (A-Z)';
          return;
        }

        if (!/[0-9]/.test(this.newPassword)) {
          this.error = 'Password must contain at least one number (0-9)';
          return;
        }

        if (!/[^a-zA-Z0-9]/.test(this.newPassword)) {
          this.error = 'Password must contain at least one special character (e.g., !@#$%^&*)';
          return;
        }

        if (this.newPassword !== this.confirmNewPassword) {
          this.error = 'Passwords do not match';
          return;
        }
      }

      this.updateUser();
    }
  }

  createUser(): void {
    const newUser: CreateUserRequest = {
      username: this.username,
      password: this.password,
      full_name: this.fullName,
      email: this.email,
      role_id: this.roleId,
      is_active: this.isActive
    };

    this.loading = true;
    this.usersService.create(newUser).subscribe({
      next: () => {
        this.tempPassword = this.password;
        this.successMessage = 'User created successfully!';
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message || 'Failed to create user';
        this.loading = false;
      }
    });
  }

  updateUser(): void {
    if (!this.userId) return;

    const updatedUser: any = {
      id: this.userId,
      full_name: this.fullName,
      email: this.email,
      role_id: this.roleId,
      is_active: this.isActive
    };

    // Add password if changing
    if (this.changePassword && this.newPassword) {
      updatedUser.password = this.newPassword;
    }

    this.loading = true;
    this.usersService.update(updatedUser).subscribe({
      next: () => {
        this.successMessage = 'User updated successfully';
        this.changePassword = false;
        this.newPassword = '';
        this.confirmNewPassword = '';
        this.loadUser(); // Reload user data
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message || 'Failed to update user';
        this.loading = false;
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/admin/users']);
  }

  addAnotherUser(): void {
    // Reset form for new user
    this.successMessage = null;
    this.tempPassword = null;
    this.error = null;
    this.username = '';
    this.password = '';
    this.confirmPassword = '';
    this.fullName = '';
    this.email = '';
    this.isActive = true;
    // Keep the selected role
  }

  onPasswordChange(): void {
    this.calculatePasswordStrength(this.password, 'create');
  }

  onNewPasswordChange(): void {
    this.calculatePasswordStrength(this.newPassword, 'edit');
  }

  hasSpaces(value: string): boolean {
    return /\s/.test(value);
  }

  calculatePasswordStrength(password: string, mode: 'create' | 'edit'): void {
    if (!password) {
      if (mode === 'create') {
        this.passwordStrength = 0;
        this.passwordStrengthLabel = '';
        this.passwordStrengthColor = '';
      } else {
        this.newPasswordStrength = 0;
        this.newPasswordStrengthLabel = '';
        this.newPasswordStrengthColor = '';
      }
      return;
    }

    let strength = 0;

    // Length checks
    if (password.length >= 8) strength += 20;
    if (password.length >= 12) strength += 10;
    if (password.length >= 16) strength += 10;

    // Character type checks
    if (/[a-z]/.test(password)) strength += 10;
    if (/[A-Z]/.test(password)) strength += 15;
    if (/[0-9]/.test(password)) strength += 15;
    if (/[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(password)) strength += 20;

    // Bonus for variety
    const types = [/[a-z]/, /[A-Z]/, /[0-9]/, /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/];
    const typeCount = types.filter(regex => regex.test(password)).length;
    if (typeCount >= 4) strength += 10;

    // Cap at 100
    strength = Math.min(strength, 100);

    // Set label and color based on strength
    let label = '';
    let color = '';

    if (strength < 20) {
      label = 'Weak';
      color = '#dc3545'; // Red
    } else if (strength < 40) {
      label = 'Fair';
      color = '#fd7e14'; // Orange
    } else if (strength < 60) {
      label = 'Medium';
      color = '#ffc107'; // Yellow
    } else if (strength < 80) {
      label = 'Good';
      color = '#90EE90'; // Light Green
    } else {
      label = 'Strong';
      color = '#28a745'; // Dark Green
    }

    if (mode === 'create') {
      this.passwordStrength = strength;
      this.passwordStrengthLabel = label;
      this.passwordStrengthColor = color;
    } else {
      this.newPasswordStrength = strength;
      this.newPasswordStrengthLabel = label;
      this.newPasswordStrengthColor = color;
    }
  }
}

<div class="content-header">
  <h1>{{ isEditMode ? 'Edit User' : 'Add New User' }}</h1>
  <p class="section-subtitle">{{ isEditMode ? 'Update user account details' : 'Create a new admin user account' }}</p>
</div>

<div class="action-bar">
  <button class="btn btn-secondary" (click)="cancel()">
    ← Back to User Management
  </button>
</div>

<div class="section">
  <!-- Success Message with Temp Password -->
  <div *ngIf="successMessage" class="success-container">
    <div class="alert alert-success">
      <strong>✓ {{ successMessage }}</strong>
    </div>

    <div *ngIf="tempPassword" class="temp-password-box">
      <strong class="temp-password-label">Temporary Password:</strong>
      <code class="temp-password-code">{{ tempPassword }}</code>
      <p class="temp-password-warning">
        ⚠️ <strong>Important:</strong> Share this password securely with the user.
        They will be required to change it upon first login.
      </p>
    </div>

    <div class="success-actions">
      <button type="button" class="btn btn-primary" (click)="addAnotherUser()">Add Another User</button>
    </div>
  </div>

  <!-- Error Message -->
  <div *ngIf="error" class="alert alert-error">{{ error }}</div>

  <!-- User Form -->
  <form *ngIf="!successMessage" (ngSubmit)="onSubmit()" class="admin-form">
    <!-- Username (Add Mode Only) -->
    <div class="form-group" *ngIf="!isEditMode">
      <label for="username">Username *</label>
      <input type="text" id="username" [(ngModel)]="username" name="username" required maxlength="50" autocomplete="off">
      <small>Username for logging into the admin panel. Must be unique.</small>
    </div>

    <!-- Username (Edit Mode - Read Only) -->
    <div class="form-group" *ngIf="isEditMode">
      <label>Username</label>
      <input type="text" [value]="username" readonly style="background-color: #f5f7fa; cursor: not-allowed;">
      <small>Username cannot be changed.</small>
    </div>

    <!-- Password (Add Mode Only) -->
    <div class="form-group" *ngIf="!isEditMode">
      <label for="password">Password *</label>
      <div class="password-input-wrapper">
        <input type="password" id="password" [(ngModel)]="password" name="password" required minlength="8" autocomplete="new-password">
        <button type="button" class="password-toggle" (click)="togglePasswordVisibility('password')" aria-label="Toggle password visibility">
          <span class="toggle-icon">{{ showPassword ? '🙈' : '👁️' }}</span>
        </button>
      </div>
      <small>Must be at least 8 characters with one uppercase letter (A-Z), one number (0-9), and one special character (e.g., !@#$%^&*). User will be required to change this on first login.</small>
    </div>

    <!-- Confirm Password (Add Mode Only) -->
    <div class="form-group" *ngIf="!isEditMode">
      <label for="confirmPassword">Confirm Password *</label>
      <div class="password-input-wrapper">
        <input type="password" id="confirmPassword" [(ngModel)]="confirmPassword" name="confirmPassword" required minlength="8" autocomplete="new-password">
        <button type="button" class="password-toggle" (click)="togglePasswordVisibility('confirmPassword')" aria-label="Toggle password visibility">
          <span class="toggle-icon">{{ showConfirmPassword ? '🙈' : '👁️' }}</span>
        </button>
      </div>
      <small>Re-enter the password to confirm.</small>
    </div>

    <!-- Full Name -->
    <div class="form-group">
      <label for="fullName">Full Name *</label>
      <input type="text" id="fullName" [(ngModel)]="fullName" name="fullName" required maxlength="100">
      <small>User's full name (displayed in admin panel).</small>
    </div>

    <!-- Email -->
    <div class="form-group">
      <label for="email">Email Address *</label>
      <input type="email" id="email" [(ngModel)]="email" name="email" required maxlength="100">
      <small>Valid email address for notifications and password reset.</small>
    </div>

    <!-- Role -->
    <div class="form-group">
      <label for="roleId">Role *</label>
      <select id="roleId" [(ngModel)]="roleId" name="roleId" required>
        <option [value]="0" disabled>-- Select Role --</option>
        <option *ngFor="let role of roles" [value]="role.id">{{ role.role_name }}</option>
      </select>
      <small>
        <strong>Admin:</strong> Full access including user management. |
        <strong>Content Manager:</strong> Can manage all content sections.
      </small>
    </div>

    <!-- Active Status -->
    <div class="form-group">
      <label class="checkbox-label">
        <input type="checkbox" [(ngModel)]="isActive" name="isActive">
        Active
      </label>
      <small>If checked, user can log in immediately. Uncheck to create inactive user.</small>
    </div>

    <!-- Password Change Section (Edit Mode Only) -->
    <div *ngIf="isEditMode" style="margin: 30px 0; padding: 20px; background: #f5f7fa; border-radius: 8px;">
      <div class="form-group">
        <label class="checkbox-label">
          <input type="checkbox" id="changePasswordCheck" [(ngModel)]="changePassword" name="changePassword" (change)="onChangePasswordToggle()">
          Change Password
        </label>
        <small>Check this box if you want to reset the user's password.</small>
      </div>

      <div *ngIf="changePassword">
        <div class="form-group">
          <label for="newPassword">New Password</label>
          <div class="password-input-wrapper">
            <input type="password" id="newPassword" [(ngModel)]="newPassword" name="newPassword" minlength="8" [required]="changePassword" autocomplete="new-password">
            <button type="button" class="password-toggle" (click)="togglePasswordVisibility('newPassword')" aria-label="Toggle password visibility">
              <span class="toggle-icon">{{ showNewPassword ? '🙈' : '👁️' }}</span>
            </button>
          </div>
          <small>Must be at least 8 characters with one uppercase letter (A-Z), one number (0-9), and one special character (e.g., !@#$%^&*). User will NOT be required to change this password.</small>
        </div>

        <div class="form-group">
          <label for="confirmNewPassword">Confirm New Password</label>
          <div class="password-input-wrapper">
            <input type="password" id="confirmNewPassword" [(ngModel)]="confirmNewPassword" name="confirmNewPassword" minlength="8" [required]="changePassword" autocomplete="new-password">
            <button type="button" class="password-toggle" (click)="togglePasswordVisibility('confirmNewPassword')" aria-label="Toggle password visibility">
              <span class="toggle-icon">{{ showConfirmNewPassword ? '🙈' : '👁️' }}</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Read-Only Information (Edit Mode Only) -->
    <div *ngIf="isEditMode && user" style="margin: 30px 0; padding: 20px; background: #f5f7fa; border-radius: 8px;">
      <h3 style="margin-bottom: 15px; color: #2d3561;">Account Information</h3>

      <div class="info-row">
        <span class="info-label">Last Login:</span>
        <span class="info-value">
          <span *ngIf="user.last_login">{{ user.last_login }}</span>
          <span *ngIf="!user.last_login">Never logged in</span>
        </span>
      </div>

      <div class="info-row">
        <span class="info-label">Account Created:</span>
        <span class="info-value">{{ user.created_at }}</span>
      </div>
    </div>

    <!-- Form Actions -->
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" [disabled]="loading">
        {{ loading ? (isEditMode ? 'Updating...' : 'Creating...') : (isEditMode ? 'Update User' : 'Create User') }}
      </button>
      <a routerLink="/admin/users" class="btn btn-secondary">Cancel</a>
      <a *ngIf="isEditMode && userId" [routerLink]="['/admin/users/delete', userId]" class="btn btn-danger btn-delete-right">Delete User</a>
    </div>
  </form>
</div>

// react-app-source/src/pages/admin/UserForm.js
import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { usersService } from '../../services/admin-api';

function UserForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEditMode = !!id;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [roles, setRoles] = useState([]);
  const [user, setUser] = useState(null);

  // Username validation
  const [usernameCheckInProgress, setUsernameCheckInProgress] = useState(false);
  const [usernameAvailable, setUsernameAvailable] = useState(null);

  // Password change (edit mode)
  const [changePassword, setChangePassword] = useState(false);
  const [newPassword, setNewPassword] = useState('');
  const [confirmNewPassword, setConfirmNewPassword] = useState('');
  const [showNewPassword, setShowNewPassword] = useState(false);
  const [showConfirmNewPassword, setShowConfirmNewPassword] = useState(false);

  const [formData, setFormData] = useState({
    username: '',
    email: '',
    full_name: '',
    role_id: 2,
    is_active: true
  });

  useEffect(() => {
    loadRoles();
    if (isEditMode) {
      loadUser();
    }
  }, [id]);

  // Debounced username check
  useEffect(() => {
    if (!isEditMode && formData.username && !hasSpaces(formData.username)) {
      const timer = setTimeout(() => {
        checkUsernameAvailability(formData.username);
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [formData.username, isEditMode]);

  const loadRoles = async () => {
    try {
      const response = await usersService.getRoles();
      setRoles(response.data || [
        { id: 1, role_name: 'Admin' },
        { id: 2, role_name: 'Content Manager' }
      ]);
    } catch (err) {
      console.error('Error loading roles:', err);
      setRoles([
        { id: 1, role_name: 'Admin' },
        { id: 2, role_name: 'Content Manager' }
      ]);
    }
  };

  const loadUser = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await usersService.getById(id);
      const data = response.data;
      setUser(data);
      setFormData({
        username: data.username || '',
        email: data.email || '',
        full_name: data.full_name || '',
        role_id: data.role_id || 2,
        is_active: data.is_active || false
      });
      setLoading(false);
    } catch (err) {
      setError('Failed to load user');
      setLoading(false);
      console.error('Error loading user:', err);
    }
  };

  const checkUsernameAvailability = async (username) => {
    if (!username || hasSpaces(username)) {
      setUsernameAvailable(null);
      return;
    }

    setUsernameCheckInProgress(true);
    try {
      const response = await usersService.checkUsername(username);
      setUsernameAvailable(response.data?.available || false);
    } catch (err) {
      console.error('Error checking username:', err);
      setUsernameAvailable(null);
    }
    setUsernameCheckInProgress(false);
  };

  const hasSpaces = (str) => /\s/.test(str);

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : (name === 'role_id' ? parseInt(value) : value)
    }));

    // Reset username availability when typing
    if (name === 'username') {
      setUsernameAvailable(null);
    }
  };

  const getPasswordStrength = (password) => {
    let strength = 0;
    if (password.length >= 8) strength += 25;
    if (/[a-z]/.test(password)) strength += 25;
    if (/[A-Z]/.test(password)) strength += 25;
    if (/[0-9]/.test(password)) strength += 12.5;
    if (/[^a-zA-Z0-9]/.test(password)) strength += 12.5;
    return Math.min(strength, 100);
  };

  const getPasswordStrengthLabel = (strength) => {
    if (strength < 25) return 'Weak';
    if (strength < 50) return 'Fair';
    if (strength < 75) return 'Good';
    return 'Strong';
  };

  const getPasswordStrengthColor = (strength) => {
    if (strength < 25) return '#dc3545';
    if (strength < 50) return '#ffc107';
    if (strength < 75) return '#17a2b8';
    return '#28a745';
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.username.trim()) {
      setError('Username is required');
      return;
    }
    if (hasSpaces(formData.username)) {
      setError('Username cannot contain spaces');
      return;
    }
    if (!isEditMode && usernameAvailable === false) {
      setError('Username is already taken');
      return;
    }
    if (!formData.email.trim()) {
      setError('Email is required');
      return;
    }
    if (!formData.full_name.trim()) {
      setError('Full name is required');
      return;
    }

    // Password validation for edit mode
    if (isEditMode && changePassword) {
      if (newPassword.length < 8) {
        setError('Password must be at least 8 characters');
        return;
      }
      if (newPassword !== confirmNewPassword) {
        setError('Passwords do not match');
        return;
      }
    }

    setLoading(true);
    setError(null);

    try {
      const submitData = { ...formData };
      if (isEditMode && changePassword && newPassword) {
        submitData.password = newPassword;
      }

      if (isEditMode) {
        await usersService.update(id, submitData);
      } else {
        await usersService.create(submitData);
      }
      navigate('/admin/users');
    } catch (err) {
      setError(err.message || 'Failed to save user');
      setLoading(false);
      console.error('Error saving user:', err);
    }
  };

  const cancel = () => {
    navigate('/admin/users');
  };

  const passwordStrength = getPasswordStrength(newPassword);

  return (
    <>
      <div className="content-header">
        <h1>{isEditMode ? 'Edit User' : 'Add New User'}</h1>
        <p className="section-subtitle">
          {isEditMode ? 'Update user account details' : 'Create a new admin user account'}
        </p>
      </div>

      <div className="action-bar">
        <button className="btn btn-secondary" onClick={cancel}>
          ← Back to User Management
        </button>
      </div>

      <div className="section">
        {error && <div className="alert alert-error">{error}</div>}

        {loading && !formData.username && isEditMode && (
          <div className="loading-container">
            <div className="spinner"></div>
            <p>Loading user...</p>
          </div>
        )}

        {(!loading || formData.username || !isEditMode) && (
          <form className="admin-form" onSubmit={handleSubmit}>
            {/* Username (Add Mode) */}
            {!isEditMode && (
              <div className="form-group">
                <label htmlFor="username">Username *</label>
                <div style={{ position: 'relative' }}>
                  <input
                    type="text"
                    id="username"
                    name="username"
                    value={formData.username}
                    onChange={handleInputChange}
                    maxLength="50"
                    autoComplete="off"
                    required
                    className={hasSpaces(formData.username) ? 'error' : ''}
                    style={{ paddingRight: '40px' }}
                  />
                  {/* Username availability indicator */}
                  <span style={{ position: 'absolute', right: '12px', top: '50%', transform: 'translateY(-50%)', fontSize: '18px' }}>
                    {usernameCheckInProgress && <span>⏳</span>}
                    {!usernameCheckInProgress && usernameAvailable === true && <span style={{ color: '#28a745' }}>✓</span>}
                    {!usernameCheckInProgress && usernameAvailable === false && <span style={{ color: '#dc3545' }}>✗</span>}
                  </span>
                </div>
                <small>Username for logging into the admin panel. Must be unique and cannot contain spaces.</small>
                {formData.username && hasSpaces(formData.username) && (
                  <div style={{ color: '#dc3545', marginTop: '5px' }}>
                    ⚠ Username cannot contain spaces
                  </div>
                )}
                {!usernameCheckInProgress && usernameAvailable === true && (
                  <div style={{ color: '#28a745', marginTop: '5px', fontSize: '0.9em' }}>
                    ✓ Username is available
                  </div>
                )}
                {!usernameCheckInProgress && usernameAvailable === false && formData.username && !hasSpaces(formData.username) && (
                  <div style={{ color: '#dc3545', marginTop: '5px', fontSize: '0.9em' }}>
                    ✗ Username is already taken
                  </div>
                )}
              </div>
            )}

            {/* Username (Edit Mode - Read Only) */}
            {isEditMode && (
              <div className="form-group">
                <label>Username</label>
                <input
                  type="text"
                  value={formData.username}
                  readOnly
                  style={{ backgroundColor: '#f5f7fa', cursor: 'not-allowed' }}
                />
                <small>Username cannot be changed.</small>
              </div>
            )}

            {/* Password Notice (Add Mode Only) */}
            {!isEditMode && (
              <div className="info-box info-box-primary">
                <p style={{ margin: 0, fontWeight: 'bold' }}>
                  Automatic Password Generation
                </p>
                <p style={{ margin: '8px 0 0 0' }}>
                  A secure password will be automatically generated for this user.
                  An activation email will be sent to the user's email address where they can set their own password.
                </p>
              </div>
            )}

            {/* Full Name */}
            <div className="form-group">
              <label htmlFor="full_name">Full Name *</label>
              <input
                type="text"
                id="full_name"
                name="full_name"
                value={formData.full_name}
                onChange={handleInputChange}
                maxLength="100"
                required
              />
              <small>User's full name (displayed in admin panel).</small>
            </div>

            {/* Email */}
            <div className="form-group">
              <label htmlFor="email">Email Address *</label>
              <input
                type="email"
                id="email"
                name="email"
                value={formData.email}
                onChange={handleInputChange}
                maxLength="100"
                required
              />
              <small>Valid email address for notifications and password reset.</small>
            </div>

            {/* Role */}
            <div className="form-group">
              <label htmlFor="role_id">Role *</label>
              <select
                id="role_id"
                name="role_id"
                value={formData.role_id}
                onChange={handleInputChange}
                required
              >
                <option value={0} disabled>-- Select Role --</option>
                {roles.map(role => (
                  <option key={role.id} value={role.id}>{role.role_name || role.name}</option>
                ))}
              </select>
              <small>
                <strong>Admin:</strong> Full access including user management. | <strong>Content Manager:</strong> Can manage all content sections.
              </small>
            </div>

            {/* Active Status */}
            <div className="form-group">
              <label className="checkbox-label">
                <input
                  type="checkbox"
                  name="is_active"
                  checked={formData.is_active}
                  onChange={handleInputChange}
                />
                <span>Active</span>
              </label>
              <small>If checked, user can log in immediately. Uncheck to create inactive user.</small>
            </div>

            {/* Password Change Section (Edit Mode Only) */}
            {isEditMode && (
              <div className="form-section-box">
                <div className="form-group">
                  <label className="checkbox-label">
                    <input
                      type="checkbox"
                      checked={changePassword}
                      onChange={(e) => {
                        setChangePassword(e.target.checked);
                        if (!e.target.checked) {
                          setNewPassword('');
                          setConfirmNewPassword('');
                        }
                      }}
                    />
                    <span>Change Password</span>
                  </label>
                  <small>Check this box if you want to reset the user's password.</small>
                </div>

                {changePassword && (
                  <>
                    <div className="form-group">
                      <label htmlFor="newPassword">New Password</label>
                      <div className="password-input-wrapper">
                        <input
                          type={showNewPassword ? 'text' : 'password'}
                          id="newPassword"
                          value={newPassword}
                          onChange={(e) => setNewPassword(e.target.value)}
                          minLength="8"
                          required={changePassword}
                          autoComplete="new-password"
                        />
                        <button
                          type="button"
                          className="password-toggle"
                          onClick={() => setShowNewPassword(!showNewPassword)}
                        >
                          {showNewPassword ? '🙈' : '👁️'}
                        </button>
                      </div>
                      {/* Password Strength Indicator */}
                      {newPassword && (
                        <div style={{ marginTop: '8px' }}>
                          <div style={{ width: '100%', height: '6px', background: '#e0e0e0', borderRadius: '3px', overflow: 'hidden' }}>
                            <div style={{
                              width: `${passwordStrength}%`,
                              height: '100%',
                              background: getPasswordStrengthColor(passwordStrength),
                              transition: 'width 0.3s ease, background 0.3s ease'
                            }} />
                          </div>
                          <span style={{ fontSize: '12px', fontWeight: '600', color: getPasswordStrengthColor(passwordStrength), marginTop: '4px', display: 'inline-block' }}>
                            {getPasswordStrengthLabel(passwordStrength)}
                          </span>
                        </div>
                      )}
                      <small>Must be at least 8 characters with one uppercase letter (A-Z), one number (0-9), and one special character.</small>
                    </div>

                    <div className="form-group">
                      <label htmlFor="confirmNewPassword">Confirm New Password</label>
                      <div className="password-input-wrapper">
                        <input
                          type={showConfirmNewPassword ? 'text' : 'password'}
                          id="confirmNewPassword"
                          value={confirmNewPassword}
                          onChange={(e) => setConfirmNewPassword(e.target.value)}
                          minLength="8"
                          required={changePassword}
                          autoComplete="new-password"
                        />
                        <button
                          type="button"
                          className="password-toggle"
                          onClick={() => setShowConfirmNewPassword(!showConfirmNewPassword)}
                        >
                          {showConfirmNewPassword ? '🙈' : '👁️'}
                        </button>
                      </div>
                      {confirmNewPassword && newPassword !== confirmNewPassword && (
                        <div style={{ color: '#dc3545', marginTop: '5px', fontSize: '0.9em' }}>
                          ✗ Passwords do not match
                        </div>
                      )}
                    </div>
                  </>
                )}
              </div>
            )}

            {/* Account Information (Edit Mode Only) */}
            {isEditMode && user && (
              <div className="form-section-box">
                <h3 style={{ marginBottom: '15px', color: '#2d3561' }}>Account Information</h3>

                <div className="info-row">
                  <span className="info-label">Last Login:</span>
                  <span className="info-value">
                    {user.last_login || 'Never logged in'}
                  </span>
                </div>

                <div className="info-row">
                  <span className="info-label">Account Created:</span>
                  <span className="info-value">{user.created_at}</span>
                </div>
              </div>
            )}

            {/* Form Actions */}
            <div className="form-actions">
              <button type="submit" className="btn btn-primary" disabled={loading}>
                {loading ? (isEditMode ? 'Updating...' : 'Creating...') : (isEditMode ? 'Update User' : 'Create User')}
              </button>
              <Link to="/admin/users" className="btn btn-secondary">Cancel</Link>
              {isEditMode && id && (
                <Link to={`/admin/users/delete/${id}`} className="btn btn-danger" style={{ marginLeft: 'auto' }}>
                  Delete User
                </Link>
              )}
            </div>
          </form>
        )}
      </div>
    </>
  );
}

export default UserForm;
