// angular-app-source/src/app/admin/guards/auth.guard.ts
import { Injectable } from '@angular/core';
import { Router, CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { AuthService } from '../services/auth.service';
import { Observable, of } from 'rxjs';
import { map, take, filter } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class AuthGuard implements CanActivate {

  constructor(
    private router: Router,
    private authService: AuthService
  ) {}

  canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean> {
    // Wait for the initial auth check to complete before making a decision
    // This prevents the race condition where the guard runs before checkAuthStatus() finishes
    return this.authService.authCheckComplete$.pipe(
      // Wait until auth check is complete
      filter(isComplete => isComplete),
      // Take only the first 'complete' emission
      take(1),
      // Now check the current user status
      map(() => {
        const user = this.authService.getCurrentUser();

        // Check if user is authenticated (user exists and is not null)
        if (user) {
          // Check if user must change password
          if (user.must_change_password) {
            // Allow access to change-password page
            if (state.url === '/admin/change-password') {
              return true;
            }
            // Redirect to change-password for any other page
            this.router.navigate(['/admin/change-password']);
            return false;
          }
          // User is authenticated and doesn't need to change password
          return true;
        }

        // Not authenticated, redirect to login with return URL
        this.router.navigate(['/admin/login'], {
          queryParams: { returnUrl: state.url }
        });
        return false;
      })
    );
  }
}

// react-app-source/src/guards/AuthGuard.js
import React from 'react';
import { Navigate, useLocation } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

/**
 * AuthGuard - Protects routes that require authentication
 * Redirects to login if not authenticated
 * Redirects to change-password if user must change password
 */
function AuthGuard({ children }) {
  const { user, loading, authCheckComplete } = useAuth();
  const location = useLocation();

  // Wait for auth check to complete before making a decision
  if (loading || !authCheckComplete) {
    return (
      <div className="loading-container">
        <div className="spinner"></div>
        <p>Loading...</p>
      </div>
    );
  }

  // Check if user is authenticated
  if (!user) {
    // Not authenticated, redirect to login with return URL
    return <Navigate to="/admin/login" state={{ returnUrl: location.pathname }} replace />;
  }

  // Check if user must change password
  if (user.must_change_password) {
    // Allow access to change-password page
    if (location.pathname === '/admin/change-password') {
      return children;
    }
    // Redirect to change-password for any other page
    return <Navigate to="/admin/change-password" replace />;
  }

  // User is authenticated and doesn't need to change password
  return children;
}

export default AuthGuard;
