// react-app-source/src/pages/admin/FormForm.js
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { formsService } from '../../services/admin-api';

function FormForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEditMode = !!id;

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const [formData, setFormData] = useState({
    form_name: '',
    form_description: '',
    embed_code: '',
    page_location: 'Workshops',
    is_active: false
  });

  useEffect(() => {
    if (isEditMode) {
      loadForm();
    }
  }, [id]);

  const loadForm = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await formsService.getById(id);
      const data = response.data;
      setFormData({
        form_name: data.form_name || '',
        form_description: data.form_description || '',
        embed_code: data.embed_code || '',
        page_location: data.page_location || 'Workshops',
        is_active: data.is_active || false
      });
      setLoading(false);
    } catch (err) {
      setError('Failed to load form');
      setLoading(false);
      console.error('Error loading form:', err);
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.form_name.trim()) {
      setError('Form name is required');
      return;
    }
    if (!formData.embed_code.trim()) {
      setError('Embed code is required');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      if (isEditMode) {
        await formsService.update(id, formData);
      } else {
        await formsService.create(formData);
      }
      navigate('/admin/forms');
    } catch (err) {
      setError(err.message || 'Failed to save form');
      setLoading(false);
      console.error('Error saving form:', err);
    }
  };

  const cancel = () => {
    navigate('/admin/forms');
  };

  return (
    <>
      <div className="content-header">
        <h1>{isEditMode ? 'Edit Form' : 'Add New Form'}</h1>
        <p className="section-subtitle">
          {isEditMode ? 'Update form details' : 'Add a new Google Form embed'}
        </p>
      </div>

      <div className="action-bar">
        <button className="btn btn-secondary" onClick={cancel}>
          ← Back to Forms
        </button>
      </div>

      {error && (
        <div className="alert alert-error">{error}</div>
      )}

      {loading && !formData.form_name && (
        <div className="loading-container">
          <div className="spinner"></div>
          <p>Loading form...</p>
        </div>
      )}

      {(!loading || formData.form_name) && (
        <form className="admin-form" onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="form_name">Form Name <span className="required">*</span></label>
            <input
              type="text"
              id="form_name"
              name="form_name"
              className="form-control"
              value={formData.form_name}
              onChange={handleInputChange}
              placeholder="Enter form name"
              maxLength="255"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="form_description">Description</label>
            <textarea
              id="form_description"
              name="form_description"
              className="form-control"
              value={formData.form_description}
              onChange={handleInputChange}
              placeholder="Enter form description (optional)"
              rows="3"
            ></textarea>
          </div>

          <div className="form-group">
            <label htmlFor="page_location">Form Location <span className="required">*</span></label>
            <select
              id="page_location"
              name="page_location"
              className="form-control"
              value={formData.page_location}
              onChange={handleInputChange}
            >
              <option value="Workshops">Workshops Page</option>
              <option value="Registration">Registration Page</option>
            </select>
            <small className="form-help">Where this form will be displayed</small>
          </div>

          <div className="form-group">
            <label htmlFor="embed_code">Embed Code <span className="required">*</span></label>
            <textarea
              id="embed_code"
              name="embed_code"
              className="form-control"
              value={formData.embed_code}
              onChange={handleInputChange}
              placeholder="Paste Google Form embed code here"
              rows="8"
              required
            ></textarea>
            <small className="form-help">Copy the iframe embed code from Google Forms</small>
          </div>

          <div className="form-group">
            <label className="checkbox-label">
              <input
                type="checkbox"
                name="is_active"
                checked={formData.is_active}
                onChange={handleInputChange}
              />
              <span>Active (visible on website)</span>
            </label>
          </div>

          <div className="form-actions">
            <button type="submit" className="btn btn-primary" disabled={loading}>
              {loading ? 'Saving...' : (isEditMode ? 'Update Form' : 'Create Form')}
            </button>
            <button type="button" className="btn btn-secondary" onClick={cancel} disabled={loading}>
              Cancel
            </button>
          </div>
        </form>
      )}
    </>
  );
}

export default FormForm;

// Front_End/angular-app/src/app/admin/forms/form-form/form-form.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-form-form',
  standalone: false,
  templateUrl: './form-form.component.html',
  styleUrls: ['./form-form.component.css']
})
export class FormFormComponent {

}

<!-- Content Header -->
<div class="content-header">
  <h1>{{ isEditMode ? 'Edit Form' : 'Add New Form' }}</h1>
  <p class="section-subtitle">{{ isEditMode ? 'Update form details' : 'Create a new Google Form for ' + currentLocation.toLowerCase() }}</p>
</div>

<!-- Back Button -->
<div class="action-bar">
  <button class="btn btn-secondary" (click)="cancel()">
    ← Back to Forms
  </button>
</div>

<!-- Error Message -->
<div class="alert alert-error" *ngIf="error">
  {{ error }}
</div>

<!-- Loading State -->
<div class="loading-container" *ngIf="loading && !formData.form_name">
  <div class="spinner"></div>
  <p>Loading form...</p>
</div>

<!-- Form -->
<form class="admin-form" (ngSubmit)="onSubmit()" *ngIf="!loading || formData.form_name">
  <!-- Form Name -->
  <div class="form-group">
    <label for="form_name">Form Name <span class="required">*</span></label>
    <input
      type="text"
      id="form_name"
      name="form_name"
      class="form-control"
      [(ngModel)]="formData.form_name"
      placeholder="e.g., Workshop Application"
      maxlength="255"
      required
    />
    <small class="form-help">This name will be displayed on the website</small>
  </div>

  <!-- Form Description -->
  <div class="form-group">
    <label for="form_description">Description</label>
    <textarea
      id="form_description"
      name="form_description"
      class="form-control"
      [(ngModel)]="formData.form_description"
      placeholder="Brief description of this form"
      rows="3"
    ></textarea>
    <small class="form-help">Optional description shown below the form name</small>
  </div>

  <!-- Google Form Embed Code -->
  <div class="form-group">
    <label for="embed_code">Google Form Embed Code <span class="required">*</span></label>
    <textarea
      id="embed_code"
      name="embed_code"
      class="form-control"
      [(ngModel)]="formData.embed_code"
      placeholder='<iframe src="https://docs.google.com/forms/d/e/..." width="640" height="800" frameborder="0"></iframe>'
      rows="5"
      required
    ></textarea>
    <small class="form-help">Paste the complete iframe embed code from Google Forms</small>
  </div>

  <!-- Page Location -->
  <div class="form-group">
    <label for="page_location">Page Location <span class="required">*</span></label>
    <select
      id="page_location"
      name="page_location"
      class="form-control"
      [(ngModel)]="formData.page_location"
      required
    >
      <option value="Workshops">Workshops</option>
      <option value="Registration">Registration</option>
    </select>
    <small class="form-help">Where should this form appear on the website?</small>
  </div>

  <!-- Is Active Checkbox -->
  <div class="form-group">
    <label class="checkbox-label">
      <input
        type="checkbox"
        name="is_active"
        [(ngModel)]="formData.is_active"
      />
      <span>Active (visible on website)</span>
    </label>
  </div>

  <!-- Form Actions -->
  <div class="form-actions">
    <button
      type="submit"
      class="btn btn-primary"
      [disabled]="loading"
    >
      {{ loading ? 'Saving...' : (isEditMode ? 'Update Form' : 'Create Form') }}
    </button>

    <button
      type="button"
      class="btn btn-secondary"
      (click)="cancel()"
      [disabled]="loading"
    >
      Cancel
    </button>
  </div>
</form>
