// react-app-source/src/components/admin/AdminHeader.js
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';

function AdminHeader({ onToggleMobileMenu }) {
  const { user, logout } = useAuth();
  const [imageLoadError, setImageLoadError] = useState(false);
  const [profilePictureUrl, setProfilePictureUrl] = useState('');

  useEffect(() => {
    setImageLoadError(false);
    updateProfilePictureUrl();
  }, [user]);

  const updateProfilePictureUrl = () => {
    if (imageLoadError || !user?.profile_picture) {
      setProfilePictureUrl('');
    } else {
      setProfilePictureUrl(`/assets/img/profiles/${user.profile_picture}?v=${Date.now()}`);
    }
  };

  const onImageError = () => {
    setImageLoadError(true);
    setProfilePictureUrl('');
  };

  const handleLogout = () => {
    logout();
  };

  return (
    <header className="admin-header">
      {/* Mobile Hamburger Menu Button */}
      <button className="hamburger-menu" onClick={onToggleMobileMenu}>
        <span>☰</span>
      </button>

      {/* Header Right Section */}
      <div className="header-right">
        {/* Profile Link with Avatar and Settings Icon */}
        <Link to="/admin/profile" className="header-profile-link" title="Profile & Settings">
          {/* Profile Avatar (Dynamic) */}
          {profilePictureUrl ? (
            <img
              src={profilePictureUrl}
              alt="Profile"
              onError={onImageError}
              className="header-avatar-img"
            />
          ) : (
            <span className="header-avatar">👤</span>
          )}
          {/* Settings Gear Icon */}
          <span className="header-settings-icon">⚙️</span>
        </Link>

        {/* Logout Button */}
        <button onClick={handleLogout} className="header-logout-link" title="Logout">
          <span>🚪</span>
        </button>
      </div>
    </header>
  );
}

export default AdminHeader;

// angular-app-source/src/app/admin/layout/admin-header/admin-header.component.ts
import { Component, EventEmitter, Output, OnInit } from '@angular/core';
import { AuthService, AdminUser } from '../../services/auth.service';

@Component({
  selector: 'app-admin-header',
  standalone: false,
  templateUrl: './admin-header.component.html',
  styleUrls: ['./admin-header.component.css']
})
export class AdminHeaderComponent implements OnInit {
  @Output() toggleMobileMenu = new EventEmitter<void>();
  currentUser: AdminUser | null = null;
  imageLoadError = false;
  profilePictureUrl = ''; // Cache the profile picture URL to prevent infinite loading

  constructor(private authService: AuthService) {}

  ngOnInit(): void {
    this.authService.currentUser$.subscribe(user => {
      this.currentUser = user;
      this.imageLoadError = false; // Reset error flag when user changes
      // Update profile picture URL when user changes (prevents infinite loading)
      this.updateProfilePictureUrl();
    });
  }

  toggleMenu(): void {
    this.toggleMobileMenu.emit();
  }

  logout(): void {
    this.authService.logout().subscribe();
  }

  /**
   * Update profile picture URL - called only when user changes
   * This prevents infinite loading by not generating new URLs on every change detection cycle
   */
  updateProfilePictureUrl(): void {
    if (this.imageLoadError || !this.currentUser?.profile_picture) {
      this.profilePictureUrl = '';
    } else {
      // Add timestamp only once when user changes, not on every template check
      this.profilePictureUrl = `/assets/img/profiles/${this.currentUser.profile_picture}?v=${Date.now()}`;
    }
  }

  getProfilePictureUrl(): string {
    return this.profilePictureUrl;
  }

  onImageError(): void {
    this.imageLoadError = true;
    this.profilePictureUrl = ''; // Clear URL on error
  }
}

<header class="admin-header">
  <!-- Mobile Hamburger Menu Button -->
  <button class="hamburger-menu" (click)="toggleMenu()">
    <span>☰</span>
  </button>

  <!-- Header Right Section -->
  <div class="header-right">
    <!-- Profile Link with Avatar and Settings Icon -->
    <a routerLink="/admin/profile" class="header-profile-link" title="Profile & Settings">
      <!-- Profile Avatar (Dynamic) -->
      <img *ngIf="getProfilePictureUrl()"
           [src]="getProfilePictureUrl()"
           alt="Profile"
           (error)="onImageError()"
           class="header-avatar-img">
      <span *ngIf="!getProfilePictureUrl()" class="header-avatar">👤</span>
      <!-- Settings Gear Icon -->
      <span class="header-settings-icon">⚙️</span>
    </a>

    <!-- Logout Button -->
    <a (click)="logout()" class="header-logout-link" title="Logout">
      <span>🚪</span>
    </a>
  </div>
</header>
