// Front_End/angular-app/src/app/components/about/about.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Subscription } from 'rxjs';
import { AudioService } from '../../services/audio.service';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('heroVideoDesktop', { static: false }) heroVideoDesktop!: ElementRef<HTMLVideoElement>;
  @ViewChild('heroVideoMobile', { static: false }) heroVideoMobile!: ElementRef<HTMLVideoElement>;

  private subscriptions: Subscription[] = [];

  constructor(private audioService: AudioService) {}

  ngOnInit(): void {
    this.setupAudioSubscription();
  }

  ngAfterViewInit(): void {
    // Initial video control based on current audio state
    this.controlVideoPlayback(this.audioService.isPlaying());
  }

  ngOnDestroy(): void {
    // Unsubscribe from all subscriptions
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  /**
   * Set up subscription to audio service to control video playback
   */
  private setupAudioSubscription(): void {
    // Subscribe to playing state only (mute state doesn't affect video)
    const playingSub = this.audioService.isPlaying$.subscribe(playing => {
      this.controlVideoPlayback(playing);
    });

    this.subscriptions.push(playingSub);
  }

  /**
   * Control hero video playback
   */
  private controlVideoPlayback(shouldPlay: boolean): void {
    if (this.heroVideoDesktop && this.heroVideoDesktop.nativeElement) {
      if (shouldPlay) {
        this.heroVideoDesktop.nativeElement.play().catch(err => {
          console.log('Video autoplay prevented:', err);
        });
      } else {
        this.heroVideoDesktop.nativeElement.pause();
      }
    }

    if (this.heroVideoMobile && this.heroVideoMobile.nativeElement) {
      if (shouldPlay) {
        this.heroVideoMobile.nativeElement.play().catch(err => {
          console.log('Video autoplay prevented:', err);
        });
      } else {
        this.heroVideoMobile.nativeElement.pause();
      }
    }
  }
}

<!-- Hero Section -->
<section class="page-hero">
    <!-- Video Background - Desktop -->
    <video #heroVideoDesktop id="aboutVideo" class="hero-video hero-video-desktop" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <!-- Video Background - Mobile -->
    <video #heroVideoMobile id="aboutVideoMobile" class="hero-video hero-video-mobile" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <div class="container">
        <h1 class="hero-title" id="aboutTitle">About PASC Region J</h1>
        <p class="hero-subtitle" id="aboutSubtitle">Celebrating Leadership Since 1932</p>
        <p class="hero-subtitle" style="margin-top: 10px; font-size: 1rem; color: #FFB300;">&nbsp;</p>
    </div>
</section>

<!-- Who We Are Section -->
<section class="about-intro">
    <div class="container">
        <div class="about-grid">
            <div class="about-text">
                <h2>Who We Are</h2>
                <p>PASC Region J represents Districts 11 and 12, proudly serving student councils across <strong>Philadelphia, Delaware, Bucks, Montgomery, and Chester Counties</strong>.</p>

                <p>Since 1932, the Pennsylvania Association of Student Councils has been dedicated to developing, engaging, and celebrating leaders across our state. PASC helps students improve their lives while learning to lead through service, collaboration, and participation.</p>

                <p>Our region is part of a statewide network that empowers and equips students to develop and strengthen their leadership skills through conferences, events, recognition programs, and networking opportunities.</p>

            </div>
            <div class="about-logo">
                <img #largeLogo src="/assets/img/logo.png" alt="PASC Region J Logo" class="large-logo" [class.rotating]="isPlaying">
            </div>
        </div>
    </div>
</section>

<!-- Mission & Vision Section -->
<section class="mission-vision">
    <div class="container">
        <div class="mission-vision-grid">
            <div class="mission-box">
                <h2>Mission</h2>
                <p>The Pennsylvania Association of Student Councils develops and elevates leaders by providing opportunities, training, networking, civic engagement, recognition, and resources necessary for students and advisors to engage in their schools, communities, and world.</p>
            </div>
            <div class="vision-box">
                <h2>Vision</h2>
                <p>The Pennsylvania Association of Student Councils envisions leaders being inspired, confident, and empowered to use their voices and put their skills into action for good in their schools, communities, and world.</p>
            </div>
        </div>
    </div>
</section>

<!-- What We Do Section with Photos -->
<section class="what-we-do">
    <div class="container">
        <h2 class="section-title">What We Do</h2>
        <p class="section-intro">PASC Region J provides year-round opportunities for students and advisors to develop and apply leadership skills in order to improve themselves, their schools, and their communities.</p>

        <div class="activities-grid">
            <!-- Card 1: Conferences & Events -->
            <div class="activity-card">
                <img src="/assets/img/gallery/f2.jpg" alt="Students holding PASC sign">
                <h3>Conferences & Events</h3>
                <p>We host regional conferences that bring together student leaders from across Districts 11 and 12. Our annual conference features inspiring keynote speakers, interactive workshops, and networking opportunities.</p>
            </div>

            <!-- Card 2: Leadership Development -->
            <div class="activity-card">
                <img src="/assets/img/gallery/f3.jpg" alt="Students at registration">
                <h3>Leadership Development</h3>
                <p>Through workshops, training sessions, and hands-on activities, we help students develop essential leadership skills including communication, collaboration, problem-solving, and civic engagement.</p>
            </div>

            <!-- Card 3: Networking & Connection -->
            <div class="activity-card">
                <img src="/assets/img/gallery/f1.jpg" alt="Students collaborating">
                <h3>Networking & Connection</h3>
                <p>Connect with fellow student leaders, share ideas, and build lasting relationships. Our events provide forums and opportunities for students and advisors to collaborate and learn from one another.</p>
            </div>
        </div>
    </div>
</section>

<!-- Why Join Section -->
<section class="why-join">
    <div class="container">
        <h2 class="section-title">About PASC Region J</h2>


        <div class="section-intro">
            <p>PASC Region J serves student councils across <strong>Districts 11 and 12</strong>, covering Philadelphia, Delaware, Bucks, Montgomery, and Chester Counties in southeastern Pennsylvania. Each year, a different school within our region has the honor of hosting the annual Regional Leadership Conference.</p>

            <p>As a member school in Region J, your student council automatically has access to all the benefits and opportunities below:</p>
        </div>

        <div class="benefits-grid">
            <div class="benefit-item">
                <div class="benefit-icon">🎯</div>
                <h3>Leadership Training</h3>
                <p>Access to state-of-the-art leadership programs, conferences, and workshops designed to develop your skills.</p>
            </div>

            <div class="benefit-item">
                <div class="benefit-icon">🤝</div>
                <h3>Networking Opportunities</h3>
                <p>Connect with student leaders from across the region and build relationships that last beyond high school.</p>
            </div>

            <div class="benefit-item">
                <div class="benefit-icon">🏆</div>
                <h3>Recognition & Awards</h3>
                <p>Eligibility for PASC awards, scholarships, and recognition programs celebrating your leadership achievements.</p>
            </div>

            <div class="benefit-item">
                <div class="benefit-icon">📚</div>
                <h3>Resources & Support</h3>
                <p>Access to advisors, training materials, best practices, and guidance from regional and state officers.</p>
            </div>

            <div class="benefit-item">
                <div class="benefit-icon">🎤</div>
                <h3>Leadership Positions</h3>
                <p>Opportunities to run for regional and state leadership positions, developing your skills at the highest level.</p>
            </div>

            <div class="benefit-item">
                <div class="benefit-icon">🌟</div>
                <h3>Make a Difference</h3>
                <p>Use your voice to create positive change in your school, community, and beyond through service and advocacy.</p>
            </div>
        </div>
    </div>
</section>

<!-- CTA Section -->
<section class="cta-section">
    <div class="container">
        <h2>Ready to Reach for the Stars, Lead Beyond Limits?</h2>
        <p>Join us for an inspiring day of leadership, workshops, and networking!</p>
        <div class="cta-buttons">
            <a routerLink="/workshops" class="btn btn-primary">View Workshops</a>
            <a routerLink="/gallery" class="btn btn-secondary">View Gallery</a>
        </div>
    </div>
</section>

// react-app-source/src/pages/About.js
import React, { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { useAudio } from '../contexts/AudioContext';
import Header from '../components/shared/Header';
import Footer from '../components/shared/Footer';

function About() {
  const { isPlaying } = useAudio();
  const heroVideoDesktopRef = useRef(null);
  const heroVideoMobileRef = useRef(null);

  useEffect(() => {
    const desktopVideo = heroVideoDesktopRef.current;
    const mobileVideo = heroVideoMobileRef.current;

    if (desktopVideo) {
      desktopVideo.muted = true;
      desktopVideo.volume = 0;
      if (isPlaying) {
        desktopVideo.play().catch(err => console.log('Video autoplay prevented:', err));
      } else {
        desktopVideo.pause();
      }
    }

    if (mobileVideo) {
      mobileVideo.muted = true;
      mobileVideo.volume = 0;
      if (isPlaying) {
        mobileVideo.play().catch(err => console.log('Video autoplay prevented:', err));
      } else {
        mobileVideo.pause();
      }
    }
  }, [isPlaying]);

  return (
    <>
      <Header />

      {/* Hero Section */}
      <section className="page-hero">
        <video ref={heroVideoDesktopRef} id="aboutVideo" className="hero-video hero-video-desktop" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>
        <video ref={heroVideoMobileRef} id="aboutVideoMobile" className="hero-video hero-video-mobile" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>

        <div className="container">
          <h1 className="hero-title" id="aboutTitle">About PASC Region J</h1>
          <p className="hero-subtitle" id="aboutSubtitle">Celebrating Leadership Since 1932</p>
        </div>
      </section>

      {/* Who We Are Section */}
      <section className="about-intro">
        <div className="container">
          <div className="about-grid">
            <div className="about-text">
              <h2>Who We Are</h2>
              <p>PASC Region J represents Districts 11 and 12, proudly serving student councils across <strong>Philadelphia, Delaware, Bucks, Montgomery, and Chester Counties</strong>.</p>

              <p>Since 1932, the Pennsylvania Association of Student Councils has been dedicated to developing, engaging, and celebrating leaders across our state. PASC helps students improve their lives while learning to lead through service, collaboration, and participation.</p>

              <p>Our region is part of a statewide network that empowers and equips students to develop and strengthen their leadership skills through conferences, events, recognition programs, and networking opportunities.</p>
            </div>
            <div className="about-logo">
              <img src="/assets/img/logo.png" alt="PASC Region J Logo" className={`large-logo ${isPlaying ? 'rotating' : ''}`} />
            </div>
          </div>
        </div>
      </section>

      {/* Mission & Vision Section */}
      <section className="mission-vision">
        <div className="container">
          <div className="mission-vision-grid">
            <div className="mission-box">
              <h2>Mission</h2>
              <p>The Pennsylvania Association of Student Councils develops and elevates leaders by providing opportunities, training, networking, civic engagement, recognition, and resources necessary for students and advisors to engage in their schools, communities, and world.</p>
            </div>
            <div className="vision-box">
              <h2>Vision</h2>
              <p>The Pennsylvania Association of Student Councils envisions leaders being inspired, confident, and empowered to use their voices and put their skills into action for good in their schools, communities, and world.</p>
            </div>
          </div>
        </div>
      </section>

      {/* What We Do Section */}
      <section className="what-we-do">
        <div className="container">
          <h2 className="section-title">What We Do</h2>
          <p className="section-intro">PASC Region J provides year-round opportunities for students and advisors to develop and apply leadership skills in order to improve themselves, their schools, and their communities.</p>

          <div className="activities-grid">
            <div className="activity-card">
              <img src="/assets/img/gallery/f2.jpg" alt="Students holding PASC sign" />
              <h3>Conferences & Events</h3>
              <p>We host regional conferences that bring together student leaders from across Districts 11 and 12. Our annual conference features inspiring keynote speakers, interactive workshops, and networking opportunities.</p>
            </div>

            <div className="activity-card">
              <img src="/assets/img/gallery/f3.jpg" alt="Students at registration" />
              <h3>Leadership Development</h3>
              <p>Through workshops, training sessions, and hands-on activities, we help students develop essential leadership skills including communication, collaboration, problem-solving, and civic engagement.</p>
            </div>

            <div className="activity-card">
              <img src="/assets/img/gallery/f1.jpg" alt="Students collaborating" />
              <h3>Networking & Connection</h3>
              <p>Connect with fellow student leaders, share ideas, and build lasting relationships. Our events provide forums and opportunities for students and advisors to collaborate and learn from one another.</p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <div className="container">
          <h2>Ready to Reach for the Stars, Lead Beyond Limits?</h2>
          <p>Join us for an inspiring day of leadership, workshops, and networking!</p>
          <div className="cta-buttons">
            <Link to="/workshops" className="btn btn-primary">View Workshops</Link>
            <Link to="/gallery" className="btn btn-secondary">View Gallery</Link>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}

export default About;
