// Front_End/angular-app/src/app/components/gallery/gallery.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, AfterViewInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { AudioService } from '../../services/audio.service';
import { GalleryImage } from '../../models/api-models';

@Component({
  selector: 'app-gallery',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './gallery.component.html',
  styleUrl: './gallery.component.css'
})
export class GalleryComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('heroVideoDesktop', { static: false }) heroVideoDesktop!: ElementRef<HTMLVideoElement>;
  @ViewChild('heroVideoMobile', { static: false }) heroVideoMobile!: ElementRef<HTMLVideoElement>;

  private apiService = inject(ApiService);
  private audioService = inject(AudioService);

  images = signal<GalleryImage[]>([]);
  totalImages = signal(0);
  currentPage = signal(1);
  imagesPerPage = 9;
  loading = signal(true);
  error = signal<string | null>(null);

  // Modal
  modalOpen = signal(false);
  modalIndex = signal(0);

  private subscriptions: Subscription[] = [];

  ngOnInit() {
    this.loadGalleryCount();
    this.loadGalleryImages();
    this.setupAudioSubscription();
  }

  ngAfterViewInit(): void {
    this.controlVideoPlayback(this.audioService.isPlaying());
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  private setupAudioSubscription(): void {
    const playingSub = this.audioService.isPlaying$.subscribe(playing => {
      this.controlVideoPlayback(playing);
    });
    this.subscriptions.push(playingSub);
  }

  private controlVideoPlayback(shouldPlay: boolean): void {
    [this.heroVideoDesktop, this.heroVideoMobile].forEach(videoRef => {
      if (videoRef && videoRef.nativeElement) {
        if (shouldPlay) {
          videoRef.nativeElement.play().catch(() => {});
        } else {
          videoRef.nativeElement.pause();
        }
      }
    });
  }

  private loadGalleryCount() {
    this.apiService.getGalleryCount('gallery').subscribe({
      next: (response) => {
        if (response.success) {
          this.totalImages.set(response.totalCount);
        }
      },
      error: (err) => {
        console.error('Error loading gallery count:', err);
      }
    });
  }

  private loadGalleryImages() {
    this.loading.set(true);
    this.apiService.getGalleryImages('gallery', this.currentPage(), this.imagesPerPage).subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.images.set(response.data);
        } else {
          this.error.set('Failed to load gallery images');
        }
        this.loading.set(false);
      },
      error: (err) => {
        console.error('Error loading gallery images:', err);
        this.error.set('Failed to load gallery images');
        this.loading.set(false);
      }
    });
  }

  getTotalPages(): number {
    return Math.ceil(this.totalImages() / this.imagesPerPage);
  }

  getStartPhoto(): number {
    return (this.currentPage() - 1) * this.imagesPerPage + 1;
  }

  getEndPhoto(): number {
    return Math.min(this.currentPage() * this.imagesPerPage, this.totalImages());
  }

  goToPage(page: number) {
    if (page >= 1 && page <= this.getTotalPages()) {
      this.currentPage.set(page);
      this.loadGalleryImages();
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  }

  handlePageInput(event: Event) {
    const input = event.target as HTMLInputElement;
    const page = parseInt(input.value, 10);
    if (!isNaN(page)) {
      this.goToPage(page);
    }
  }

  openModal(index: number) {
    this.modalIndex.set(index);
    this.modalOpen.set(true);
  }

  closeModal() {
    this.modalOpen.set(false);
  }

  nextModalImage(event: Event) {
    event.stopPropagation();
    const currentIndex = this.modalIndex();
    if (currentIndex < this.images().length - 1) {
      this.modalIndex.set(currentIndex + 1);
    }
  }

  previousModalImage(event: Event) {
    event.stopPropagation();
    const currentIndex = this.modalIndex();
    if (currentIndex > 0) {
      this.modalIndex.set(currentIndex - 1);
    }
  }
}

<!-- Hero Section -->
<section class="page-hero">
    <!-- Video Background - Desktop -->
    <video #heroVideoDesktop id="galleryVideo" class="hero-video hero-video-desktop" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <!-- Video Background - Mobile -->
    <video #heroVideoMobile id="galleryVideoMobile" class="hero-video hero-video-mobile" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <div class="container">
        <h1 class="hero-title" id="galleryTitle">Photo Gallery</h1>
        <p class="hero-subtitle" id="gallerySubtitle">Conference Memories & Highlights</p>
        <p class="hero-subtitle" style="margin-top: 10px; font-size: 1rem; color: #FFB300;">&nbsp</p>
    </div>
</section>

<!-- Gallery Section -->
<section class="gallery-section">
    <div class="container">
        @if (loading()) {
            <div class="loading-spinner">
                <div class="spinner"></div>
                <p>Loading gallery...</p>
            </div>
        }

        @if (error()) {
            <div class="alert alert-error">
                <p>{{ error() }}</p>
            </div>
        }

        @if (!loading() && !error() && images().length === 0) {
            <!-- Empty Gallery State -->
            <div class="gallery-empty">
                <div class="gallery-empty-icon">📸</div>
                <h2>No Photos Yet</h2>
                <p>Gallery photos will be added soon. Check back later!</p>
                <a routerLink="/home" class="btn btn-primary">Return Home</a>
            </div>
        }

        @if (!loading() && images().length > 0) {
            <!-- TOP PAGINATION CONTROLS -->
            <div class="controls">
                <div class="page-info">
                    Page <span id="currentPage">{{ currentPage() }}</span> of <span id="totalPages">{{ getTotalPages() }}</span>
                    (Photos <span id="startPhoto">{{ getStartPhoto() }}</span>-<span id="endPhoto">{{ getEndPhoto() }}</span> of <span id="totalPhotos">{{ totalImages() }}</span>)
                </div>
                <div class="nav-buttons">
                    <button class="nav-button" id="firstButton" (click)="goToPage(1)" [disabled]="currentPage() === 1">⏮ First</button>
                    <button class="nav-button" id="prevButton" (click)="goToPage(currentPage() - 1)" [disabled]="currentPage() === 1">◀ Previous</button>
                    <input type="number"
                           class="page-input"
                           id="pageInput"
                           [min]="1"
                           [max]="getTotalPages()"
                           [value]="currentPage()"
                           (change)="handlePageInput($event)">
                    <button class="nav-button" id="nextButton" (click)="goToPage(currentPage() + 1)" [disabled]="currentPage() === getTotalPages()">Next ▶</button>
                    <button class="nav-button" id="lastButton" (click)="goToPage(getTotalPages())" [disabled]="currentPage() === getTotalPages()">Last ⏭</button>
                </div>
            </div>

            <!-- Gallery Grid -->
            <div class="gallery-grid">
                @for (image of images(); track image.id; let i = $index) {
                    <div class="gallery-item">
                        <img [src]="image.fullPath"
                             [alt]="image.title"
                             (click)="openModal(i)"
                             loading="lazy">
                        <div class="info">
                            <div class="date">{{ image.title }}</div>
                        </div>
                    </div>
                }
            </div>

            <!-- BOTTOM PAGINATION CONTROLS (IDENTICAL TO TOP) -->
            <div class="controls">
                <div class="page-info">
                    Page <span id="currentPageBottom">{{ currentPage() }}</span> of <span id="totalPagesBottom">{{ getTotalPages() }}</span>
                    (Photos <span id="startPhotoBottom">{{ getStartPhoto() }}</span>-<span id="endPhotoBottom">{{ getEndPhoto() }}</span> of <span id="totalPhotosBottom">{{ totalImages() }}</span>)
                </div>
                <div class="nav-buttons">
                    <button class="nav-button" id="firstButtonBottom" (click)="goToPage(1)" [disabled]="currentPage() === 1">⏮ First</button>
                    <button class="nav-button" id="prevButtonBottom" (click)="goToPage(currentPage() - 1)" [disabled]="currentPage() === 1">◀ Previous</button>
                    <input type="number"
                           class="page-input"
                           id="pageInputBottom"
                           [min]="1"
                           [max]="getTotalPages()"
                           [value]="currentPage()"
                           (change)="handlePageInput($event)">
                    <button class="nav-button" id="nextButtonBottom" (click)="goToPage(currentPage() + 1)" [disabled]="currentPage() === getTotalPages()">Next ▶</button>
                    <button class="nav-button" id="lastButtonBottom" (click)="goToPage(getTotalPages())" [disabled]="currentPage() === getTotalPages()">Last ⏭</button>
                </div>
            </div>
        }
    </div>
</section>

<!-- Lightbox Modal -->
@if (modalOpen()) {
    <div id="imageModal" class="modal" (click)="closeModal()">
        <span class="close" (click)="closeModal()">&times;</span>
        <img class="modal-content" id="modalImage" [src]="images()[modalIndex()]?.fullPath" (click)="$event.stopPropagation()">

        <div class="modal-arrows">
            <button class="arrow-left" id="prevModalBtn" (click)="previousModalImage($event)" [disabled]="modalIndex() === 0">◀</button>
            <button class="arrow-right" id="nextModalBtn" (click)="nextModalImage($event)" [disabled]="modalIndex() === images().length - 1">▶</button>
        </div>

        <div class="modal-info" id="modalInfo">Photo {{ modalIndex() + 1 }} of {{ images().length }}</div>
    </div>
}

// react-app-source/src/pages/Gallery.js
import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { useAudio } from '../contexts/AudioContext';
import { getGalleryImages, getGalleryCount } from '../services/api';
import Header from '../components/shared/Header';
import Footer from '../components/shared/Footer';

function Gallery() {
  const { isPlaying } = useAudio();
  const [images, setImages] = useState([]);
  const [totalImages, setTotalImages] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [modalIndex, setModalIndex] = useState(0);

  const imagesPerPage = 9;
  const heroVideoDesktopRef = useRef(null);
  const heroVideoMobileRef = useRef(null);

  useEffect(() => {
    loadGalleryCount();
  }, []);

  useEffect(() => {
    loadGalleryImages();
  }, [currentPage]);

  useEffect(() => {
    const desktopVideo = heroVideoDesktopRef.current;
    const mobileVideo = heroVideoMobileRef.current;

    [desktopVideo, mobileVideo].forEach(video => {
      if (video) {
        video.muted = true;
        video.volume = 0;
        if (isPlaying) {
          video.play().catch(() => {});
        } else {
          video.pause();
        }
      }
    });
  }, [isPlaying]);

  const loadGalleryCount = async () => {
    try {
      const response = await getGalleryCount('gallery');
      if (response.success) {
        setTotalImages(response.totalcount);
      }
    } catch (err) {
      console.error('Error loading gallery count:', err);
    }
  };

  const loadGalleryImages = async () => {
    try {
      setLoading(true);
      const response = await getGalleryImages('gallery', currentPage, imagesPerPage);
      if (response.success && response.data) {
        setImages(response.data);
      } else {
        setError('Failed to load gallery images');
      }
    } catch (err) {
      console.error('Error loading gallery images:', err);
      setError('Failed to load gallery images');
    } finally {
      setLoading(false);
    }
  };

  const getTotalPages = () => Math.ceil(totalImages / imagesPerPage);
  const getStartPhoto = () => (currentPage - 1) * imagesPerPage + 1;
  const getEndPhoto = () => Math.min(currentPage * imagesPerPage, totalImages);

  const goToPage = (page) => {
    if (page >= 1 && page <= getTotalPages()) {
      setCurrentPage(page);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const handlePageInput = (e) => {
    const page = parseInt(e.target.value, 10);
    if (!isNaN(page)) {
      goToPage(page);
    }
  };

  const openModal = (index) => {
    setModalIndex(index);
    setModalOpen(true);
  };

  const closeModal = () => {
    setModalOpen(false);
  };

  const nextModalImage = (e) => {
    e.stopPropagation();
    if (modalIndex < images.length - 1) {
      setModalIndex(modalIndex + 1);
    }
  };

  const previousModalImage = (e) => {
    e.stopPropagation();
    if (modalIndex > 0) {
      setModalIndex(modalIndex - 1);
    }
  };

  const PaginationControls = ({ suffix = '' }) => (
    <div className="controls">
      <div className="page-info">
        Page <span id={`currentPage${suffix}`}>{currentPage}</span> of <span id={`totalPages${suffix}`}>{getTotalPages()}</span>
        {' '}(Photos <span id={`startPhoto${suffix}`}>{getStartPhoto()}</span>-<span id={`endPhoto${suffix}`}>{getEndPhoto()}</span> of <span id={`totalPhotos${suffix}`}>{totalImages}</span>)
      </div>
      <div className="nav-buttons">
        <button className="nav-button" onClick={() => goToPage(1)} disabled={currentPage === 1}>&#9198; First</button>
        <button className="nav-button" onClick={() => goToPage(currentPage - 1)} disabled={currentPage === 1}>&#9664; Previous</button>
        <input
          type="number"
          className="page-input"
          min="1"
          max={getTotalPages()}
          value={currentPage}
          onChange={handlePageInput}
        />
        <button className="nav-button" onClick={() => goToPage(currentPage + 1)} disabled={currentPage === getTotalPages()}>Next &#9654;</button>
        <button className="nav-button" onClick={() => goToPage(getTotalPages())} disabled={currentPage === getTotalPages()}>Last &#9197;</button>
      </div>
    </div>
  );

  return (
    <>
      <Header />

      {/* Hero Section */}
      <section className="page-hero">
        <video ref={heroVideoDesktopRef} id="galleryVideo" className="hero-video hero-video-desktop" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>
        <video ref={heroVideoMobileRef} id="galleryVideoMobile" className="hero-video hero-video-mobile" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>

        <div className="container">
          <h1 className="hero-title" id="galleryTitle">Photo Gallery</h1>
          <p className="hero-subtitle" id="gallerySubtitle">Conference Memories & Highlights</p>
        </div>
      </section>

      {/* Gallery Section */}
      <section className="gallery-section">
        <div className="container">
          {loading && (
            <div className="loading-spinner">
              <div className="spinner"></div>
              <p>Loading gallery...</p>
            </div>
          )}

          {error && (
            <div className="alert alert-error">
              <p>{error}</p>
            </div>
          )}

          {!loading && !error && images.length === 0 && (
            <div className="gallery-empty">
              <div className="gallery-empty-icon">&#128248;</div>
              <h2>No Photos Yet</h2>
              <p>Gallery photos will be added soon. Check back later!</p>
              <Link to="/home" className="btn btn-primary">Return Home</Link>
            </div>
          )}

          {!loading && images.length > 0 && (
            <>
              <PaginationControls />

              <div className="gallery-grid">
                {images.map((image, index) => (
                  <div key={image.id} className="gallery-item">
                    <img
                      src={image.fullpath}
                      alt={image.title}
                      onClick={() => openModal(index)}
                      loading="lazy"
                    />
                    <div className="info">
                      <div className="date">{image.title}</div>
                    </div>
                  </div>
                ))}
              </div>

              <PaginationControls suffix="Bottom" />
            </>
          )}
        </div>
      </section>

      {/* Lightbox Modal */}
      {modalOpen && (
        <div id="imageModal" className="modal" onClick={closeModal}>
          <span className="close" onClick={closeModal}>&times;</span>
          <img
            className="modal-content"
            id="modalImage"
            src={images[modalIndex]?.fullpath}
            alt=""
            onClick={(e) => e.stopPropagation()}
          />

          <div className="modal-arrows">
            <button className="arrow-left" onClick={previousModalImage} disabled={modalIndex === 0}>&#9664;</button>
            <button className="arrow-right" onClick={nextModalImage} disabled={modalIndex === images.length - 1}>&#9654;</button>
          </div>

          <div className="modal-info" id="modalInfo">Photo {modalIndex + 1} of {images.length}</div>
        </div>
      )}

      <Footer />
    </>
  );
}

export default Gallery;
