// Front_End/angular-app/src/app/components/home/home.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, AfterViewInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { AudioService } from '../../services/audio.service';
import { Announcement } from '../../models/api-models';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('heroVideoDesktop', { static: false }) heroVideoDesktop!: ElementRef<HTMLVideoElement>;
  @ViewChild('heroVideoMobile', { static: false }) heroVideoMobile!: ElementRef<HTMLVideoElement>;

  private apiService = inject(ApiService);
  private audioService = inject(AudioService);

  announcements = signal<Announcement[]>([]);
  loading = signal(true);
  error = signal<string | null>(null);

  private subscriptions: Subscription[] = [];

  ngOnInit() {
    this.loadAnnouncements();
    this.setupAudioSubscription();
  }

  ngAfterViewInit(): void {
    // Initial video control based on current audio state
    this.controlVideoPlayback(this.audioService.isPlaying());
  }

  ngOnDestroy(): void {
    // Unsubscribe from all subscriptions
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  /**
   * Set up subscription to audio service to control video playback
   */
  private setupAudioSubscription(): void {
    // Subscribe to playing state only (mute state doesn't affect video)
    const playingSub = this.audioService.isPlaying$.subscribe(playing => {
      this.controlVideoPlayback(playing);
    });

    this.subscriptions.push(playingSub);
  }

  /**
   * Control hero video playback
   */
  private controlVideoPlayback(shouldPlay: boolean): void {
    if (this.heroVideoDesktop && this.heroVideoDesktop.nativeElement) {
      if (shouldPlay) {
        this.heroVideoDesktop.nativeElement.play().catch(err => {
          console.log('Video autoplay prevented:', err);
        });
      } else {
        this.heroVideoDesktop.nativeElement.pause();
      }
    }

    if (this.heroVideoMobile && this.heroVideoMobile.nativeElement) {
      if (shouldPlay) {
        this.heroVideoMobile.nativeElement.play().catch(err => {
          console.log('Video autoplay prevented:', err);
        });
      } else {
        this.heroVideoMobile.nativeElement.pause();
      }
    }
  }

  private loadAnnouncements() {
    this.loading.set(true);
    this.apiService.getAnnouncements().subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.announcements.set(response.data);
        } else {
          this.error.set('Failed to load announcements');
        }
        this.loading.set(false);
      },
      error: (err) => {
        console.error('Error loading announcements:', err);
        this.error.set('Failed to load announcements');
        this.loading.set(false);
      }
    });
  }
}

<!-- Hero Section -->
<section class="hero">
  <!-- Video Background - Desktop -->
  <video #heroVideoDesktop id="heroVideo" class="hero-video hero-video-desktop" muted loop playsinline>
    <source src="/assets/video/space-background.mp4" type="video/mp4">
  </video>

  <!-- Video Background - Mobile -->
  <video #heroVideoMobile id="heroVideoMobile" class="hero-video hero-video-mobile" muted loop playsinline>
    <source src="/assets/video/space-background_M.mp4" type="video/mp4">
  </video>

  <div class="hero-content">
    <div class="stars-background"></div>
    <div class="hero-text">
      <h1 class="hero-title" id="heroTitle">PASC REGION J CONFERENCE 2026</h1>
      <p class="hero-subtitle" id="heroSubtitle">Reach for the Stars, Lead Beyond Limits - February 13, 2026</p>

      <div class="hero-buttons">
        <a routerLink="/workshops" class="btn btn-primary">Register Now</a>
        <a routerLink="/about" class="btn btn-secondary">Learn More</a>
      </div>
    </div>
  </div>
</section>

<!-- Announcements Section -->
<section class="announcements-section">
  <div class="container">
    <h2 class="section-title">Latest Announcements</h2>

    @if (loading()) {
      <div class="loading-spinner">
        <div class="spinner"></div>
        <p>Loading announcements...</p>
      </div>
    }

    @if (error()) {
      <div class="alert alert-error">
        <p>{{ error() }}</p>
      </div>
    }

    @if (!loading() && !error() && announcements().length === 0) {
      <p class="no-announcements">No announcements at this time. Check back soon!</p>
    }

    @if (!loading() && announcements().length > 0) {
      <div class="announcements-grid">
        @for (announcement of announcements(); track announcement.id) {
          <div class="announcement-card" [class.featured]="announcement.isFeatured">
            @if (announcement.isFeatured) {
              <span class="featured-badge">⭐ Featured</span>
            }
            <h3>{{ announcement.title }}</h3>
            <p>{{ announcement.content }}</p>
            <span class="announcement-date">{{ announcement.publishStart }}</span>
          </div>
        }
      </div>
    }
  </div>
</section>

<!-- Quick Info Section -->
<section class="quick-info">
  <div class="container">
    <div class="info-grid">
      <div class="info-card">
        <div class="info-icon">📆</div>
        <h3>Event Date</h3>
        <p>February 13, 2026</p>
      </div>

      <div class="info-card">
        <div class="info-icon">🎓</div>
        <h3>Who Can Attend</h3>
        <p>Student Council Members within Region J</p>
      </div>

      <div class="info-card">
        <div class="info-icon">🚀</div>
        <h3>Theme</h3>
        <p>Navigating the Stars</p>
      </div>

      <div class="info-card">
        <div class="info-icon">📋</div>
        <h3>Registration</h3>
        <p>January 5-23, 2026</p>
      </div>
    </div>
  </div>
</section>

<!-- Call to Action Section -->
<section class="cta-section">
  <div class="container">
    <h2>Ready to Reach for the Stars, Lead Beyond Limits?</h2>
    <p>Join us for an inspiring day of leadership, workshops, and networking!</p>
    <div class="cta-buttons">
      <a routerLink="/workshops" class="btn btn-large btn-primary">Register for the Conference</a>
      <a routerLink="/workshops" class="btn btn-large btn-outline">Apply to Present a Workshop</a>
    </div>
  </div>
</section>

// react-app-source/src/pages/Home.js
import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { getAnnouncements } from '../services/api';
import Header from '../components/shared/Header';
import Footer from '../components/shared/Footer';

function Home() {
  const [announcements, setAnnouncements] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const heroVideoDesktopRef = useRef(null);
  const heroVideoMobileRef = useRef(null);

  useEffect(() => {
    loadAnnouncements();
  }, []);

  useEffect(() => {
    // Video should always autoplay (muted) - independent of audio state
    const desktopVideo = heroVideoDesktopRef.current;
    const mobileVideo = heroVideoMobileRef.current;
    const isMobile = window.innerWidth <= 768;

    const activeVideo = isMobile ? mobileVideo : desktopVideo;

    if (activeVideo) {
      activeVideo.muted = true;
      activeVideo.loop = true;
      activeVideo.play().catch(err => {
        console.log('Video autoplay prevented:', err);
        // Try to play on user interaction
        document.addEventListener('click', () => {
          activeVideo.play();
        }, { once: true });
      });
    }
  }, []);

  const loadAnnouncements = async () => {
    try {
      setLoading(true);
      const response = await getAnnouncements();
      if (response.success && response.data) {
        setAnnouncements(response.data);
      } else {
        setError('Failed to load announcements');
      }
    } catch (err) {
      console.error('Error loading announcements:', err);
      setError('Failed to load announcements');
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  };

  return (
    <>
      <Header />

      {/* Hero Section */}
      <section className="hero">
        {/* Video Background - Desktop */}
        <video
          ref={heroVideoDesktopRef}
          id="heroVideo"
          className="hero-video hero-video-desktop"
          muted
          loop
          playsInline
        >
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>

        {/* Video Background - Mobile */}
        <video
          ref={heroVideoMobileRef}
          id="heroVideoMobile"
          className="hero-video hero-video-mobile"
          muted
          loop
          playsInline
        >
          <source src="/assets/video/space-background_M.mp4" type="video/mp4" />
        </video>

        <div className="hero-content">
          <div className="stars-background"></div>
          <div className="hero-text">
            <h1 className="hero-title" id="heroTitle">PASC REGION J CONFERENCE 2026</h1>
            <p className="hero-subtitle" id="heroSubtitle">Reach for the Stars, Lead Beyond Limits - February 13, 2026</p>

            <div className="hero-buttons">
              <Link to="/workshops" className="btn btn-primary">Register Now</Link>
              <Link to="/about" className="btn btn-secondary">Learn More</Link>
            </div>
          </div>
        </div>
      </section>

      {/* Announcements Section */}
      <section className="announcements-section">
        <div className="container">
          <h2 className="section-title">Latest Announcements</h2>

          {loading && (
            <div className="loading-spinner">
              <div className="spinner"></div>
              <p>Loading announcements...</p>
            </div>
          )}

          {error && (
            <div className="alert alert-error">
              <p>{error}</p>
            </div>
          )}

          {!loading && !error && announcements.length === 0 && (
            <p className="no-announcements">No announcements at this time. Check back soon!</p>
          )}

          {!loading && announcements.length > 0 && (
            <div className="announcements-grid">
              {announcements.map(announcement => (
                <div
                  key={announcement.id}
                  className={`announcement-card ${announcement.isfeatured ? 'featured' : ''}`}
                >
                  {announcement.isfeatured ? (
                    <span className="featured-badge">&#11088; Featured</span>
                  ) : null}
                  <h3>{announcement.title}</h3>
                  <p>{announcement.content}</p>
                  <span className="announcement-date">{formatDate(announcement.publishstart)}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </section>

      {/* Quick Info Section */}
      <section className="quick-info">
        <div className="container">
          <div className="info-grid">
            <div className="info-card">
              <div className="info-icon">&#128197;</div>
              <h3>Event Date</h3>
              <p>February 13, 2026</p>
            </div>

            <div className="info-card">
              <div className="info-icon">&#127891;</div>
              <h3>Who Can Attend</h3>
              <p>Student Council Members within Region J</p>
            </div>

            <div className="info-card">
              <div className="info-icon">&#128640;</div>
              <h3>Theme</h3>
              <p>Navigating the Stars</p>
            </div>

            <div className="info-card">
              <div className="info-icon">&#128203;</div>
              <h3>Registration</h3>
              <p>January 5-23, 2026</p>
            </div>
          </div>
        </div>
      </section>

      {/* Call to Action Section */}
      <section className="cta-section">
        <div className="container">
          <h2>Ready to Reach for the Stars, Lead Beyond Limits?</h2>
          <p>Join us for an inspiring day of leadership, workshops, and networking!</p>
          <div className="cta-buttons">
            <Link to="/workshops" className="btn btn-large btn-primary">Register for the Conference</Link>
            <Link to="/workshops" className="btn btn-large btn-outline">Apply to Present a Workshop</Link>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}

export default Home;
