// Front_End/angular-app/src/app/components/resources/resources.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, AfterViewInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { AudioService } from '../../services/audio.service';
import { Document, PageContent } from '../../models/api-models';

@Component({
  selector: 'app-resources',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './resources.component.html',
  styleUrl: './resources.component.css'
})
export class ResourcesComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('heroVideoDesktop', { static: false }) heroVideoDesktop!: ElementRef<HTMLVideoElement>;
  @ViewChild('heroVideoMobile', { static: false }) heroVideoMobile!: ElementRef<HTMLVideoElement>;
  @ViewChild('anthemAudio', { static: false }) anthemAudio!: ElementRef<HTMLAudioElement>;
  @ViewChild('anthemSectionVideo', { static: false }) anthemSectionVideo!: ElementRef<HTMLVideoElement>;
  @ViewChild('anthemPlayerVideo', { static: false}) anthemPlayerVideo!: ElementRef<HTMLVideoElement>;
  @ViewChild('progressBar', { static: false }) progressBar!: ElementRef<HTMLDivElement>;

  private apiService = inject(ApiService);
  private audioService = inject(AudioService);

  documents = signal<Document[]>([]);
  pageContent = signal<PageContent | null>(null);
  loading = signal(true);
  error = signal<string | null>(null);

  // Anthem player state
  isAnthemPlaying = signal(false);
  anthemProgress = signal(0);
  anthemCurrentTime = signal(0);
  anthemDuration = signal(0);

  private subscriptions: Subscription[] = [];

  ngOnInit() {
    this.loadPageContent();
    this.loadDocuments();
    this.setupAudioSubscription();
  }

  ngAfterViewInit(): void {
    this.controlVideoPlayback(this.audioService.isPlaying());
    this.setupAnthemPlayerListeners();
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
    // Stop anthem if playing
    if (this.anthemAudio && !this.anthemAudio.nativeElement.paused) {
      this.anthemAudio.nativeElement.pause();
    }
  }

  private setupAudioSubscription(): void {
    const playingSub = this.audioService.isPlaying$.subscribe(playing => {
      this.controlVideoPlayback(playing);
    });
    this.subscriptions.push(playingSub);
  }

  private controlVideoPlayback(shouldPlay: boolean): void {
    [this.heroVideoDesktop, this.heroVideoMobile].forEach(videoRef => {
      if (videoRef && videoRef.nativeElement) {
        if (shouldPlay) {
          videoRef.nativeElement.play().catch(() => {});
        } else {
          videoRef.nativeElement.pause();
        }
      }
    });
  }

  private setupAnthemPlayerListeners(): void {
    if (!this.anthemAudio) return;

    const audio = this.anthemAudio.nativeElement;

    // Update progress bar and time
    audio.addEventListener('timeupdate', () => {
      if (audio.duration) {
        const progress = (audio.currentTime / audio.duration) * 100;
        this.anthemProgress.set(progress);
        this.anthemCurrentTime.set(audio.currentTime);
      }
    });

    // Set duration when metadata loads
    audio.addEventListener('loadedmetadata', () => {
      this.anthemDuration.set(audio.duration);
    });

    // Update playing state
    audio.addEventListener('play', () => {
      this.isAnthemPlaying.set(true);
      // Pause global background music
      if (this.audioService.isPlaying()) {
        this.audioService.pause();
      }
      // Play anthem videos
      if (this.anthemSectionVideo) {
        this.anthemSectionVideo.nativeElement.play().catch(() => {});
      }
      if (this.anthemPlayerVideo) {
        this.anthemPlayerVideo.nativeElement.play().catch(() => {});
      }
    });

    audio.addEventListener('pause', () => {
      this.isAnthemPlaying.set(false);
      // Pause anthem videos
      if (this.anthemSectionVideo) {
        this.anthemSectionVideo.nativeElement.pause();
      }
      if (this.anthemPlayerVideo) {
        this.anthemPlayerVideo.nativeElement.pause();
      }
    });

    // Reset on end (for looping, this shouldn't trigger often)
    audio.addEventListener('ended', () => {
      this.isAnthemPlaying.set(false);
      this.anthemProgress.set(0);
    });
  }

  toggleAnthemPlayback(): void {
    if (!this.anthemAudio) return;

    const audio = this.anthemAudio.nativeElement;
    if (audio.paused) {
      audio.play().catch(err => console.log('Anthem audio play failed:', err));
    } else {
      audio.pause();
    }
  }

  seekAnthemAudio(event: MouseEvent): void {
    if (!this.anthemAudio || !this.progressBar) return;

    const audio = this.anthemAudio.nativeElement;
    const progressBarEl = this.progressBar.nativeElement;
    const clickX = event.offsetX;
    const width = progressBarEl.offsetWidth;
    const seekTime = (clickX / width) * audio.duration;
    audio.currentTime = seekTime;
  }

  formatTime(seconds: number): string {
    if (isNaN(seconds) || seconds === 0) return '0:00';
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return mins + ':' + (secs < 10 ? '0' : '') + secs;
  }

  private loadPageContent() {
    this.apiService.getPageContent('resources').subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.pageContent.set(response.data);
        }
      },
      error: (err) => {
        console.error('Error loading page content:', err);
      }
    });
  }

  private loadDocuments() {
    this.loading.set(true);
    this.apiService.getDocuments().subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.documents.set(response.data);
        } else {
          this.error.set('Failed to load documents');
        }
        this.loading.set(false);
      },
      error: (err) => {
        console.error('Error loading documents:', err);
        this.error.set('Failed to load documents');
        this.loading.set(false);
      }
    });
  }
}

<!-- Hero Section -->
<section class="page-hero">
    <!-- Video Background - Desktop -->
    <video #heroVideoDesktop id="resourcesVideo" class="hero-video hero-video-desktop" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <!-- Video Background - Mobile -->
    <video #heroVideoMobile id="resourcesVideoMobile" class="hero-video hero-video-mobile" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <div class="container">
        <h1 class="hero-title" id="resourcesTitle">Resources</h1>
        <p class="hero-subtitle" id="resourcesSubtitle">Conference Materials & Media</p>
        <p class="hero-subtitle" style="margin-top: 10px; font-size: 1rem; color: #FFB300;">&nbsp;</p>
    </div>
</section>

<!-- Conference Anthem Section with Cinema Effect -->
<div class="cinema-theater-wrapper">
    <!-- Static Space Background (Theater Ambiance) -->
    <video #cinemaSpaceBg class="cinema-space-bg" muted loop playsinline autoplay>
        <source src="/assets/video/intro-space-background.mp4" type="video/mp4">
    </video>

    <!-- Dark Vignette (Theater Edges) -->
    <div class="cinema-vignette"></div>

    <section class="anthem-section">
        <!-- Section Background Video -->
        <video #anthemSectionVideo id="anthemSectionVideo" class="anthem-section-video" muted loop playsinline>
            <source src="/assets/video/resources-background.mp4" type="video/mp4">
        </video>

        <div class="container">
            <!-- Cinema Screen Frame -->
            <div class="cinema-screen-frame">
                <div class="anthem-featured">
                    <!-- Singer Background Video - Covers Entire Section -->
                    <video #anthemPlayerVideo id="anthemPlayerVideo" class="anthem-player-video" muted loop playsinline>
                        <source src="/assets/video/conference-anthem-background.mp4" type="video/mp4">
                    </video>

                    <div class="anthem-header">
                        <h2>Conference Anthem</h2>
                        <div class="anthem-info">
                            <h3 class="song-title">One Orbit</h3>
                            <p class="song-artist">by IronRUST</p>
                            <p class="song-description">Official theme song for PASC Region J Conference 2026: Reach for the stars, lead beyond limits!</p>
                        </div>
                    </div>

                    <!-- Audio Player -->
                    <div class="custom-audio-player">
                        <audio #anthemAudio id="anthemAudio" preload="metadata" loop>
                            <source src="/assets/audio/one-orbit-anthem.mp3" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>

                        <div class="player-controls">
                            <button #playPauseBtn id="playPauseBtn" class="play-pause-btn" aria-label="Play/Pause" (click)="toggleAnthemPlayback()">
                                <svg class="play-icon" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" [style.display]="isAnthemPlaying() ? 'none' : 'block'">
                                    <path d="M8 5v14l11-7z"/>
                                </svg>
                                <svg class="pause-icon" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" [style.display]="isAnthemPlaying() ? 'block' : 'none'">
                                    <path d="M6 4h4v16H6V4zm8 0h4v16h-4V4z"/>
                                </svg>
                            </button>

                            <div class="player-info">
                                <div class="progress-container">
                                    <div class="progress-bar" #progressBar id="progressBar" (click)="seekAnthemAudio($event)">
                                        <div class="progress-fill" id="progressFill" [style.width.%]="anthemProgress()"></div>
                                    </div>
                                </div>
                                <div class="time-display">
                                    <span id="currentTime">{{ formatTime(anthemCurrentTime()) }}</span>
                                    <span class="time-separator">/</span>
                                    <span id="duration">{{ formatTime(anthemDuration()) }}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Download Button -->
                    <div class="anthem-download">
                        <a href="/assets/audio/one-orbit-anthem-full.mp3" download="one-orbit-anthem-full.mp3" class="btn btn-download">
                            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                                <polyline points="7 10 12 15 17 10"/>
                                <line x1="12" y1="15" x2="12" y2="3"/>
                            </svg>
                            Download MP3
                        </a>
                        <a href="/assets/audio/instrumental_background.mp3" download="instrumental_background.mp3" class="btn btn-download btn-secondary-download">
                            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                                <polyline points="7 10 12 15 17 10"/>
                                <line x1="12" y1="15" x2="12" y2="3"/>
                            </svg>
                            Download Background Music (Instrumental)
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Document Library Section -->
<section class="documents-section">
    <div class="container">
        <div class="section-header">
            <h2>Resource Library</h2>
            <p class="section-description">Browse and download conference materials, guides, and resources</p>
        </div>

        @if (loading()) {
            <div class="loading-spinner">
                <div class="spinner"></div>
                <p>Loading resources...</p>
            </div>
        }

        @if (error()) {
            <div class="alert alert-error">
                <p>{{ error() }}</p>
            </div>
        }

        @if (!loading() && !error() && documents().length > 0) {
            <div class="documents-grid">
                @for (doc of documents(); track doc.id) {
                    <div class="document-card">
                        <!-- File Type Icon -->
                        <div class="document-icon">
                            @if (doc.fileExtension === '.pdf') {
                                <span class="icon-pdf">📄</span>
                            } @else if (doc.fileExtension === '.doc' || doc.fileExtension === '.docx') {
                                <span class="icon-word">📘</span>
                            } @else if (doc.fileExtension === '.xls' || doc.fileExtension === '.xlsx') {
                                <span class="icon-excel">📊</span>
                            } @else if (doc.fileExtension === '.ppt' || doc.fileExtension === '.pptx') {
                                <span class="icon-powerpoint">📙</span>
                            } @else {
                                <span class="icon-generic">📃</span>
                            }
                        </div>

                        <!-- Document Title -->
                        <h3 class="document-title">{{ doc.title }}</h3>

                        <!-- Description (if exists) -->
                        @if (doc.description) {
                            <p class="document-description">{{ doc.description }}</p>
                        }

                        <!-- Category Badge (if exists) -->
                        @if (doc.documentType) {
                            <span class="document-badge">{{ doc.documentType }}</span>
                        }

                        <!-- File Size -->
                        <p class="document-size">{{ doc.fileSizeFormatted }}</p>

                        <!-- Download Button -->
                        <a [href]="doc.downloadPath" [download]="doc.originalFilename" class="btn btn-download-doc">
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                                <polyline points="7 10 12 15 17 10"/>
                                <line x1="12" y1="15" x2="12" y2="3"/>
                            </svg>
                            Download
                        </a>
                    </div>
                }
            </div>
        }

        @if (!loading() && !error() && documents().length === 0) {
            <div class="no-documents">
                <p>No resources available yet. Check back soon!</p>
            </div>
        }
    </div>
</section>

// react-app-source/src/pages/Resources.js
import React, { useState, useEffect, useRef } from 'react';
import { useAudio } from '../contexts/AudioContext';
import { getDocuments, getPageContent, getSchedule } from '../services/api';
import Header from '../components/shared/Header';
import Footer from '../components/shared/Footer';

function Resources() {
  const { isPlaying } = useAudio();
  const [documents, setDocuments] = useState([]);
  const [pageContent, setPageContent] = useState(null);
  const [scheduleItems, setScheduleItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const heroVideoDesktopRef = useRef(null);
  const heroVideoMobileRef = useRef(null);

  useEffect(() => {
    loadPageContent();
    loadDocuments();
    loadSchedule();
  }, []);

  useEffect(() => {
    [heroVideoDesktopRef, heroVideoMobileRef].forEach(ref => {
      const video = ref.current;
      if (video) {
        video.muted = true;
        video.volume = 0;
        if (isPlaying) {
          video.play().catch(() => {});
        } else {
          video.pause();
        }
      }
    });
  }, [isPlaying]);

  const loadPageContent = async () => {
    try {
      const response = await getPageContent('resources');
      if (response.success && response.data) {
        setPageContent(response.data);
      }
    } catch (err) {
      console.error('Error loading page content:', err);
    }
  };

  const loadDocuments = async () => {
    try {
      setLoading(true);
      const response = await getDocuments();
      if (response.success && response.data) {
        setDocuments(response.data);
      } else {
        setError('Failed to load documents');
      }
    } catch (err) {
      console.error('Error loading documents:', err);
      setError('Failed to load documents');
    } finally {
      setLoading(false);
    }
  };

  const loadSchedule = async () => {
    try {
      const response = await getSchedule();
      if (response.success && response.data) {
        setScheduleItems(response.data);
      }
    } catch (err) {
      console.error('Error loading schedule:', err);
    }
  };

  const getDownloadUrl = (filename) => {
    return `/assets/documents/${filename}`;
  };

  const getFileIcon = (extension) => {
    switch (extension?.toLowerCase()) {
      case 'pdf':
        return <span className="icon-pdf">&#128196;</span>;
      case 'doc':
      case 'docx':
        return <span className="icon-word">&#128216;</span>;
      case 'xls':
      case 'xlsx':
        return <span className="icon-excel">&#128202;</span>;
      case 'ppt':
      case 'pptx':
        return <span className="icon-powerpoint">&#128217;</span>;
      default:
        return <span className="icon-generic">&#128195;</span>;
    }
  };

  return (
    <>
      <Header />

      {/* Hero Section */}
      <section className="page-hero">
        <video ref={heroVideoDesktopRef} id="resourcesVideo" className="hero-video hero-video-desktop" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>
        <video ref={heroVideoMobileRef} id="resourcesVideoMobile" className="hero-video hero-video-mobile" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>

        <div className="container">
          <h1 className="hero-title" id="resourcesTitle">Resources</h1>
          <p className="hero-subtitle" id="resourcesSubtitle">Conference Materials & Media</p>
        </div>
      </section>

      {/* Document Library Section */}
      <section className="documents-section">
        <div className="container">
          <div className="section-header">
            <h2 className="section-title-orange">Resource Library</h2>
            <p className="section-description">Browse and download conference materials, guides, and resources</p>
          </div>

          {loading && (
            <div className="loading-spinner">
              <div className="spinner"></div>
              <p>Loading resources...</p>
            </div>
          )}

          {error && (
            <div className="alert alert-error">
              <p>{error}</p>
            </div>
          )}

          {!loading && !error && documents.length > 0 && (
            <div className="documents-grid">
              {documents.map(doc => (
                <div key={doc.id} className="document-card">
                  {/* File Type Icon */}
                  <div className="document-icon">
                    {getFileIcon(doc.fileextension)}
                  </div>

                  {/* Document Title */}
                  <h3 className="document-title">{doc.title}</h3>

                  {/* Description (if exists) */}
                  {doc.description && (
                    <p className="document-description">{doc.description}</p>
                  )}

                  {/* Category Badge (if exists) */}
                  {doc.documenttype && (
                    <span className="document-badge">{doc.documenttype}</span>
                  )}

                  {/* File Size */}
                  <p className="document-size">{doc.filesizeformatted}</p>

                  {/* Download Button */}
                  <a
                    href={getDownloadUrl(doc.filename)}
                    download={`${doc.title}.${doc.fileextension}`}
                    className="btn btn-download-doc"
                  >
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                      <polyline points="7 10 12 15 17 10"/>
                      <line x1="12" y1="15" x2="12" y2="3"/>
                    </svg>
                    Download
                  </a>
                </div>
              ))}
            </div>
          )}

          {!loading && !error && documents.length === 0 && (
            <div className="no-documents">
              <p>No resources available yet. Check back soon!</p>
            </div>
          )}
        </div>
      </section>

      <Footer />
    </>
  );
}

export default Resources;
