// angular-app-source/src/app/components/schedule/schedule.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, AfterViewInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { AudioService } from '../../services/audio.service';
import { ScheduleItem } from '../../models/api-models';

@Component({
  selector: 'app-schedule',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './schedule.component.html',
  styleUrl: './schedule.component.css'
})
export class ScheduleComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('heroVideoDesktop', { static: false }) heroVideoDesktop!: ElementRef<HTMLVideoElement>;
  @ViewChild('heroVideoMobile', { static: false }) heroVideoMobile!: ElementRef<HTMLVideoElement>;

  private apiService = inject(ApiService);
  private audioService = inject(AudioService);

  scheduleItems = signal<ScheduleItem[]>([]);
  loading = signal(true);
  error = signal<string | null>(null);

  private subscriptions: Subscription[] = [];

  ngOnInit() {
    this.loadSchedule();
    this.setupAudioSubscription();
  }

  ngAfterViewInit(): void {
    // Explicitly ensure hero videos are muted
    if (this.heroVideoDesktop?.nativeElement) {
      this.heroVideoDesktop.nativeElement.muted = true;
      this.heroVideoDesktop.nativeElement.volume = 0;
    }
    if (this.heroVideoMobile?.nativeElement) {
      this.heroVideoMobile.nativeElement.muted = true;
      this.heroVideoMobile.nativeElement.volume = 0;
    }

    this.controlVideoPlayback(this.audioService.isPlaying());
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  private setupAudioSubscription(): void {
    const playingSub = this.audioService.isPlaying$.subscribe(playing => {
      this.controlVideoPlayback(playing);
    });
    this.subscriptions.push(playingSub);
  }

  private controlVideoPlayback(shouldPlay: boolean): void {
    [this.heroVideoDesktop, this.heroVideoMobile].forEach(videoRef => {
      if (videoRef && videoRef.nativeElement) {
        if (shouldPlay) {
          videoRef.nativeElement.play().catch(() => {});
        } else {
          videoRef.nativeElement.pause();
        }
      }
    });
  }

  private loadSchedule() {
    this.loading.set(true);
    this.apiService.getSchedule().subscribe({
      next: (response) => {
        if (response.success && response.data) {
          this.scheduleItems.set(response.data);
        } else {
          this.error.set('Failed to load schedule');
        }
        this.loading.set(false);
      },
      error: (err) => {
        console.error('Error loading schedule:', err);
        this.error.set('Failed to load schedule');
        this.loading.set(false);
      }
    });
  }

  downloadPDF() {
    // Trigger direct download of PDF
    window.location.href = '/api/schedule-pdf.cfm';
  }
}

<!-- Hero Section -->
<section class="page-hero">
    <!-- Video Background - Desktop -->
    <video #heroVideoDesktop id="scheduleVideo" class="hero-video hero-video-desktop" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <!-- Video Background - Mobile -->
    <video #heroVideoMobile id="scheduleVideoMobile" class="hero-video hero-video-mobile" muted loop playsinline>
        <source src="/assets/video/space-background.mp4" type="video/mp4">
    </video>

    <div class="container">
        <h1 class="hero-title" id="scheduleTitle">Conference Schedule</h1>
        <p class="hero-subtitle" id="scheduleSubtitle">Plan your day of leadership and learning</p>
    </div>
</section>

<!-- Schedule Timeline Section -->
<section class="schedule-timeline-section">
    <div class="container">
        <h2 class="section-title">Schedule Timeline</h2>
        <p class="section-description">
            View the complete conference schedule below.
            <button class="btn-download-pdf" (click)="downloadPDF()" title="Download Schedule PDF">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                    <polyline points="7 10 12 15 17 10"/>
                    <line x1="12" y1="15" x2="12" y2="3"/>
                </svg>
                Download PDF
            </button>
        </p>

        @if (loading()) {
            <div class="loading-spinner">
                <div class="spinner"></div>
                <p>Loading schedule...</p>
            </div>
        }

        @if (error()) {
            <div class="alert alert-error">
                <p>{{ error() }}</p>
            </div>
        }

        @if (!loading() && !error() && scheduleItems().length > 0) {
            <div class="timeline">
                @for (item of scheduleItems(); track item.schedule_id || $index) {
                    <div class="timeline-item">
                        <div class="timeline-connector"></div>
                        <div class="timeline-content">
                            <div class="time-range">
                                {{ item.event_time }}@if (item.end_time) { - {{ item.end_time }} }
                            </div>
                            <div class="event-details">
                                <div class="event-header">
                                    @if (item.event_icon) {
                                        <span class="event-icon">{{ item.event_icon }}</span>
                                    }
                                    <h3 class="event-name">{{ item.event_name }}</h3>
                                </div>
                                @if (item.event_description) {
                                    <p class="event-description">{{ item.event_description }}</p>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        }

        @if (!loading() && !error() && scheduleItems().length === 0) {
            <div class="no-schedule">
                <div class="message-icon">📅</div>
                <h3>Schedule Coming Soon</h3>
                <p>Our conference schedule will be available shortly. Check back soon!</p>
            </div>
        }
    </div>
</section>

<!-- Workshop Rotation Explanation Section -->
<section class="rotation-section">
    <div class="container">
        <h2 class="section-title">Workshop Rotation Groups</h2>
        <p class="section-description">
            Conference attendees will be assigned to rotation groups for the workshop sessions.
            Each group follows a different sequence to ensure optimal learning experiences.
        </p>

        <div class="rotation-grid">
            <div class="rotation-card">
                <div class="rotation-header group-a">
                    <h3>Group A</h3>
                </div>
                <div class="rotation-sequence">
                    <div class="sequence-item">
                        <div class="sequence-number">1</div>
                        <div class="sequence-text">Workshop 1</div>
                    </div>
                    <div class="sequence-arrow">→</div>
                    <div class="sequence-item">
                        <div class="sequence-number">2</div>
                        <div class="sequence-text">Lunch</div>
                    </div>
                    <div class="sequence-arrow">→</div>
                    <div class="sequence-item">
                        <div class="sequence-number">3</div>
                        <div class="sequence-text">Workshop 2</div>
                    </div>
                </div>
            </div>

            <div class="rotation-card">
                <div class="rotation-header group-b">
                    <h3>Group B</h3>
                </div>
                <div class="rotation-sequence">
                    <div class="sequence-item">
                        <div class="sequence-number">1</div>
                        <div class="sequence-text">Workshop 1</div>
                    </div>
                    <div class="sequence-arrow">→</div>
                    <div class="sequence-item">
                        <div class="sequence-number">2</div>
                        <div class="sequence-text">Workshop 2</div>
                    </div>
                    <div class="sequence-arrow">→</div>
                    <div class="sequence-item">
                        <div class="sequence-number">3</div>
                        <div class="sequence-text">Lunch</div>
                    </div>
                </div>
            </div>

            <div class="rotation-card">
                <div class="rotation-header group-c">
                    <h3>Group C</h3>
                </div>
                <div class="rotation-sequence">
                    <div class="sequence-item">
                        <div class="sequence-number">1</div>
                        <div class="sequence-text">Lunch</div>
                    </div>
                    <div class="sequence-arrow">→</div>
                    <div class="sequence-item">
                        <div class="sequence-number">2</div>
                        <div class="sequence-text">Workshop 1</div>
                    </div>
                    <div class="sequence-arrow">→</div>
                    <div class="sequence-item">
                        <div class="sequence-number">3</div>
                        <div class="sequence-text">Workshop 2</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="rotation-note">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="12" y1="16" x2="12" y2="12"></line>
                <line x1="12" y1="8" x2="12.01" y2="8"></line>
            </svg>
            <p>Your rotation group will be assigned during registration. Please follow your group's schedule for the best experience.</p>
        </div>
    </div>
</section>

// react-app-source/src/pages/Schedule.js
import React, { useState, useEffect, useRef } from 'react';
import { useAudio } from '../contexts/AudioContext';
import { getSchedule } from '../services/api';
import Header from '../components/shared/Header';
import Footer from '../components/shared/Footer';

function Schedule() {
  const { isPlaying } = useAudio();
  const [scheduleItems, setScheduleItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const heroVideoDesktopRef = useRef(null);
  const heroVideoMobileRef = useRef(null);

  useEffect(() => {
    loadSchedule();
  }, []);

  useEffect(() => {
    [heroVideoDesktopRef, heroVideoMobileRef].forEach(ref => {
      const video = ref.current;
      if (video) {
        video.muted = true;
        video.volume = 0;
        if (isPlaying) {
          video.play().catch(() => {});
        } else {
          video.pause();
        }
      }
    });
  }, [isPlaying]);

  const loadSchedule = async () => {
    try {
      setLoading(true);
      const response = await getSchedule();
      if (response.success && response.data) {
        setScheduleItems(response.data);
      } else {
        setError('Failed to load schedule');
      }
    } catch (err) {
      console.error('Error loading schedule:', err);
      setError('Failed to load schedule');
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    window.location.href = '/api/schedule-pdf.cfm';
  };

  return (
    <>
      <Header />

      {/* Hero Section */}
      <section className="page-hero">
        <video ref={heroVideoDesktopRef} id="scheduleVideo" className="hero-video hero-video-desktop" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>
        <video ref={heroVideoMobileRef} id="scheduleVideoMobile" className="hero-video hero-video-mobile" muted loop playsInline>
          <source src="/assets/video/space-background.mp4" type="video/mp4" />
        </video>

        <div className="container">
          <h1 className="hero-title" id="scheduleTitle">Conference Schedule</h1>
          <p className="hero-subtitle" id="scheduleSubtitle">Plan your day of leadership and learning</p>
        </div>
      </section>

      {/* Schedule Timeline Section */}
      <section className="schedule-timeline-section">
        <div className="container">
          <h2 className="section-title">Schedule Timeline</h2>
          <p className="section-description">
            View the complete conference schedule below.
            <button className="btn-download-pdf" onClick={downloadPDF} title="Download Schedule PDF">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="7 10 12 15 17 10"/>
                <line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
              Download PDF
            </button>
          </p>

          {loading && (
            <div className="loading-spinner">
              <div className="spinner"></div>
              <p>Loading schedule...</p>
            </div>
          )}

          {error && (
            <div className="alert alert-error">
              <p>{error}</p>
            </div>
          )}

          {!loading && !error && scheduleItems.length > 0 && (
            <div className="timeline">
              {scheduleItems.map((item, index) => (
                <div key={item.schedule_id || index} className="timeline-item">
                  <div className="timeline-connector"></div>
                  <div className="timeline-content">
                    <div className="time-range">
                      {item.event_time}{item.end_time && ` - ${item.end_time}`}
                    </div>
                    <div className="event-details">
                      <div className="event-header">
                        {item.event_icon && (
                          <span className="event-icon">{item.event_icon}</span>
                        )}
                        <h3 className="event-name">{item.event_name}</h3>
                      </div>
                      {item.event_description && (
                        <p className="event-description">{item.event_description}</p>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {!loading && !error && scheduleItems.length === 0 && (
            <div className="no-schedule">
              <div className="message-icon">&#128197;</div>
              <h3>Schedule Coming Soon</h3>
              <p>Our conference schedule will be available shortly. Check back soon!</p>
            </div>
          )}
        </div>
      </section>

      {/* Workshop Rotation Explanation Section */}
      <section className="rotation-section">
        <div className="container">
          <h2 className="section-title">Workshop Rotation Groups</h2>
          <p className="section-description">
            Conference attendees will be assigned to rotation groups for the workshop sessions.
            Each group follows a different sequence to ensure optimal learning experiences.
          </p>

          <div className="rotation-grid">
            <div className="rotation-card">
              <div className="rotation-header group-a">
                <h3>Group A</h3>
              </div>
              <div className="rotation-sequence">
                <div className="sequence-item">
                  <div className="sequence-number">1</div>
                  <div className="sequence-text">Workshop 1</div>
                </div>
                <div className="sequence-arrow">&rarr;</div>
                <div className="sequence-item">
                  <div className="sequence-number">2</div>
                  <div className="sequence-text">Lunch</div>
                </div>
                <div className="sequence-arrow">&rarr;</div>
                <div className="sequence-item">
                  <div className="sequence-number">3</div>
                  <div className="sequence-text">Workshop 2</div>
                </div>
              </div>
            </div>

            <div className="rotation-card">
              <div className="rotation-header group-b">
                <h3>Group B</h3>
              </div>
              <div className="rotation-sequence">
                <div className="sequence-item">
                  <div className="sequence-number">1</div>
                  <div className="sequence-text">Workshop 1</div>
                </div>
                <div className="sequence-arrow">&rarr;</div>
                <div className="sequence-item">
                  <div className="sequence-number">2</div>
                  <div className="sequence-text">Workshop 2</div>
                </div>
                <div className="sequence-arrow">&rarr;</div>
                <div className="sequence-item">
                  <div className="sequence-number">3</div>
                  <div className="sequence-text">Lunch</div>
                </div>
              </div>
            </div>

            <div className="rotation-card">
              <div className="rotation-header group-c">
                <h3>Group C</h3>
              </div>
              <div className="rotation-sequence">
                <div className="sequence-item">
                  <div className="sequence-number">1</div>
                  <div className="sequence-text">Lunch</div>
                </div>
                <div className="sequence-arrow">&rarr;</div>
                <div className="sequence-item">
                  <div className="sequence-number">2</div>
                  <div className="sequence-text">Workshop 1</div>
                </div>
                <div className="sequence-arrow">&rarr;</div>
                <div className="sequence-item">
                  <div className="sequence-number">3</div>
                  <div className="sequence-text">Workshop 2</div>
                </div>
              </div>
            </div>
          </div>

          <div className="rotation-note">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10"></circle>
              <line x1="12" y1="16" x2="12" y2="12"></line>
              <line x1="12" y1="8" x2="12.01" y2="8"></line>
            </svg>
            <p>Your rotation group will be assigned during registration. Please follow your group's schedule for the best experience.</p>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}

export default Schedule;
